=== AuthFailed/cotl-api/tests/expected-site/v1/schema/weapon.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Weapon",
  "type": "object",
  "required": [
    "id",
    "name",
    "description",
    "namePlain",
    "descriptionPlain",
    "icon",
    "thumb",
    "lore",
    "family",
    "legendary",
    "speed",
    "damage",
    "heavyDamage"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]+$"
    },
    "name": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      },
      "required": [
        "en"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "namePlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "name without the game's text markup"
    },
    "descriptionPlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "description without the game's text markup"
    },
    "icon": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/weapons/[A-Za-z0-9_-]+\\.png$"
    },
    "thumb": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/weapons/64/[A-Za-z0-9_-]+\\.png$"
    },
    "lore": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "family": {
      "type": [
        "string",
        "null"
      ],
      "description": "Sword, Axe, Hammer, Dagger, Gauntlet, Blunderbuss, Chain"
    },
    "legendary": {
      "type": "boolean",
      "description": ""
    },
    "speed": {
      "type": "number",
      "description": "attack speed"
    },
    "damage": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "description": "damage of each hit of the light combo"
    },
    "heavyDamage": {
      "type": [
        "number",
        "null"
      ],
      "description": "heavy attack damage"
    }
  }
}

=== AuthFailed/cotl-api/site/v1/weapons/Gauntlet_Legendary.json
{
  "damage": [
    1.0,
    1.0,
    3.0
  ],
  "description": {
    "ar": "الهجوم الثالث من مجموعة هجمات يستدعي صاعقة.",
    "de": "Der dritte Angriff in einer Kombo beschwört einen Blitzschlag herauf.",
    "en": "The third attack in a combo summons a lightning strike.",
    "es": "Invoca un relámpago con el tercer ataque de un combo.",
    "fr": "La troisième attaque d'un combo invoque la foudre.",
    "fr-CA": "La troisième attaque d'un combo invoque la foudre.",
    "it": "Il terzo attacco di una combo evoca un fulmine.",
    "ja": "コンボ3段目が雷を落とす。",
    "ko": "콤보의 세 번째 공격이 번개를 내려칩니다.",
    "nl": "De derde aanval in een combo roept een blikseminslag op.",
    "pt-BR": "O terceiro ataque em um combo gera um raio.",
    "ru": "Оружие, которое вызывает удар молнии при третьем последовательном ударе.",
    "tr": "Kombonun üçüncü saldırısı bir yıldırım tetikler.",
    "zh-CN": "连击时的第三击召唤一道闪电。",
    "zh-TW": "第三次連擊召喚一道雷擊。"
  },
  "descriptionPlain": {
    "ar": "الهجوم الثالث من مجموعة هجمات يستدعي صاعقة.",
    "de": "Der dritte Angriff in einer Kombo beschwört einen Blitzschlag herauf.",
    "en": "The third attack in a combo summons a lightning strike.",
    "es": "Invoca un relámpago con el tercer ataque de un combo.",
    "fr": "La troisième attaque d'un combo invoque la foudre.",
    "fr-CA": "La troisième attaque d'un combo invoque la foudre.",
    "it": "Il terzo attacco di una combo evoca un fulmine.",
    "ja": "コンボ3段目が雷を落とす。",
    "ko": "콤보의 세 번째 공격이 번개를 내려칩니다.",
    "nl": "De derde aanval in een combo roept een blikseminslag op.",
    "pt-BR": "O terceiro ataque em um combo gera um raio.",
    "ru": "Оружие, которое вызывает удар молнии при третьем последовательном ударе.",
    "tr": "Kombonun üçüncü saldırısı bir yıldırım tetikler.",
    "zh-CN": "连击时的第三击召唤一道闪电。",
    "zh-TW": "第三次連擊召喚一道雷擊。"
  },
  "family": "Gauntlet",
  "heavyDamage": 0.0,
  "icon": "icons/weapons/Gauntlet_Legendary.png",
  "id": "Gauntlet_Legendary",
  "legendary": true,
  "lore": {
    "ar": "قفازان أسطوريان يفحمان عدوك.",
    "de": "Die Panzerhandschuhe der legendären Blasphemie.",
    "en": "The gauntlets of legendary blasphemy.",
    "es": "El guantelete de la blasfemia ancestral.",
    "fr": "Les gantelets du blasphème légendaire.",
    "fr-CA": "Les gantelets du blasphème légendaire.",
    "it": "I guanti della leggendaria blasfemia.",
    "ja": "神を冒涜したとされる伝説の篭手。",
    "ko": "전설적인 모독의 장갑.",
    "nl": "Handschoenen voor legendarische godslastering.",
    "pt-BR": "As manoplas da blasfêmia lendária.",
    "ru": "Перчатки из легенды о богохульстве.",
    "tr": "Efsanevi şirkin eldivenleri.",
    "zh-CN": "传奇亵渎拳套。",
    "zh-TW": "傳奇褻瀆拳套。"
  },
  "name": {
    "ar": "المزدري",
    "de": "Beschmutzer des Göttlichen",
    "en": "Defiler of the Divine",
    "es": "Profanador de la divinidad",
    "fr": "Profanateurs du divin",
    "fr-CA": "Profanateurs du divin",
    "it": "Profanazione del divino",
    "ja": "神々を穢す者",
    "ko": "신성의 모독자",
    "nl": "Ontheiliger van het goddelijke",
    "pt-BR": "Violador da Divindade",
    "ru": "Осквернители божественного",
    "tr": "Kutsalların Kovucusu",
    "zh-CN": "渎圣者",
    "zh-TW": "神聖玷汙者"
  },
  "namePlain": {
    "ar": "المزدري",
    "de": "Beschmutzer des Göttlichen",
    "en": "Defiler of the Divine",
    "es": "Profanador de la divinidad",
    "fr": "Profanateurs du divin",
    "fr-CA": "Profanateurs du divin",
    "it": "Profanazione del divino",
    "ja": "神々を穢す者",
    "ko": "신성의 모독자",
    "nl": "Ontheiliger van het goddelijke",
    "pt-BR": "Violador da Divindade",
    "ru": "Осквернители божественного",
    "tr": "Kutsalların Kovucusu",
    "zh-CN": "渎圣者",
    "zh-TW": "神聖玷汙者"
  },
  "speed": 0.8,
  "thumb": "icons/weapons/64/Gauntlet_Legendary.png"
}

=== AuthFailed/cotl-api/site/v1/weapons/Sword_Godly.json
{
  "damage": [
    2.0,
    2.0,
    2.0
  ],
  "description": {
    "ar": "يلحق ضررًا أكبر بكثير من ضرر أسلحة الفانين.",
    "de": "Teilt erheblich mehr Schaden als gewöhnliche Waffen aus.",
    "en": "Deal significantly more damage than mortal weapons.",
    "es": "Inflige más daño que las armas mortales.",
    "fr": "Inflige nettement plus de dégâts que les armes ordinaires.",
    "fr-CA": "Inflige beaucoup plus de dégâts que les armes ordinaires.",
    "it": "Infligge danni significativamente maggiori rispetto alle armi mortali.",
    "ja": "通常の武器よりも強大な破壊力を誇る。",
    "ko": "필멸의 무기보다 훨씬 더 많은 피해를 입힙니다.",
    "nl": "Breng aanzienlijk meer schade toe dan met stervelingwapens.",
    "pt-BR": "Armas Celestiais causam dano consideravelmente maior que as armas de mortais.",
    "ru": "Оружие, которое наносит гораздо больше урона, чем обычное.",
    "tr": "Fâni silahlara kıyasla çok daha fazla hasar verir.",
    "zh-CN": "造成远胜凡间武器的伤害。",
    "zh-TW": "造成遠勝凡間武器的傷害。"
  },
  "descriptionPlain": {
    "ar": "يلحق ضررًا أكبر بكثير من ضرر أسلحة الفانين.",
    "de": "Teilt erheblich mehr Schaden als gewöhnliche Waffen aus.",
    "en": "Deal significantly more damage than mortal weapons.",
    "es": "Inflige más daño que las armas mortales.",
    "fr": "Inflige nettement plus de dégâts que les armes ordinaires.",
    "fr-CA": "Inflige beaucoup plus de dégâts que les armes ordinaires.",
    "it": "Infligge danni significativamente maggiori rispetto alle armi mortali.",
    "ja": "通常の武器よりも強大な破壊力を誇る。",
    "ko": "필멸의 무기보다 훨씬 더 많은 피해를 입힙니다.",
    "nl": "Breng aanzienlijk meer schade toe dan met stervelingwapens.",
    "pt-BR": "Armas Celestiais causam dano consideravelmente maior que as armas de mortais.",
    "ru": "Оружие, которое наносит гораздо больше урона, чем обычное.",
    "tr": "Fâni silahlara kıyasla çok daha fazla hasar verir.",
    "zh-CN": "造成远胜凡间武器的伤害。",
    "zh-TW": "造成遠勝凡間武器的傷害。"
  },
  "family": "Sword",
  "heavyDamage": 0.0,
  "icon": "icons/weapons/Sword_Godly.png",
  "id": "Sword_Godly",
  "legendary": false,
  "lore": {
    "ar": "كان يُستخدم لإراقة دماء السادة...",
    "de": "Wurde einst dazu verwendet, einen Gott zu verwunden …",
    "en": "Once used to draw Godly blood...",
    "es": "Otrora usada para derramar sangre divina...",
    "fr": "Autrefois utilisée pour faire couler le sang des dieux...",
    "fr-CA": "Autrefois utilisée pour faire couler le sang des dieux...",
    "it": "Un tempo utilizzata per spillare sangue divino...",
    "ja": "かつては神に血を流させるために使われていたという…",
    "ko": "신의 피를 흘리기 위해 사용되었던 것이다...",
    "nl": "Ooit gebruikt om goddelijk bloed te laten vloeien...",
    "pt-BR": "Já foi usada para derramar sangue Celestial...",
    "ru": "Когда-то это лезвие обагрила кровь бога.",
    "tr": "Bir zamanlar Tanrıların kanını dökmek için kullanılıyordu...",
    "zh-CN": "曾用来弑神之血……",
    "zh-TW": "曾用來使神見血……"
  },
  "name": {
    "ar": "سيف السادة",
    "de": "Göttliches Schwert",
    "en": "Godly Sword",
    "es": "Espada divina",
    "fr": "Épée divine",
    "fr-CA": "Épée divine",
    "it": "Spada divina",
    "ja": "神なる剣",
    "ko": "신성한 검",
    "nl": "Goddelijke zwaard",
    "pt-BR": "Espada Celestial",
    "ru": "Священный меч",
    "tr": "Tanrıların Kılıcı",
    "zh-CN": "神力之剑",
    "zh-TW": "神力之劍"
  },
  "namePlain": {
    "ar": "سيف السادة",
    "de": "Göttliches Schwert",
    "en": "Godly Sword",
    "es": "Espada divina",
    "fr": "Épée divine",
    "fr-CA": "Épée divine",
    "it": "Spada divina",
    "ja": "神なる剣",
    "ko": "신성한 검",
    "nl": "Goddelijke zwaard",
    "pt-BR": "Espada Celestial",
    "ru": "Священный меч",
    "tr": "Tanrıların Kılıcı",
    "zh-CN": "神力之剑",
    "zh-TW": "神力之劍"
  },
  "speed": 1.0,
  "thumb": "icons/weapons/64/Sword_Godly.png"
}

=== AuthFailed/cotl-api/site/v1/weapons/Blunderbuss_Healing.json
{
  "damage": [
    2.7
  ],
  "description": {
    "ar": "تتيح فرصة لعلاج حاملها باستخدام قوة الحياة لعدو مقتول.",
    "de": "Gewährt die Chance, den Träger mit der Lebenskraft eines getöteten Gegners zu heilen.",
    "en": "Chance to heal the wielder using the life force of a slain foe.",
    "es": "Probabilidad de curar al portador absorbiendo la fuerza vital de un enemigo asesinado.",
    "fr": "Vous soigne parfois lorsque vous tuez un ennemi.",
    "fr-CA": "Vous soigne parfois lorsque vous tuez un ennemi.",
    "it": "Ha la possibilità di curare chi lo impugna, con la forza vitale dei nemici debellati.",
    "ja": "一定確率で倒した敵の生命力を吸い取り、使用者の体力を回復する。",
    "ko": "죽은 적들의 생명력으로 착용자를 일정 확률로 회복시킵니다.",
    "nl": "Kans om de gebruiker te genezen met de levenskracht van een verslagen vijand.",
    "pt-BR": "Chance de curar seu portador com a força vital de um inimigo morto.",
    "ru": "Оружие, которое иногда передаёт владельцу жизненную силу врага.",
    "tr": "Katledilen bir düşmanın yaşam enerjisini kullanarak seni iyileştirme ihtimali vardır.",
    "zh-CN": "有一定机率能运用死去敌人的生命力，治疗武器使用者。",
    "zh-TW": "有一定機率能運用死去敵人的生命力，治療武器使用者。"
  },
  "descriptionPlain": {
    "ar": "تتيح فرصة لعلاج حاملها باستخدام قوة الحياة لعدو مقتول.",
    "de": "Gewährt die Chance, den Träger mit der Lebenskraft eines getöteten Gegners zu heilen.",
    "en": "Chance to heal the wielder using the life force of a slain foe.",
    "es": "Probabilidad de curar al portador absorbiendo la fuerza vital de un enemigo asesinado.",
    "fr": "Vous soigne parfois lorsque vous tuez un ennemi.",
    "fr-CA": "Vous soigne parfois lorsque vous tuez un ennemi.",
    "it": "Ha la possibilità di curare chi lo impugna, con la forza vitale dei nemici debellati.",
    "ja": "一定確率で倒した敵の生命力を吸い取り、使用者の体力を回復する。",
    "ko": "죽은 적들의 생명력으로 착용자를 일정 확률로 회복시킵니다.",
    "nl": "Kans om de gebruiker te genezen met de levenskracht van een verslagen vijand.",
    "pt-BR": "Chance de curar seu portador com a força vital de um inimigo morto.",
    "ru": "Оружие, которое иногда передаёт владельцу жизненную силу врага.",
    "tr": "Katledilen bir düşmanın yaşam enerjisini kullanarak seni iyileştirme ihtimali vardır.",
    "zh-CN": "有一定机率能运用死去敌人的生命力，治疗武器使用者。",
    "zh-TW": "有一定機率能運用死去敵人的生命力，治療武器使用者。"
  },
  "family": "Blunderbuss",
  "heavyDamage": 0.0,
  "icon": "icons/weapons/Blunderbuss_Healing.png",
  "id": "Blunderbuss_Healing",
  "legendary": false,
  "lore": {
    "ar": "استدعاء حياة للاستحواذ عليها.",
    "de": "Hol dir ein Leben, um es zu verzehren.",
    "en": "Fetch a life to be consumed.",
    "es": "Rastrea una vida que consumir.",
    "fr": "Une vie perdue contre une vie sauvée.",
    "fr-CA": "Une vie perdue contre une vie sauvée.",
    "it": "Scegli una vita da consumare.",
    "ja": "獲物でしかない命を吸い取れ。",
    "ko": "생명력을 빼앗아 흡수한다.",
    "nl": "Pik een leven in voor consumptie.",
    "pt-BR": "Capture uma alma para consumir.",
    "ru": "Чужая жизнь — ваша.",
    "tr": "Tükenmeyi bekleyen hayatların eceli.",
    "zh-CN": "夺取生命并加以吞噬。",
    "zh-TW": "奪取生命並加以吞噬。"
  },
  "name": {
    "ar": "بندقية مصاص الدماء القصيرة",
    "de": "Vampir-Donnerbüchse",
    "en": "Vampiric Blunderbuss",
    "es": "Trabuco vampírico",
    "fr": "Tromblon vampirique",
    "fr-CA": "Tromblon vampirique",
    "it": "Schioppo vampiresco",
    "ja": "吸血の銃",
    "ko": "흡혈 나팔총",
    "nl": "Vampierdonderbus",
    "pt-BR": "Bacamarte Vampírico",
    "ru": "Вампирический мушкетон",
    "tr": "Cani Alaybozan",
    "zh-CN": "吸血之枪",
    "zh-TW": "吸血之槍"
  },
  "namePlain": {
    "ar": "بندقية مصاص الدماء القصيرة",
    "de": "Vampir-Donnerbüchse",
    "en": "Vampiric Blunderbuss",
    "es": "Trabuco vampírico",
    "fr": "Tromblon vampirique",
    "fr-CA": "Tromblon vampirique",
    "it": "Schioppo vampiresco",
    "ja": "吸血の銃",
    "ko": "흡혈 나팔총",
    "nl": "Vampierdonderbus",
    "pt-BR": "Bacamarte Vampírico",
    "ru": "Вампирический мушкетон",
    "tr": "Cani Alaybozan",
    "zh-CN": "吸血之枪",
    "zh-TW": "吸血之槍"
  },
  "speed": 1.0,
  "thumb": "icons/weapons/64/Blunderbuss_Healing.png"
}

=== AuthFailed/cotl-api/site/v1/weapons/Blunderbuss_Legendary.json
{
  "damage": [
    2.7
  ],
  "description": {
    "ar": "تطلق 3 قذائف دفعة واحدة.",
    "de": "Verschießt drei Projektile mit einem Schuss.",
    "en": "Shoots 3 projectiles in one shot.",
    "es": "Arroja 3 proyectiles de un solo disparo.",
    "fr": "Tire trois projectiles à chaque coup.",
    "fr-CA": "Tire trois projectiles à chaque coup.",
    "it": "Spara 3 proiettili in un colpo solo.",
    "ja": "一度の射撃で弾を3発射出する。",
    "ko": "한 번에 탄환 3개를 발사합니다.",
    "nl": "Schiet 3 projectielen in één keer.",
    "pt-BR": "Dispare 3 projéteis de uma vez.",
    "ru": "Оружие, которое выпускает по 3 пули.",
    "tr": "Tek saldırıda 3 mermi ateşler.",
    "zh-CN": "一枪可射出 3 个投射物。",
    "zh-TW": "一槍射出 3 個投射物。"
  },
  "descriptionPlain": {
    "ar": "تطلق 3 قذائف دفعة واحدة.",
    "de": "Verschießt drei Projektile mit einem Schuss.",
    "en": "Shoots 3 projectiles in one shot.",
    "es": "Arroja 3 proyectiles de un solo disparo.",
    "fr": "Tire trois projectiles à chaque coup.",
    "fr-CA": "Tire trois projectiles à chaque coup.",
    "it": "Spara 3 proiettili in un colpo solo.",
    "ja": "一度の射撃で弾を3発射出する。",
    "ko": "한 번에 탄환 3개를 발사합니다.",
    "nl": "Schiet 3 projectielen in één keer.",
    "pt-BR": "Dispare 3 projéteis de uma vez.",
    "ru": "Оружие, которое выпускает по 3 пули.",
    "tr": "Tek saldırıda 3 mermi ateşler.",
    "zh-CN": "一枪可射出 3 个投射物。",
    "zh-TW": "一槍射出 3 個投射物。"
  },
  "family": "Blunderbuss",
  "heavyDamage": 0.0,
  "icon": "icons/weapons/Blunderbuss_Legendary.png",
  "id": "Blunderbuss_Legendary",
  "legendary": true,
  "lore": {
    "ar": "بندقية قصيرة أسطورية تكتسح هدفها.",
    "de": "Die Donnerbüchse der legendären Gier.",
    "en": "The blunderbuss of legendary greed.",
    "es": "El trabuco de la avaricia ancestral.",
    "fr": "Le tromblon de la cupidité légendaire.",
    "fr-CA": "Le tromblon de la cupidité légendaire.",
    "it": "Lo schioppo della leggendaria avidità.",
    "ja": "底なしの欲にまみれた伝説の銃。",
    "ko": "전설적인 탐욕의 나팔총.",
    "nl": "Een donderbus van legendarische hebzucht.",
    "pt-BR": "O bacamarte da ganância lendária.",
    "ru": "Мушкетон из легенды о жадности.",
    "tr": "Efsanevi cimriliğin alaybozanı.",
    "zh-CN": "传奇贪婪之枪。",
    "zh-TW": "傳奇貪婪之槍。"
  },
  "name": {
    "ar": "مصير بليمبو الأول",
    "de": "Schicksal von Plimbo dem Ersten",
    "en": "Fate of Plimbo the First",
    "es": "Hado de Plimbo el Primigenio",
    "fr": "Destin de Plimbo Ier",
    "fr-CA": "Destin de Plimbo Ier",
    "it": "Sorte di Plimbo il Vecchio",
    "ja": "プリンボ1世の宿命",
    "ko": "첫째 플림보의 운명",
    "nl": "Lot van Plimbo de eerste",
    "pt-BR": "Sina de Plimbo, o Primeiro",
    "ru": "Участь Плимбо Первого",
    "tr": "İlk Plimbo'nun Kaderi",
    "zh-CN": "普霖波一世之命运",
    "zh-TW": "普霖波一世之命"
  },
  "namePlain": {
    "ar": "مصير بليمبو الأول",
    "de": "Schicksal von Plimbo dem Ersten",
    "en": "Fate of Plimbo the First",
    "es": "Hado de Plimbo el Primigenio",
    "fr": "Destin de Plimbo Ier",
    "fr-CA": "Destin de Plimbo Ier",
    "it": "Sorte di Plimbo il Vecchio",
    "ja": "プリンボ1世の宿命",
    "ko": "첫째 플림보의 운명",
    "nl": "Lot van Plimbo de eerste",
    "pt-BR": "Sina de Plimbo, o Primeiro",
    "ru": "Участь Плимбо Первого",
    "tr": "İlk Plimbo'nun Kaderi",
    "zh-CN": "普霖波一世之命运",
    "zh-TW": "普霖波一世之命"
  },
  "speed": 1.0,
  "thumb": "icons/weapons/64/Blunderbuss_Legendary.png"
}

=== AuthFailed/cotl-api/site/v1/weapons/Sword.json
{
  "damage": [
    1.0,
    1.0,
    1.0
  ],
  "description": {
    "ar": "نصل متزن يلحق ضررًا متوسطًا.",
    "de": "Eine gut ausbalancierte Klinge, die moderaten Schaden verursacht.",
    "en": "A well balanced blade dealing moderate damage.",
    "es": "Una espada bien equilibrada que inflige bastante daño.",
    "fr": "Une épée équilibrée qui inflige des dégâts modérés.",
    "fr-CA": "Une épée équilibrée qui inflige des dégâts modérés.",
    "it": "Una lama ben bilanciata che infligge danni moderati.",
    "ja": "バランスの取れた扱いやすい剣。",
    "ko": "적당한 피해를 주는 균형잡힌 칼입니다.",
    "nl": "Een zwaard met een goede balans voor gemiddelde schade.",
    "pt-BR": "Uma lâmina bem equilibrada que causa dano moderado.",
    "ru": "Клинок с хорошим балансом.",
    "tr": "Ortalama hasar veren, dengeli bir kılıç.",
    "zh-CN": "功能平衡的刀刃，造成中量伤害。",
    "zh-TW": "功能平衡的刀刃，造成中量傷害。"
  },
  "descriptionPlain": {
    "ar": "نصل متزن يلحق ضررًا متوسطًا.",
    "de": "Eine gut ausbalancierte Klinge, die moderaten Schaden verursacht.",
    "en": "A well balanced blade dealing moderate damage.",
    "es": "Una espada bien equilibrada que inflige bastante daño.",
    "fr": "Une épée équilibrée qui inflige des dégâts modérés.",
    "fr-CA": "Une épée équilibrée qui inflige des dégâts modérés.",
    "it": "Una lama ben bilanciata che infligge danni moderati.",
    "ja": "バランスの取れた扱いやすい剣。",
    "ko": "적당한 피해를 주는 균형잡힌 칼입니다.",
    "nl": "Een zwaard met een goede balans voor gemiddelde schade.",
    "pt-BR": "Uma lâmina bem equilibrada que causa dano moderado.",
    "ru": "Клинок с хорошим балансом.",
    "tr": "Ortalama hasar veren, dengeli bir kılıç.",
    "zh-CN": "功能平衡的刀刃，造成中量伤害。",
    "zh-TW": "功能平衡的刀刃，造成中量傷害。"
  },
  "family": "Sword",
  "heavyDamage": 0.0,
  "icon": "icons/weapons/Sword.png",
  "id": "Sword",
  "legendary": false,
  "lore": {
    "ar": "الرفيق القوي للمحارب المتجول.",
    "de": "Ein treuer Begleiter des wandernden Kriegers.",
    "en": "Stalwart companion to the wandering warrior.",
    "es": "Leal acompañante de los guerreros errantes.",
    "fr": "Fidèle compagnon des guerriers vagabonds.",
    "fr-CA": "Fidèle compagnon des guerriers vagabonds.",
    "it": "Compagna fedele del guerriero errante.",
    "ja": "彷徨う戦士にとっては頼れる相棒だ。",
    "ko": "방랑하는 전사에게 있어 든든한 동반자이다.",
    "nl": "Loyale metgezel voor de zwervende krijger.",
    "pt-BR": "Fiel escudeiro para o guerreiro errante.",
    "ru": "Верный товарищ многих странствующих воинов.",
    "tr": "Macerasever savaşçıların güvenilir yoldaşı.",
    "zh-CN": "流浪战士的忠实伙伴。",
    "zh-TW": "流浪戰士的忠實夥伴。"
  },
  "name": {
    "ar": "نصل المحارب",
    "de": "Klinge des Kreuzfahrers",
    "en": "Crusader's Blade",
    "es": "Espada de misionero",
    "fr": "Lame des croisades",
    "fr-CA": "Lame des croisades",
    "it": "Spada del crociato",
    "ja": "聖戦士の剣",
    "ko": "성기사의 검",
    "nl": "Kruisvaarderszwaard",
    "pt-BR": "Lâmina do Cavaleiro",
    "ru": "Меч завоевателей",
    "tr": "Seferber Kılıcı",
    "zh-CN": "圣战士之刃",
    "zh-TW": "聖戰士之刃"
  },
  "namePlain": {
    "ar": "نصل المحارب",
    "de": "Klinge des Kreuzfahrers",
    "en": "Crusader's Blade",
    "es": "Espada de misionero",
    "fr": "Lame des croisades",
    "fr-CA": "Lame des croisades",
    "it": "Spada del crociato",
    "ja": "聖戦士の剣",
    "ko": "성기사의 검",
    "nl": "Kruisvaarderszwaard",
    "pt-BR": "Lâmina do Cavaleiro",
    "ru": "Меч завоевателей",
    "tr": "Seferber Kılıcı",
    "zh-CN": "圣战士之刃",
    "zh-TW": "聖戰士之刃"
  },
  "speed": 1.0,
  "thumb": "icons/weapons/64/Sword.png"
}

=== AuthFailed/cotl-api/site/v1/weapons/Gauntlet_Fervour.json
{
  "damage": [
    1.0,
    1.0,
    3.0
  ],
  "description": {
    "ar": "الحماس <sprite name=\"icon_blackSoul\"> الذي جمعته سيزيد أيضًا شريط الإلهام المقدر لديك.",
    "de": "Gesammelter Eifer <sprite name=\"icon_blackSoul\"> vergrößert auch deine Göttliche-Inspiration-Leiste.",
    "en": "Collected Fervour <sprite name=\"icon_blackSoul\"> will also increase your Divine Inspiration bar.",
    "es": "El fervor que recojas <sprite name=\"icon_blackSoul\"> también aumentará tu barra de inspiración divina.",
    "fr": "Vous permettent d'utiliser la ferveur collectée <sprite name=\"icon_blackSoul\"> pour augmenter votre barre d'inspiration divine.",
    "fr-CA": "Vous permettent d'utiliser la ferveur collectée <sprite name=\"icon_blackSoul\"> pour augmenter votre barre d'inspiration divine.",
    "it": "Il Fervore <sprite name=\"icon_blackSoul\"> raccolto aumenterà anche la tua barra Ispirazione divina.",
    "ja": "信力 <sprite name=\"icon_blackSoul\"> を獲得すると神聖なる啓示バーが増加する。",
    "ko": "획득한 열정 <sprite name=\"icon_blackSoul\">은 또한 종교적 영감 게이지를 증가시킵니다.",
    "nl": "Verzamelde furie <sprite name=\"icon_blackSoul\"> vult ook je goddelijke inspiratie-balk.",
    "pt-BR": "O Fervor <sprite name=\"icon_blackSoul\"> coletado também aumentará a sua barra de Inspiração Divina.",
    "ru": "Оружие, которое пополняет шкалу откровения при накоплении усердия <sprite name=\"icon_blackSoul\">.",
    "tr": "Toplanan Şevk <sprite name=\"icon_blackSoul\"> aynı zamanda İlahi İlham göstergesini de doldurur.",
    "zh-CN": "你收集到的热诚 <sprite name=\"icon_blackSoul\"> 将填充圣冠灵感条。",
    "zh-TW": "你收集到的熱誠 <sprite name=\"icon_blackSoul\"> 將填充聖冠靈感條。"
  },
  "descriptionPlain": {
    "ar": "الحماس الذي جمعته سيزيد أيضًا شريط الإلهام المقدر لديك.",
    "de": "Gesammelter Eifer vergrößert auch deine Göttliche-Inspiration-Leiste.",
    "en": "Collected Fervour will also increase your Divine Inspiration bar.",
    "es": "El fervor que recojas también aumentará tu barra de inspiración divina.",
    "fr": "Vous permettent d'utiliser la ferveur collectée pour augmenter votre barre d'inspiration divine.",
    "fr-CA": "Vous permettent d'utiliser la ferveur collectée pour augmenter votre barre d'inspiration divine.",
    "it": "Il Fervore raccolto aumenterà anche la tua barra Ispirazione divina.",
    "ja": "信力 を獲得すると神聖なる啓示バーが増加する。",
    "ko": "획득한 열정 은 또한 종교적 영감 게이지를 증가시킵니다.",
    "nl": "Verzamelde furie vult ook je goddelijke inspiratie-balk.",
    "pt-BR": "O Fervor coletado também aumentará a sua barra de Inspiração Divina.",
    "ru": "Оружие, которое пополняет шкалу откровения при накоплении усердия.",
    "tr": "Toplanan Şevk aynı zamanda İlahi İlham göstergesini de doldurur.",
    "zh-CN": "你收集到的热诚 将填充圣冠灵感条。",
    "zh-TW": "你收集到的熱誠 將填充聖冠靈感條。"
  },
  "family": "Gauntlet",
  "heavyDamage": 0.0,
  "icon": "icons/weapons/Gauntlet_Fervour.png",
  "id": "Gauntlet_Fervour",
  "legendary": false,
  "lore": {
    "ar": "يحميان من الشك.",
    "de": "Schützt vor Zweifeln.",
    "en": "Protects against doubt.",
    "es": "Protege de la duda.",
    "fr": "Vous protège du doute.",
    "fr-CA": "Vous protège du doute.",
    "it": "Non dubiterai mai dei tuoi ideali.",
    "ja": "疑心に対する加護を与えてくれる。",
    "ko": "의심을 떨쳐버릴 수 있다.",
    "nl": "Beschermt tegen twijfel.",
    "pt-BR": "Protege contra a dúvida.",
    "ru": "Разят без сомнения.",
    "tr": "Şüpheye yer yok.",
    "zh-CN": "防止产生疑虑。",
    "zh-TW": "抵禦疑慮。"
  },
  "name": {
    "ar": "قفازا الإقدام",
    "de": "Eifer-Panzerhandschuh",
    "en": "Zealous Gauntlet",
    "es": "Guantelete ferviente",
    "fr": "Gant occulte",
    "fr-CA": "Gant fervent",
    "it": "Guanti ferventi",
    "ja": "篤信なる篭手",
    "ko": "열성의 건틀릿",
    "nl": "Onverstoorbare handschoenen",
    "pt-BR": "Manopla Zelosa",
    "ru": "Неистовые перчатки",
    "tr": "Hırs Eldiveni",
    "zh-CN": "狂热拳套",
    "zh-TW": "狂熱拳套"
  },
  "namePlain": {
    "ar": "قفازا الإقدام",
    "de": "Eifer-Panzerhandschuh",
    "en": "Zealous Gauntlet",
    "es": "Guantelete ferviente",
    "fr": "Gant occulte",
    "fr-CA": "Gant fervent",
    "it": "Guanti ferventi",
    "ja": "篤信なる篭手",
    "ko": "열성의 건틀릿",
    "nl": "Onverstoorbare handschoenen",
    "pt-BR": "Manopla Zelosa",
    "ru": "Неистовые перчатки",
    "tr": "Hırs Eldiveni",
    "zh-CN": "狂热拳套",
    "zh-TW": "狂熱拳套"
  },
  "speed": 0.8,
  "thumb": "icons/weapons/64/Gauntlet_Fervour.png"
}

=== AuthFailed/cotl-api/site/v1/weapons/Axe_Poison.json
{
  "damage": [
    2.0,
    2.0,
    2.0
  ],
  "description": {
    "ar": "تتيح فرصة لتسميم الأعداء عند الهجوم.",
    "de": "Gewährt die Chance, angegriffene Gegner zu vergiften.",
    "en": "Chance of poisoning enemies when attacking.",
    "es": "Probabilidad de envenenar a los enemigos al atacar.",
    "fr": "Empoisonne parfois les ennemis que vous attaquez.",
    "fr-CA": "Empoisonne parfois les ennemis que vous attaquez.",
    "it": "Ha la possibilità di avvelenare i nemici che attacchi.",
    "ja": "攻撃時、一定確率で毒を付与する。",
    "ko": "공격을 할 때 일정 확률로 적들을 중독시킵니다.",
    "nl": "Kans op vergiftigen van vijanden bij aanvallen.",
    "pt-BR": "Chance de envenenar inimigos ao atacá-los.",
    "ru": "Оружие, которое отравляет врагов.",
    "tr": "Düşmanları zehirleme ihtimali vardır.",
    "zh-CN": "攻击时有一定机率使敌人中毒。",
    "zh-TW": "攻擊時有一定機率使敵人中毒。"
  },
  "descriptionPlain": {
    "ar": "تتيح فرصة لتسميم الأعداء عند الهجوم.",
    "de": "Gewährt die Chance, angegriffene Gegner zu vergiften.",
    "en": "Chance of poisoning enemies when attacking.",
    "es": "Probabilidad de envenenar a los enemigos al atacar.",
    "fr": "Empoisonne parfois les ennemis que vous attaquez.",
    "fr-CA": "Empoisonne parfois les ennemis que vous attaquez.",
    "it": "Ha la possibilità di avvelenare i nemici che attacchi.",
    "ja": "攻撃時、一定確率で毒を付与する。",
    "ko": "공격을 할 때 일정 확률로 적들을 중독시킵니다.",
    "nl": "Kans op vergiftigen van vijanden bij aanvallen.",
    "pt-BR": "Chance de envenenar inimigos ao atacá-los.",
    "ru": "Оружие, которое отравляет врагов.",
    "tr": "Düşmanları zehirleme ihtimali vardır.",
    "zh-CN": "攻击时有一定机率使敌人中毒。",
    "zh-TW": "攻擊時有一定機率使敵人中毒。"
  },
  "family": "Axe",
  "heavyDamage": 0.0,
  "icon": "icons/weapons/Axe_Poison.png",
  "id": "Axe_Poison",
  "legendary": false,
  "lore": {
    "ar": "يتوسل المسموم لإنهاء معاناته بالنصل.",
    "de": "Einmal vom Gift getroffen, wird man süchtig nach der Klinge.",
    "en": "Once struck by the toxins, one begs for the blade.",
    "es": "Cuando las toxinas te infectan, solo desearás la muerte.",
    "fr": "Vos ennemis vous supplieront de les achever.",
    "fr-CA": "Vos ennemis vous supplieront de les achever.",
    "it": "Una volta esposti alle tossine, si implora la lama.",
    "ja": "毒をその身に受けた者は、死による救済を請うことだろう。",
    "ko": "독에 명중당한 적은 죽음을 구걸하게 될 것이다.",
    "nl": "Zodra het gif door de aderen stroomt, zullen ze smeken om de genadeklap.",
    "pt-BR": "Quando atingido pelas toxinas, vai implorar pela lâmina.",
    "ru": "Яд страшнее любого клинка.",
    "tr": "Zehri kapan baltayı mumla arar.",
    "zh-CN": "中了毒素的伤者将乞求一击致命，得以解脱。",
    "zh-TW": "中了毒素的傷者將乞求一擊致命好得以解脫。"
  },
  "name": {
    "ar": "فأس الهلاك",
    "de": "Tückische Axt",
    "en": "Bane Axe",
    "es": "Hacha de la perdición",
    "fr": "Hache maudite",
    "fr-CA": "Hache maudite",
    "it": "Ascia velenosa",
    "ja": "有毒なる斧",
    "ko": "파멸의 도끼",
    "nl": "Venijnbijl",
    "pt-BR": "Machado Peçonhento",
    "ru": "Истощающий топор",
    "tr": "Zehirli Balta",
    "zh-CN": "恶毒之斧",
    "zh-TW": "惡毒之斧"
  },
  "namePlain": {
    "ar": "فأس الهلاك",
    "de": "Tückische Axt",
    "en": "Bane Axe",
    "es": "Hacha de la perdición",
    "fr": "Hache maudite",
    "fr-CA": "Hache maudite",
    "it": "Ascia velenosa",
    "ja": "有毒なる斧",
    "ko": "파멸의 도끼",
    "nl": "Venijnbijl",
    "pt-BR": "Machado Peçonhento",
    "ru": "Истощающий топор",
    "tr": "Zehirli Balta",
    "zh-CN": "恶毒之斧",
    "zh-TW": "惡毒之斧"
  },
  "speed": 0.5,
  "thumb": "icons/weapons/64/Axe_Poison.png"
}
