=== AuthFailed/cotl-api/tests/expected-site/v1/schema/weapon.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Weapon",
  "type": "object",
  "required": [
    "id",
    "name",
    "description",
    "namePlain",
    "descriptionPlain",
    "icon",
    "thumb",
    "lore",
    "family",
    "legendary",
    "speed",
    "damage",
    "heavyDamage"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]+$"
    },
    "name": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      },
      "required": [
        "en"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "namePlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "name without the game's text markup"
    },
    "descriptionPlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "description without the game's text markup"
    },
    "icon": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/weapons/[A-Za-z0-9_-]+\\.png$"
    },
    "thumb": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/weapons/64/[A-Za-z0-9_-]+\\.png$"
    },
    "lore": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "family": {
      "type": [
        "string",
        "null"
      ],
      "description": "Sword, Axe, Hammer, Dagger, Gauntlet, Blunderbuss, Chain"
    },
    "legendary": {
      "type": "boolean",
      "description": ""
    },
    "speed": {
      "type": "number",
      "description": "attack speed"
    },
    "damage": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "description": "damage of each hit of the light combo"
    },
    "heavyDamage": {
      "type": [
        "number",
        "null"
      ],
      "description": "heavy attack damage"
    }
  }
}

=== AuthFailed/cotl-api/site/v1/weapons/Axe_Fervour.json
{
  "damage": [
    2.0,
    2.0,
    2.0
  ],
  "description": {
    "ar": "الحماس <sprite name=\"icon_blackSoul\"> الذي جمعته سيزيد أيضًا شريط الإلهام المقدر لديك.",
    "de": "Gesammelter Eifer <sprite name=\"icon_blackSoul\"> vergrößert auch deine Göttliche-Inspiration-Leiste.",
    "en": "Collected Fervour <sprite name=\"icon_blackSoul\"> will also increase your Divine Inspiration bar.",
    "es": "El fervor que recojas <sprite name=\"icon_blackSoul\"> también aumentará tu barra de inspiración divina.",
    "fr": "Vous permettent d'utiliser la ferveur collectée <sprite name=\"icon_blackSoul\"> pour augmenter votre barre d'inspiration divine.",
    "fr-CA": "Vous permettent d'utiliser la ferveur collectée <sprite name=\"icon_blackSoul\"> pour augmenter votre barre d'inspiration divine.",
    "it": "Il Fervore <sprite name=\"icon_blackSoul\"> raccolto aumenterà anche la tua barra Ispirazione divina.",
    "ja": "信力 <sprite name=\"icon_blackSoul\"> を獲得すると神聖なる啓示バーが増加する。",
    "ko": "획득한 열정 <sprite name=\"icon_blackSoul\">은 또한 종교적 영감 게이지를 증가시킵니다.",
    "nl": "Verzamelde furie <sprite name=\"icon_blackSoul\"> vult ook je goddelijke inspiratie-balk.",
    "pt-BR": "O Fervor <sprite name=\"icon_blackSoul\"> coletado também aumentará a sua barra de Inspiração Divina.",
    "ru": "Оружие, которое пополняет шкалу откровения при накоплении усердия <sprite name=\"icon_blackSoul\">.",
    "tr": "Toplanan Şevk <sprite name=\"icon_blackSoul\"> aynı zamanda İlahi İlham göstergesini de doldurur.",
    "zh-CN": "你收集到的热诚 <sprite name=\"icon_blackSoul\"> 将填充圣冠灵感条。",
    "zh-TW": "你收集到的熱誠 <sprite name=\"icon_blackSoul\"> 將填充聖冠靈感條。"
  },
  "descriptionPlain": {
    "ar": "الحماس الذي جمعته سيزيد أيضًا شريط الإلهام المقدر لديك.",
    "de": "Gesammelter Eifer vergrößert auch deine Göttliche-Inspiration-Leiste.",
    "en": "Collected Fervour will also increase your Divine Inspiration bar.",
    "es": "El fervor que recojas también aumentará tu barra de inspiración divina.",
    "fr": "Vous permettent d'utiliser la ferveur collectée pour augmenter votre barre d'inspiration divine.",
    "fr-CA": "Vous permettent d'utiliser la ferveur collectée pour augmenter votre barre d'inspiration divine.",
    "it": "Il Fervore raccolto aumenterà anche la tua barra Ispirazione divina.",
    "ja": "信力 を獲得すると神聖なる啓示バーが増加する。",
    "ko": "획득한 열정 은 또한 종교적 영감 게이지를 증가시킵니다.",
    "nl": "Verzamelde furie vult ook je goddelijke inspiratie-balk.",
    "pt-BR": "O Fervor coletado também aumentará a sua barra de Inspiração Divina.",
    "ru": "Оружие, которое пополняет шкалу откровения при накоплении усердия.",
    "tr": "Toplanan Şevk aynı zamanda İlahi İlham göstergesini de doldurur.",
    "zh-CN": "你收集到的热诚 将填充圣冠灵感条。",
    "zh-TW": "你收集到的熱誠 將填充聖冠靈感條。"
  },
  "family": "Axe",
  "heavyDamage": 0.0,
  "icon": "icons/weapons/Axe_Fervour.png",
  "id": "Axe_Fervour",
  "legendary": false,
  "lore": {
    "ar": "كان يستخدمها المقدام العظيم لإعدام المنشقين.",
    "de": "Wurde von dem großen Fanatiker dazu verwendet, Ketzer hinzurichten.",
    "en": "Used by the great Fanatic to execute heretics.",
    "es": "Usada por los grandes fanáticos para ejecutar a los herejes.",
    "fr": "Utilisée par les fanatiques pour exécuter les hérétiques.",
    "fr-CA": "Utilisée par les fanatiques pour exécuter les hérétiques.",
    "it": "Brandita dalla grande Fanatica per giustiziare gli eretici.",
    "ja": "とある偉大な狂信者が、異端者を殺すために使っていた武器。",
    "ko": "훌륭한 광신자들이 이단자들을 처형할 때 사용한다.",
    "nl": "Gebruikt door de grote zeloot om ketters te executeren.",
    "pt-BR": "Usado pelo grande Fanático para executar hereges.",
    "ru": "Карающая длань ярого фанатика.",
    "tr": "İnanç Fedaileri tarafından sapkınları infaz etmek için kullanılıyordu.",
    "zh-CN": "极端狂热者过去处决异教徒所用。",
    "zh-TW": "極端狂熱者過去處決異教徒所用。"
  },
  "name": {
    "ar": "فأس الإقدام",
    "de": "Eiferaxt",
    "en": "Zealous Axe",
    "es": "Hacha ferviente",
    "fr": "Hache occulte",
    "fr-CA": "Hache fervente",
    "it": "Ascia fervente",
    "ja": "篤信なる斧",
    "ko": "열성의 도끼",
    "nl": "Onverstoorbare bijl",
    "pt-BR": "Machado Zeloso",
    "ru": "Неистовый топор",
    "tr": "Hırs Baltası",
    "zh-CN": "狂热之斧",
    "zh-TW": "狂熱之斧"
  },
  "namePlain": {
    "ar": "فأس الإقدام",
    "de": "Eiferaxt",
    "en": "Zealous Axe",
    "es": "Hacha ferviente",
    "fr": "Hache occulte",
    "fr-CA": "Hache fervente",
    "it": "Ascia fervente",
    "ja": "篤信なる斧",
    "ko": "열성의 도끼",
    "nl": "Onverstoorbare bijl",
    "pt-BR": "Machado Zeloso",
    "ru": "Неистовый топор",
    "tr": "Hırs Baltası",
    "zh-CN": "狂热之斧",
    "zh-TW": "狂熱之斧"
  },
  "speed": 0.5,
  "thumb": "icons/weapons/64/Axe_Fervour.png"
}
