=== AuthFailed/cotl-api/schema/item.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Item",
  "type": "object",
  "required": [
    "id",
    "name",
    "description",
    "icon",
    "category",
    "namePlain",
    "descriptionPlain"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]+$"
    },
    "name": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      },
      "required": [
        "en"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "icon": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/(items|structures|skins)/[A-Za-z0-9_-]+\\.png$"
    },
    "category": {
      "type": [
        "string",
        "null"
      ]
    },
    "namePlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "name without the game's text markup"
    },
    "descriptionPlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "description without the game's text markup"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "food, fish, big_fish, meat, heart, gift"
    }
  }
}

=== AuthFailed/cotl-api/site/v1/items/POOP_RAINBOW.json
{
  "category": "POOP",
  "description": {
    "ar": "المحاصيل التي تُزرع باستخدامه تنمو على الفور.",
    "de": "Damit gedüngte Feldfrüchte wachsen sofort.",
    "en": "Crops grown with this will grow instantly.",
    "es": "Los cultivos en los que se use esto crecerán de inmediato.",
    "fr": "Les plantations fertilisées avec ceci poussent instantanément.",
    "fr-CA": "Les plantations fertilisées avec ceci poussent instantanément.",
    "it": "Le colture cresceranno in un battibaleno.",
    "ja": "これを使って育てた作物は成長が早い",
    "ko": "이 거름을 먹고 자란 곡식은 즉시 성장합니다.",
    "nl": "Zaden gezaaid op deze mest groeien direct uit tot gewassen.",
    "pt-BR": "Plantações cultivadas com isto crescerão instantaneamente.",
    "ru": "Удобрение, заставляющее посевы взойти моментально.",
    "tr": "Bununla yetişen mahsuller anında büyür.",
    "zh-CN": "施肥后，作物立即生长完毕。",
    "zh-TW": "施肥後，作物立即生長完畢。"
  },
  "descriptionPlain": {
    "ar": "المحاصيل التي تُزرع باستخدامه تنمو على الفور.",
    "de": "Damit gedüngte Feldfrüchte wachsen sofort.",
    "en": "Crops grown with this will grow instantly.",
    "es": "Los cultivos en los que se use esto crecerán de inmediato.",
    "fr": "Les plantations fertilisées avec ceci poussent instantanément.",
    "fr-CA": "Les plantations fertilisées avec ceci poussent instantanément.",
    "it": "Le colture cresceranno in un battibaleno.",
    "ja": "これを使って育てた作物は成長が早い",
    "ko": "이 거름을 먹고 자란 곡식은 즉시 성장합니다.",
    "nl": "Zaden gezaaid op deze mest groeien direct uit tot gewassen.",
    "pt-BR": "Plantações cultivadas com isto crescerão instantaneamente.",
    "ru": "Удобрение, заставляющее посевы взойти моментально.",
    "tr": "Bununla yetişen mahsuller anında büyür.",
    "zh-CN": "施肥后，作物立即生长完毕。",
    "zh-TW": "施肥後，作物立即生長完畢。"
  },
  "icon": "icons/items/POOP_RAINBOW.png",
  "id": "POOP_RAINBOW",
  "name": {
    "ar": "سماد ملون",
    "de": "Regenbogen-Dünger",
    "en": "Rainbow Fertiliser",
    "es": "Fertilizante arcoíris",
    "fr": "Fertilisant arc-en-ciel",
    "fr-CA": "Fertilisant arc-en-ciel",
    "it": "Concime arcobaleno",
    "ja": "虹色の肥料",
    "ko": "무지개 퇴비",
    "nl": "Regenboogmest",
    "pt-BR": "Fertilizante de Arco-Íris",
    "ru": "Радужное удобрение",
    "tr": "Gökkuşağı Gübre",
    "zh-CN": "彩虹肥料",
    "zh-TW": "彩虹肥料"
  },
  "namePlain": {
    "ar": "سماد ملون",
    "de": "Regenbogen-Dünger",
    "en": "Rainbow Fertiliser",
    "es": "Fertilizante arcoíris",
    "fr": "Fertilisant arc-en-ciel",
    "fr-CA": "Fertilisant arc-en-ciel",
    "it": "Concime arcobaleno",
    "ja": "虹色の肥料",
    "ko": "무지개 퇴비",
    "nl": "Regenboogmest",
    "pt-BR": "Fertilizante de Arco-Íris",
    "ru": "Радужное удобрение",
    "tr": "Gökkuşağı Gübre",
    "zh-CN": "彩虹肥料",
    "zh-TW": "彩虹肥料"
  },
  "tags": []
}

=== AuthFailed/cotl-api/site/v1/items/REPAIRED_WEAPON_CHAIN.json
{
  "category": "NONE",
  "description": {
    "en": "This weapon will not reach its full potential until it is brought to <color=#FFD201>Kudaai</color>."
  },
  "descriptionPlain": {
    "en": "This weapon will not reach its full potential until it is brought to Kudaai."
  },
  "icon": "icons/items/REPAIRED_WEAPON_CHAIN.png",
  "id": "REPAIRED_WEAPON_CHAIN",
  "name": {
    "en": "Yngya's Torment"
  },
  "namePlain": {
    "en": "Yngya's Torment"
  },
  "tags": []
}

=== AuthFailed/cotl-api/site/v1/items/STONE.json
{
  "category": "NONE",
  "description": {
    "ar": "مادة بناء مفيدة.",
    "de": "Ein nützliches Baumaterial.",
    "en": "A useful building material.",
    "es": "Un material muy útil para construir.",
    "fr": "Un matériau de construction très utile.",
    "fr-CA": "Un matériau de construction très utile.",
    "it": "Un utile materiale da costruzione.",
    "ja": "便利な建築素材",
    "ko": "유용한 건축용 자재입니다.",
    "nl": "Een handig bouwmateriaal.",
    "pt-BR": "Um material de construção útil.",
    "ru": "Строительный материал.",
    "tr": "Kullanışlı bir inşa malzemesi.",
    "zh-CN": "有用的建材。",
    "zh-TW": "有用的建材。"
  },
  "descriptionPlain": {
    "ar": "مادة بناء مفيدة.",
    "de": "Ein nützliches Baumaterial.",
    "en": "A useful building material.",
    "es": "Un material muy útil para construir.",
    "fr": "Un matériau de construction très utile.",
    "fr-CA": "Un matériau de construction très utile.",
    "it": "Un utile materiale da costruzione.",
    "ja": "便利な建築素材",
    "ko": "유용한 건축용 자재입니다.",
    "nl": "Een handig bouwmateriaal.",
    "pt-BR": "Um material de construção útil.",
    "ru": "Строительный материал.",
    "tr": "Kullanışlı bir inşa malzemesi.",
    "zh-CN": "有用的建材。",
    "zh-TW": "有用的建材。"
  },
  "icon": "icons/items/STONE.png",
  "id": "STONE",
  "name": {
    "ar": "حجر",
    "de": "Stein",
    "en": "Stone",
    "es": "Piedra",
    "fr": "Pierre",
    "fr-CA": "Pierre",
    "it": "Pietra",
    "ja": "石",
    "ko": "돌",
    "nl": "Steen",
    "pt-BR": "Pedra",
    "ru": "Камень",
    "tr": "Taş",
    "zh-CN": "石材",
    "zh-TW": "石材"
  },
  "namePlain": {
    "ar": "حجر",
    "de": "Stein",
    "en": "Stone",
    "es": "Piedra",
    "fr": "Pierre",
    "fr-CA": "Pierre",
    "it": "Pietra",
    "ja": "石",
    "ko": "돌",
    "nl": "Steen",
    "pt-BR": "Pedra",
    "ru": "Камень",
    "tr": "Taş",
    "zh-CN": "石材",
    "zh-TW": "石材"
  },
  "tags": []
}

=== AuthFailed/cotl-api/site/v1/items/GIFT_SMALL.json
{
  "category": "NONE",
  "description": {
    "ar": "هدية صغيرة لزيادة إخلاص تابع.",
    "de": "Ein kleines Geschenk, um die Loyalität deiner Anhänger zu steigern.",
    "en": "A small gift to raise the Loyalty of a Follower.",
    "es": "Un regalito para aumentar la lealtad de un adepto.",
    "fr": "Un petit cadeau permettant d'augmenter la fidélité d'un adepte.",
    "fr-CA": "Un petit cadeau permettant d'accroître la fidélité d'un adepte.",
    "it": "Un piccolo dono per aumentare la Fedeltà di un membro del Culto.",
    "ja": "信者の忠誠心を高めてくれる小さな贈り物",
    "ko": "추종자의 충성심을 상승시키는 작은 선물입니다.",
    "nl": "Een klein geschenk om de loyaliteit van een volgeling te verhogen.",
    "pt-BR": "Um pequeno presente para aumentar a Lealdade de um Seguidor.",
    "ru": "Скромный дар, помогающий укрепить доверие последователя.",
    "tr": "Bir Takipçi'nin Bağlılık'ını artırmaya yarayan küçük bir hediye.",
    "zh-CN": "增加教徒忠诚度的小型礼物。",
    "zh-TW": "增加教徒忠誠度的小型禮物。"
  },
  "descriptionPlain": {
    "ar": "هدية صغيرة لزيادة إخلاص تابع.",
    "de": "Ein kleines Geschenk, um die Loyalität deiner Anhänger zu steigern.",
    "en": "A small gift to raise the Loyalty of a Follower.",
    "es": "Un regalito para aumentar la lealtad de un adepto.",
    "fr": "Un petit cadeau permettant d'augmenter la fidélité d'un adepte.",
    "fr-CA": "Un petit cadeau permettant d'accroître la fidélité d'un adepte.",
    "it": "Un piccolo dono per aumentare la Fedeltà di un membro del Culto.",
    "ja": "信者の忠誠心を高めてくれる小さな贈り物",
    "ko": "추종자의 충성심을 상승시키는 작은 선물입니다.",
    "nl": "Een klein geschenk om de loyaliteit van een volgeling te verhogen.",
    "pt-BR": "Um pequeno presente para aumentar a Lealdade de um Seguidor.",
    "ru": "Скромный дар, помогающий укрепить доверие последователя.",
    "tr": "Bir Takipçi'nin Bağlılık'ını artırmaya yarayan küçük bir hediye.",
    "zh-CN": "增加教徒忠诚度的小型礼物。",
    "zh-TW": "增加教徒忠誠度的小型禮物。"
  },
  "icon": "icons/items/GIFT_SMALL.png",
  "id": "GIFT_SMALL",
  "name": {
    "ar": "هدية صغيرة",
    "de": "Kleines Geschenk",
    "en": "Small Gift",
    "es": "Regalo pequeño",
    "fr": "Petit cadeau",
    "fr-CA": "Petit cadeau",
    "it": "Dono piccolo",
    "ja": "贈り物（小）",
    "ko": "소형 선물",
    "nl": "Klein geschenk",
    "pt-BR": "Presente Pequeno",
    "ru": "Маленький подарок",
    "tr": "Küçük Hediye",
    "zh-CN": "小型礼物",
    "zh-TW": "小型禮物"
  },
  "namePlain": {
    "ar": "هدية صغيرة",
    "de": "Kleines Geschenk",
    "en": "Small Gift",
    "es": "Regalo pequeño",
    "fr": "Petit cadeau",
    "fr-CA": "Petit cadeau",
    "it": "Dono piccolo",
    "ja": "贈り物（小）",
    "ko": "소형 선물",
    "nl": "Klein geschenk",
    "pt-BR": "Presente Pequeno",
    "ru": "Маленький подарок",
    "tr": "Küçük Hediye",
    "zh-CN": "小型礼物",
    "zh-TW": "小型禮物"
  },
  "tags": [
    "gift"
  ]
}
