=== AuthFailed/cotl-api/schema/relic.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Relic",
  "type": "object",
  "required": [
    "id",
    "name",
    "description",
    "namePlain",
    "descriptionPlain",
    "icon",
    "thumb",
    "lore",
    "subType",
    "interactionType",
    "damageType",
    "chargeDamage",
    "chargeCategory",
    "weight",
    "requiresCult",
    "unlockedBy",
    "dlc",
    "coop",
    "majorDlc"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]+$"
    },
    "name": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      },
      "required": [
        "en"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "namePlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "name without the game's text markup"
    },
    "descriptionPlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "description without the game's text markup"
    },
    "icon": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/relics/[A-Za-z0-9_-]+\\.png$"
    },
    "thumb": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/relics/64/[A-Za-z0-9_-]+\\.png$"
    },
    "lore": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "subType": {
      "type": [
        "string",
        "null"
      ],
      "description": "None, Blessed, Damned, Corrupted, Coop ..."
    },
    "interactionType": {
      "type": [
        "string",
        "null"
      ],
      "description": "Instant, Fragile (single use) ..."
    },
    "damageType": {
      "type": [
        "string",
        "null"
      ],
      "description": "damage that charges it"
    },
    "chargeDamage": {
      "type": "number",
      "description": "damage needed to charge it"
    },
    "chargeCategory": {
      "type": [
        "string",
        "null"
      ],
      "description": "Fast, Average or Slow, as the game labels it"
    },
    "weight": {
      "type": "number",
      "description": "draw weight"
    },
    "requiresCult": {
      "type": "boolean",
      "description": "only appears once you have a cult"
    },
    "unlockedBy": {
      "type": [
        "string",
        "null"
      ],
      "description": "UpgradeSystem upgrade that unlocks it"
    },
    "dlc": {
      "type": "boolean",
      "description": ""
    },
    "coop": {
      "type": "boolean",
      "description": ""
    },
    "majorDlc": {
      "type": "boolean",
      "description": ""
    }
  }
}

=== AuthFailed/cotl-api/site/v1/relics/GungeonBlank.json
{
  "chargeCategory": "Slow",
  "chargeDamage": 110.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "يمكن اكتساب 8 ثوانٍ من الحصانة.",
    "de": "Erhalte 8 Sekunden der Unverwundbarkeit.",
    "en": "Gain 8 seconds of invincibility.",
    "es": "Gana 8 segundos de invencibilidad.",
    "fr": "Obtenez 8 secondes d'invincibilité.",
    "fr-CA": "Obtenez 8 secondes d'invincibilité.",
    "it": "Conferisce 8 secondi di invincibilità.",
    "ja": "8秒間無敵状態になる",
    "ko": "8초 동안 무적이 됩니다.",
    "nl": "Word 8 seconden onoverwinnelijk.",
    "pt-BR": "Ganhe 8 segundos de invencibilidade.",
    "ru": "Вы становитесь неуязвимы на 8 сек.",
    "tr": "8 saniyeliğine hasar görmez olursun.",
    "zh-CN": "获得 8 秒无敌状态。",
    "zh-TW": "獲得 8 秒無敵狀態。"
  },
  "descriptionPlain": {
    "ar": "يمكن اكتساب 8 ثوانٍ من الحصانة.",
    "de": "Erhalte 8 Sekunden der Unverwundbarkeit.",
    "en": "Gain 8 seconds of invincibility.",
    "es": "Gana 8 segundos de invencibilidad.",
    "fr": "Obtenez 8 secondes d'invincibilité.",
    "fr-CA": "Obtenez 8 secondes d'invincibilité.",
    "it": "Conferisce 8 secondi di invincibilità.",
    "ja": "8秒間無敵状態になる",
    "ko": "8초 동안 무적이 됩니다.",
    "nl": "Word 8 seconden onoverwinnelijk.",
    "pt-BR": "Ganhe 8 segundos de invencibilidade.",
    "ru": "Вы становитесь неуязвимы на 8 сек.",
    "tr": "8 saniyeliğine hasar görmez olursun.",
    "zh-CN": "获得 8 秒无敌状态。",
    "zh-TW": "獲得 8 秒無敵狀態。"
  },
  "dlc": false,
  "icon": "icons/relics/GungeonBlank.png",
  "id": "GungeonBlank",
  "interactionType": "Charging",
  "lore": {
    "ar": "لا أدبّر شرًا.",
    "de": "Nichts Böses denken.",
    "en": "Think no evil.",
    "es": "No pensar el Mal.",
    "fr": "Ne pas penser le mal.",
    "fr-CA": "Ne pas penser le mal.",
    "it": "Ho smesso di pensare.",
    "ja": "悪を考えず",
    "ko": "악을 생각하지 말지어다.",
    "nl": "Denk geen kwaad.",
    "pt-BR": "Não pense em mal algum.",
    "ru": "Не думать о зле.",
    "tr": "Akılsız kötülük.",
    "zh-CN": "毋思恶。",
    "zh-TW": "毋思惡。"
  },
  "majorDlc": false,
  "name": {
    "ar": "جمجمة شامورا",
    "de": "Shamuras Schädel",
    "en": "Shamura's Skull",
    "es": "Calavera de Shamura",
    "fr": "Crâne de Shamura",
    "fr-CA": "Crâne de Shamura",
    "it": "Teschio di Shamura",
    "ja": "シャムラの頭蓋骨",
    "ko": "샤무라의 해골",
    "nl": "Schedel van Shamura",
    "pt-BR": "Crânio de Shamura",
    "ru": "Череп Шамуры",
    "tr": "Shamura'nın Kafatası",
    "zh-CN": "沙穆拉之颅",
    "zh-TW": "夏慕拉之顱"
  },
  "namePlain": {
    "ar": "جمجمة شامورا",
    "de": "Shamuras Schädel",
    "en": "Shamura's Skull",
    "es": "Calavera de Shamura",
    "fr": "Crâne de Shamura",
    "fr-CA": "Crâne de Shamura",
    "it": "Teschio di Shamura",
    "ja": "シャムラの頭蓋骨",
    "ko": "샤무라의 해골",
    "nl": "Schedel van Shamura",
    "pt-BR": "Crânio de Shamura",
    "ru": "Череп Шамуры",
    "tr": "Shamura'nın Kafatası",
    "zh-CN": "沙穆拉之颅",
    "zh-TW": "夏慕拉之顱"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/GungeonBlank.png",
  "unlockedBy": "Building_LightningRod",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/SpawnCombatFollower.json
{
  "chargeCategory": "Slow",
  "chargeDamage": 100.0,
  "coop": false,
  "damageType": "DealsDamage",
  "description": {
    "ar": "يمكن استدعاء تابع حي لمساعدتك حتى موته في حملتك.",
    "de": "Beschwöre einen untoten Anhänger, um dir auf deinem Kreuzzug zu helfen.",
    "en": "Summon an undead Follower to help you in your Crusade.",
    "es": "Invoca a un adepto no muerto para que te ayude en tu cruzada.",
    "fr": "Invoquez un adepte mort-vivant pour vous accompagner dans les donjons.",
    "fr-CA": "Invoquez un adepte mort-vivant pour vous accompagner lors de vos croisades.",
    "it": "Evoca un membro del Culto non morto per assisterti nella crociata.",
    "ja": "聖戦を手助けしてくれる信者の死霊を召喚する",
    "ko": "언데드 추종자 하나를 소환해 성전에서 돕게 합니다.",
    "nl": "Roep een ondode volgeling op om je te helpen in je kruistocht.",
    "pt-BR": "Invoque um Seguidor morto-vivo para lhe ajudar na sua Cruzada.",
    "ru": "Вы призываете умершего последователя, который будет помогать вам в походе.",
    "tr": "Sefer'inde sana yardımcı olması için bir hortlak Takipçi çağırır.",
    "zh-CN": "召唤一位不死的教徒，在圣战中帮助你。",
    "zh-TW": "召喚一位不死的教徒，在聖戰中幫助你。"
  },
  "descriptionPlain": {
    "ar": "يمكن استدعاء تابع حي لمساعدتك حتى موته في حملتك.",
    "de": "Beschwöre einen untoten Anhänger, um dir auf deinem Kreuzzug zu helfen.",
    "en": "Summon an undead Follower to help you in your Crusade.",
    "es": "Invoca a un adepto no muerto para que te ayude en tu cruzada.",
    "fr": "Invoquez un adepte mort-vivant pour vous accompagner dans les donjons.",
    "fr-CA": "Invoquez un adepte mort-vivant pour vous accompagner lors de vos croisades.",
    "it": "Evoca un membro del Culto non morto per assisterti nella crociata.",
    "ja": "聖戦を手助けしてくれる信者の死霊を召喚する",
    "ko": "언데드 추종자 하나를 소환해 성전에서 돕게 합니다.",
    "nl": "Roep een ondode volgeling op om je te helpen in je kruistocht.",
    "pt-BR": "Invoque um Seguidor morto-vivo para lhe ajudar na sua Cruzada.",
    "ru": "Вы призываете умершего последователя, который будет помогать вам в походе.",
    "tr": "Sefer'inde sana yardımcı olması için bir hortlak Takipçi çağırır.",
    "zh-CN": "召唤一位不死的教徒，在圣战中帮助你。",
    "zh-TW": "召喚一位不死的教徒，在聖戰中幫助你。"
  },
  "dlc": false,
  "icon": "icons/relics/SpawnCombatFollower.png",
  "id": "SpawnCombatFollower",
  "interactionType": "Charging",
  "lore": {
    "ar": "لا أسمع شرًا.",
    "de": "Nichts Böses hören.",
    "en": "Hear no evil.",
    "es": "No escuchar el Mal.",
    "fr": "Ne pas entendre le mal.",
    "fr-CA": "Ne pas entendre le mal.",
    "it": "\"Non sento\".",
    "ja": "悪を聞かず",
    "ko": "악을 듣지 말지어다.",
    "nl": "Hoor geen kwaad.",
    "pt-BR": "Não ouça mal algum.",
    "ru": "Не слышать зла.",
    "tr": "Sağır kötülük.",
    "zh-CN": "毋闻恶。",
    "zh-TW": "毋聞惡。"
  },
  "majorDlc": false,
  "name": {
    "ar": "أذن كالامار",
    "de": "Kallamars Ohr",
    "en": "Kallamar's Ear",
    "es": "Oreja de Kallamar",
    "fr": "Oreille de Kallamar",
    "fr-CA": "Oreille de Kallamar",
    "it": "Orecchio di Kallamar",
    "ja": "カラマールの耳",
    "ko": "칼라마르의 귀",
    "nl": "Kallamars oor",
    "pt-BR": "Orelha de Kallamar",
    "ru": "Ухо Калламара",
    "tr": "Kallamar'ın Kulağı",
    "zh-CN": "凯拉鰢之耳",
    "zh-TW": "凱拉鰢之耳"
  },
  "namePlain": {
    "ar": "أذن كالامار",
    "de": "Kallamars Ohr",
    "en": "Kallamar's Ear",
    "es": "Oreja de Kallamar",
    "fr": "Oreille de Kallamar",
    "fr-CA": "Oreille de Kallamar",
    "it": "Orecchio di Kallamar",
    "ja": "カラマールの耳",
    "ko": "칼라마르의 귀",
    "nl": "Kallamars oor",
    "pt-BR": "Orelha de Kallamar",
    "ru": "Ухо Калламара",
    "tr": "Kallamar'ın Kulağı",
    "zh-CN": "凯拉鰢之耳",
    "zh-TW": "凱拉鰢之耳"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/SpawnCombatFollower.png",
  "unlockedBy": "Building_LightningRod",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/IncreaseDamageForDuration.json
{
  "chargeCategory": "Average",
  "chargeDamage": 70.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "يزيد ضرر الهجوم لمدة 10 ثوانٍ.",
    "de": "Erhöhe 10 Sekunden lang den Angriffsschaden.",
    "en": "Increases attack damage for 10 seconds.",
    "es": "Aumenta el daño de tus ataques durante 10 segundos.",
    "fr": "Augmentez vos dégâts infligés pendant 10 secondes.",
    "fr-CA": "Augmentez vos dégâts infligés pendant 10 secondes.",
    "it": "Aumenta i danni che infliggi per 10 secondi.",
    "ja": "10秒間、攻撃で与えるダメージが上昇する",
    "ko": "10초 간 공격력을 증가시킵니다.",
    "nl": "Verhoogt 10 seconden lang aanvalsschade.",
    "pt-BR": "Aumenta o dano do ataque por 10 segundos.",
    "ru": "Вы наносите больше урона в течение 10 сек.",
    "tr": "Saldırı hasarını 10 saniyeliğine artırır.",
    "zh-CN": "增加攻击伤害值 10 秒。",
    "zh-TW": "增加攻擊傷害值 10 秒。"
  },
  "descriptionPlain": {
    "ar": "يزيد ضرر الهجوم لمدة 10 ثوانٍ.",
    "de": "Erhöhe 10 Sekunden lang den Angriffsschaden.",
    "en": "Increases attack damage for 10 seconds.",
    "es": "Aumenta el daño de tus ataques durante 10 segundos.",
    "fr": "Augmentez vos dégâts infligés pendant 10 secondes.",
    "fr-CA": "Augmentez vos dégâts infligés pendant 10 secondes.",
    "it": "Aumenta i danni che infliggi per 10 secondi.",
    "ja": "10秒間、攻撃で与えるダメージが上昇する",
    "ko": "10초 간 공격력을 증가시킵니다.",
    "nl": "Verhoogt 10 seconden lang aanvalsschade.",
    "pt-BR": "Aumenta o dano do ataque por 10 segundos.",
    "ru": "Вы наносите больше урона в течение 10 сек.",
    "tr": "Saldırı hasarını 10 saniyeliğine artırır.",
    "zh-CN": "增加攻击伤害值 10 秒。",
    "zh-TW": "增加攻擊傷害值 10 秒。"
  },
  "dlc": false,
  "icon": "icons/relics/IncreaseDamageForDuration.png",
  "id": "IncreaseDamageForDuration",
  "interactionType": "Charging",
  "lore": {
    "ar": "لا أنطق شرًا.",
    "de": "Nichts Böses sagen.",
    "en": "Speak no evil.",
    "es": "No decir el Mal.",
    "fr": "Ne pas dire le mal.",
    "fr-CA": "Ne pas dire le mal.",
    "it": "\"Non parlo\".",
    "ja": "悪を語らず",
    "ko": "악을 말하지 말지어다.",
    "nl": "Spreek geen kwaad.",
    "pt-BR": "Não fale mal algum.",
    "ru": "Не говорить о зле.",
    "tr": "Dilsiz kötülük.",
    "zh-CN": "毋言恶。",
    "zh-TW": "毋言惡。"
  },
  "majorDlc": false,
  "name": {
    "ar": "حلق هيكت",
    "de": "Hekets Kehle",
    "en": "Heket's Throat",
    "es": "Garganta de Heket",
    "fr": "Gorge de Heket",
    "fr-CA": "Gorge de Heket",
    "it": "Gola di Heket",
    "ja": "ヘケトの喉",
    "ko": "헤켓의 목젖",
    "nl": "Hekets keel",
    "pt-BR": "Garganta de Heket",
    "ru": "Связки Хекат",
    "tr": "Heket'in Boğazı",
    "zh-CN": "赫凯特之喉",
    "zh-TW": "赫凱特之喉"
  },
  "namePlain": {
    "ar": "حلق هيكت",
    "de": "Hekets Kehle",
    "en": "Heket's Throat",
    "es": "Garganta de Heket",
    "fr": "Gorge de Heket",
    "fr-CA": "Gorge de Heket",
    "it": "Gola di Heket",
    "ja": "ヘケトの喉",
    "ko": "헤켓의 목젖",
    "nl": "Hekets keel",
    "pt-BR": "Garganta de Heket",
    "ru": "Связки Хекат",
    "tr": "Heket'in Boğazı",
    "zh-CN": "赫凯特之喉",
    "zh-TW": "赫凱特之喉"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/IncreaseDamageForDuration.png",
  "unlockedBy": "Building_LightningRod",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/HealPerFollower_Dammed.json
{
  "chargeCategory": "Fast",
  "chargeDamage": 30.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "يمكن اكتساب نصف قلب روح مقابل كل تابع معارض.",
    "de": "Erhalte ein halbes Geisterherz pro abtrünnigem Anhänger.",
    "en": "Gain half a Spirit Heart per Dissenting Follower.",
    "es": "Gana medio corazón fantasma por cada adepto desertor.",
    "fr": "Obtenez une moitié de cœur spirituel par adepte rebelle.",
    "fr-CA": "Obtenez une moitié de cœur spirituel par adepte rebelle.",
    "it": "Conferisce mezzo cuore spirituale per ogni membro dissidente del Culto.",
    "ja": "離反中の信者1人につき、半分のスピリットハートを獲得する",
    "ko": "반목하는 추종자 하나당 영혼 심장 하나를 얻습니다.",
    "nl": "Krijg een half spiritueel hart per afvallige volgeling.",
    "pt-BR": "Ganhe meio Coração Espiritual por Seguidor Rebelde.",
    "ru": "Вы получаете по половине эфемерного сердца за каждого инакомыслящего последователя.",
    "tr": "Tarikat'ındaki Başkaldıran Takipçi başına bir yarım Ruh Kalbi kazanırsın.",
    "zh-CN": "教中每有一位反教者，就获得半颗灵心。",
    "zh-TW": "教中每有一位反教者，就獲得半顆靈心。"
  },
  "descriptionPlain": {
    "ar": "يمكن اكتساب نصف قلب روح مقابل كل تابع معارض.",
    "de": "Erhalte ein halbes Geisterherz pro abtrünnigem Anhänger.",
    "en": "Gain half a Spirit Heart per Dissenting Follower.",
    "es": "Gana medio corazón fantasma por cada adepto desertor.",
    "fr": "Obtenez une moitié de cœur spirituel par adepte rebelle.",
    "fr-CA": "Obtenez une moitié de cœur spirituel par adepte rebelle.",
    "it": "Conferisce mezzo cuore spirituale per ogni membro dissidente del Culto.",
    "ja": "離反中の信者1人につき、半分のスピリットハートを獲得する",
    "ko": "반목하는 추종자 하나당 영혼 심장 하나를 얻습니다.",
    "nl": "Krijg een half spiritueel hart per afvallige volgeling.",
    "pt-BR": "Ganhe meio Coração Espiritual por Seguidor Rebelde.",
    "ru": "Вы получаете по половине эфемерного сердца за каждого инакомыслящего последователя.",
    "tr": "Tarikat'ındaki Başkaldıran Takipçi başına bir yarım Ruh Kalbi kazanırsın.",
    "zh-CN": "教中每有一位反教者，就获得半颗灵心。",
    "zh-TW": "教中每有一位反教者，就獲得半顆靈心。"
  },
  "dlc": false,
  "icon": "icons/relics/HealPerFollower_Dammed.png",
  "id": "HealPerFollower_Dammed",
  "interactionType": "Fragile",
  "lore": {
    "ar": "حتى الشك قد يكون له فائدة.",
    "de": "Selbst der Zweifel kann nützlich sein.",
    "en": "Even doubt may have its use.",
    "es": "Incluso la duda alberga sus usos.",
    "fr": "Même le doute peut avoir ses avantages.",
    "fr-CA": "Même le doute peut avoir ses avantages.",
    "it": "Persino il dubbio può avere una sua utilità.",
    "ja": "疑念の心にも、使い道があるのだ",
    "ko": "의심 또한 쓰일 곳이 있나니.",
    "nl": "Zelfs twijfel kan nut hebben.",
    "pt-BR": "Até a dúvida pode ser útil.",
    "ru": "Даже в сомнении есть польза.",
    "tr": "Bazen kuşkunun bile faydası vardır.",
    "zh-CN": "就连质疑也可能有其用处。",
    "zh-TW": "就連質疑也可能有其用處。"
  },
  "majorDlc": false,
  "name": {
    "ar": "بلسم المعتزِل <color=#FD1D03>الملعون</color>",
    "de": "<color=#FD1D03>Verdammter</color> Balsam des Einsiedlers",
    "en": "<color=#FD1D03>Damned</color> Balm of the Anchorite",
    "es": "Bálsamo <color=#FD1D03>maldito</color> del ermitaño",
    "fr": "Baume de l'anachorète <color=#FD1D03>maudit</color>",
    "fr-CA": "Baume <color=#FD1D03>maudit</color> de l'anachorète",
    "it": "Balsamo dell'anacoreta <color=#FD1D03>dannato</color>",
    "ja": "<color=#FD1D03>呪われた</color>隠者の香油",
    "ko": "<color=#FD1D03>저주받은</color> 은자의 연고",
    "nl": "<color=#FD1D03>Verdoemde</color> balsem van de Anchoriet",
    "pt-BR": "Bálsamo do Anacoreta <color=#FD1D03>Maldito</color>",
    "ru": "<color=#FD1D03>Проклятый</color> бальзам аскета",
    "tr": "<color=#FD1D03>Lanetli</color> Münzevinin Merhemi",
    "zh-CN": "<color=#FD1D03>受诅咒的</color>隐修者香膏",
    "zh-TW": "<color=#FD1D03>受詛咒的</color>隱修者香膏"
  },
  "namePlain": {
    "ar": "بلسم المعتزِل الملعون",
    "de": "Verdammter Balsam des Einsiedlers",
    "en": "Damned Balm of the Anchorite",
    "es": "Bálsamo maldito del ermitaño",
    "fr": "Baume de l'anachorète maudit",
    "fr-CA": "Baume maudit de l'anachorète",
    "it": "Balsamo dell'anacoreta dannato",
    "ja": "呪われた隠者の香油",
    "ko": "저주받은 은자의 연고",
    "nl": "Verdoemde balsem van de Anchoriet",
    "pt-BR": "Bálsamo do Anacoreta Maldito",
    "ru": "Проклятый бальзам аскета",
    "tr": "Lanetli Münzevinin Merhemi",
    "zh-CN": "受诅咒的隐修者香膏",
    "zh-TW": "受詛咒的隱修者香膏"
  },
  "requiresCult": true,
  "subType": "Any",
  "thumb": "icons/relics/64/HealPerFollower_Dammed.png",
  "unlockedBy": "Relics_Dammed_1",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/IgniteAll.json
{
  "chargeCategory": "Average",
  "chargeDamage": 60.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "يمكن <color=#f79502>حرق</color> جميع الأعداء النشطين.",
    "de": "<color=#f79502>Verbrenne</color> alle aktiven Gegner.",
    "en": "<color=#f79502>Burn</color> all active enemies.",
    "es": "<color=#f79502>Quema</color> a todos los enemigos activos.",
    "fr": "<color=#f79502>Brûle</color> tous les ennemis présents.",
    "fr-CA": "<color=#f79502>Brûle</color> tous les ennemis présents.",
    "it": "<color=#f79502>Incendia</color> tutti i nemici a schermo.",
    "ja": "画面内の敵すべてを<color=#f79502>炎上</color>状態にする",
    "ko": "모든 활동 중의 적들을 <color=#f79502>불태웁니다.</color>",
    "nl": "<color=#f79502>Verbrand</color> alle actieve vijanden.",
    "pt-BR": "<color=#f79502>Queima</color> todos os inimigos ativos.",
    "ru": "Вы <color=#f79502>поджигаете</color> всех врагов.",
    "tr": "Tüm etkin düşmanları <color=#f79502>yakar</color>.",
    "zh-CN": "使所有行动中的敌人<color=#f79502>燃烧</color>。",
    "zh-TW": "使所有行動中的敵人<color=#f79502>燃燒</color>。"
  },
  "descriptionPlain": {
    "ar": "يمكن حرق جميع الأعداء النشطين.",
    "de": "Verbrenne alle aktiven Gegner.",
    "en": "Burn all active enemies.",
    "es": "Quema a todos los enemigos activos.",
    "fr": "Brûle tous les ennemis présents.",
    "fr-CA": "Brûle tous les ennemis présents.",
    "it": "Incendia tutti i nemici a schermo.",
    "ja": "画面内の敵すべてを炎上状態にする",
    "ko": "모든 활동 중의 적들을 불태웁니다.",
    "nl": "Verbrand alle actieve vijanden.",
    "pt-BR": "Queima todos os inimigos ativos.",
    "ru": "Вы поджигаете всех врагов.",
    "tr": "Tüm etkin düşmanları yakar.",
    "zh-CN": "使所有行动中的敌人燃烧。",
    "zh-TW": "使所有行動中的敵人燃燒。"
  },
  "dlc": true,
  "icon": "icons/relics/IgniteAll.png",
  "id": "IgniteAll",
  "interactionType": "Charging",
  "lore": {
    "ar": "السم الذي يحرق من الأعماق إلى السطح.",
    "de": "Gift, das von innen heraus brennt.",
    "en": "Venom that burns from the inside out.",
    "es": "Un veneno que abrasa desde las entrañas.",
    "fr": "Un venin qui brûle de l'intérieur.",
    "fr-CA": "Un venin qui brûle de l'intérieur.",
    "it": "Un fuoco che divampa dall'interno.",
    "ja": "その毒はことごとくを焼き尽くす",
    "ko": "내면에서부터 태워버리는 맹독.",
    "nl": "Vergif dat van binnen naar buiten brandt.",
    "pt-BR": "Um veneno que queima por dentro.",
    "ru": "Горючий яд, изливающийся наружу.",
    "tr": "İçten yakan bir zehir.",
    "zh-CN": "由内而外燃烧的剧毒。",
    "zh-TW": "由內而外燃燒的劇毒。"
  },
  "majorDlc": true,
  "name": {
    "ar": "شوكة أصحاب الجمرات",
    "de": "Stachel des Aschenvolks",
    "en": "Spine of the Cinderfolk",
    "es": "Púa de los cinéreos",
    "fr": "Épine de Cendréen",
    "fr-CA": "Épine de Cendréen",
    "it": "Aculeo del Cineride",
    "ja": "灰者の棘",
    "ko": "잔불사람의 척추",
    "nl": "Stekel van het Sintelvolk",
    "pt-BR": "Espinhos em Brasa",
    "ru": "Хребет уголита",
    "tr": "Külzade Omurgası",
    "zh-CN": "灰烬者之脊",
    "zh-TW": "灰燼者之脊"
  },
  "namePlain": {
    "ar": "شوكة أصحاب الجمرات",
    "de": "Stachel des Aschenvolks",
    "en": "Spine of the Cinderfolk",
    "es": "Púa de los cinéreos",
    "fr": "Épine de Cendréen",
    "fr-CA": "Épine de Cendréen",
    "it": "Aculeo del Cineride",
    "ja": "灰者の棘",
    "ko": "잔불사람의 척추",
    "nl": "Stekel van het Sintelvolk",
    "pt-BR": "Espinhos em Brasa",
    "ru": "Хребет уголита",
    "tr": "Külzade Omurgası",
    "zh-CN": "灰烬者之脊",
    "zh-TW": "灰燼者之脊"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/IgniteAll.png",
  "unlockedBy": "Relics_Fire",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/RerollWeapon.json
{
  "chargeCategory": "Average",
  "chargeDamage": 70.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "يمكن استدعاء سلاح جديد بمستوى زائد.",
    "de": "Beschwöre eine neue Waffe mit erhöhter Stufe.",
    "en": "Summon a new Weapon with an increased level.",
    "es": "Invoca un arma nueva de más nivel.",
    "fr": "Invoquez une nouvelle arme d'un niveau supérieur.",
    "fr-CA": "Invoquez une nouvelle arme d'un niveau supérieur.",
    "it": "Evoca una nuova arma di livello superiore.",
    "ja": "レベルがより高い武器を召喚する",
    "ko": "레벨이 상승한 새로운 무기 하나를 소환합니다.",
    "nl": "Roep een nieuw wapen op van een hoger level.",
    "pt-BR": "Invoque uma nova Arma com o nível aumentado.",
    "ru": "Вы призываете новое оружие повышенного уровня.",
    "tr": "Bir üst seviyeli yeni bir Silah çağırır.",
    "zh-CN": "召唤一把等级提升过的新武器。",
    "zh-TW": "召喚一把等級提升過的新武器。"
  },
  "descriptionPlain": {
    "ar": "يمكن استدعاء سلاح جديد بمستوى زائد.",
    "de": "Beschwöre eine neue Waffe mit erhöhter Stufe.",
    "en": "Summon a new Weapon with an increased level.",
    "es": "Invoca un arma nueva de más nivel.",
    "fr": "Invoquez une nouvelle arme d'un niveau supérieur.",
    "fr-CA": "Invoquez une nouvelle arme d'un niveau supérieur.",
    "it": "Evoca una nuova arma di livello superiore.",
    "ja": "レベルがより高い武器を召喚する",
    "ko": "레벨이 상승한 새로운 무기 하나를 소환합니다.",
    "nl": "Roep een nieuw wapen op van een hoger level.",
    "pt-BR": "Invoque uma nova Arma com o nível aumentado.",
    "ru": "Вы призываете новое оружие повышенного уровня.",
    "tr": "Bir üst seviyeli yeni bir Silah çağırır.",
    "zh-CN": "召唤一把等级提升过的新武器。",
    "zh-TW": "召喚一把等級提升過的新武器。"
  },
  "dlc": false,
  "icon": "icons/relics/RerollWeapon.png",
  "id": "RerollWeapon",
  "interactionType": "Charging",
  "lore": {
    "ar": "مخلب قاتل وحاد كالسكاكين.",
    "de": "Bösartige Klaue, sündhaft scharf.",
    "en": "Vicious claw, wickedly sharp.",
    "es": "Garra salvaje, asaz afilada.",
    "fr": "Une griffe vicieusement aiguisée.",
    "fr-CA": "Une griffe vicieusement aiguisée.",
    "it": "Un artiglio feroce, perfidamente affilato.",
    "ja": "悪意に満ちたその爪は、邪悪なほどに鋭い",
    "ko": "잔혹한 발톱, 사악할만치 날카롭다.",
    "nl": "Venijnige klauw, verraderlijk scherp.",
    "pt-BR": "Uma garra feroz, terrivelmente afiada.",
    "ru": "Бритвенно-острый коготь отмщения.",
    "tr": "Hainlikle bilenmiş, vahşi bir pençe.",
    "zh-CN": "凶残之爪，异常锐利。",
    "zh-TW": "凶殘之爪，異常銳利。"
  },
  "majorDlc": false,
  "name": {
    "ar": "ظفر إصبع كوداي",
    "de": "Kudaais Fingernagel",
    "en": "Kudaai's Fingernail",
    "es": "Uña de la mano de Kudaai",
    "fr": "Ongle de Kudaai",
    "fr-CA": "Ongle de Kudaai",
    "it": "Unghia di Kudaai",
    "ja": "クダーイの手爪",
    "ko": "쿠다이의 손톱",
    "nl": "Kudaais vingernagel",
    "pt-BR": "Unha de Kudaai",
    "ru": "Ноготь с руки Кыдая",
    "tr": "Kudaai'nin Tırnağı",
    "zh-CN": "库鐽伊之指甲",
    "zh-TW": "庫鐽伊之指甲"
  },
  "namePlain": {
    "ar": "ظفر إصبع كوداي",
    "de": "Kudaais Fingernagel",
    "en": "Kudaai's Fingernail",
    "es": "Uña de la mano de Kudaai",
    "fr": "Ongle de Kudaai",
    "fr-CA": "Ongle de Kudaai",
    "it": "Unghia di Kudaai",
    "ja": "クダーイの手爪",
    "ko": "쿠다이의 손톱",
    "nl": "Kudaais vingernagel",
    "pt-BR": "Unha de Kudaai",
    "ru": "Ноготь с руки Кыдая",
    "tr": "Kudaai'nin Tırnağı",
    "zh-CN": "库鐽伊之指甲",
    "zh-TW": "庫鐽伊之指甲"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/RerollWeapon.png",
  "unlockedBy": "Building_LightningRod",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/HealPerFollower_Blessed.json
{
  "chargeCategory": "Fast",
  "chargeDamage": 30.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "يمكن اكتساب نصف قلب روح مقابل كل تابع مسن.",
    "de": "Erhalte ein halbes Geisterherz pro Ältester-Anhänger.",
    "en": "Gain half a Spirit Heart per Elderly Follower.",
    "es": "Gana medio corazón fantasma por cada adepto anciano.",
    "fr": "Obtenez une moitié de cœur spirituel par adepte âgé.",
    "fr-CA": "Obtenez une moitié de cœur spirituel par adepte âgé.",
    "it": "Conferisce mezzo cuore spirituale per ogni membro anziano del Culto.",
    "ja": "高齢の信者1人につき、半分のスピリットハートを獲得する",
    "ko": "노인 추종자 하나당 영혼 심장 반쪽을 얻습니다.",
    "nl": "Krijg een half spiritueel hart per bejaarde volgeling.",
    "pt-BR": "Ganhe meio Coração Espiritual por Seguidor Idoso.",
    "ru": "Вы получаете по половине эфемерного сердца за каждого пожилого последователя.",
    "tr": "Tarikat'ındaki İhtiyar Takipçi başına bir yarım Ruh Kalbi kazanırsın.",
    "zh-CN": "教中每有一位年长教徒，就获得半颗灵心。",
    "zh-TW": "教中每有一位年長教徒，就獲得半顆靈心。"
  },
  "descriptionPlain": {
    "ar": "يمكن اكتساب نصف قلب روح مقابل كل تابع مسن.",
    "de": "Erhalte ein halbes Geisterherz pro Ältester-Anhänger.",
    "en": "Gain half a Spirit Heart per Elderly Follower.",
    "es": "Gana medio corazón fantasma por cada adepto anciano.",
    "fr": "Obtenez une moitié de cœur spirituel par adepte âgé.",
    "fr-CA": "Obtenez une moitié de cœur spirituel par adepte âgé.",
    "it": "Conferisce mezzo cuore spirituale per ogni membro anziano del Culto.",
    "ja": "高齢の信者1人につき、半分のスピリットハートを獲得する",
    "ko": "노인 추종자 하나당 영혼 심장 반쪽을 얻습니다.",
    "nl": "Krijg een half spiritueel hart per bejaarde volgeling.",
    "pt-BR": "Ganhe meio Coração Espiritual por Seguidor Idoso.",
    "ru": "Вы получаете по половине эфемерного сердца за каждого пожилого последователя.",
    "tr": "Tarikat'ındaki İhtiyar Takipçi başına bir yarım Ruh Kalbi kazanırsın.",
    "zh-CN": "教中每有一位年长教徒，就获得半颗灵心。",
    "zh-TW": "教中每有一位年長教徒，就獲得半顆靈心。"
  },
  "dlc": false,
  "icon": "icons/relics/HealPerFollower_Blessed.png",
  "id": "HealPerFollower_Blessed",
  "interactionType": "Fragile",
  "lore": {
    "ar": "لن يتركونا أبدًا.",
    "de": "Mögen sie uns nie verlassen.",
    "en": "They shall never leave us.",
    "es": "Jamás nos abandonarán.",
    "fr": "Ils ne partiront jamais vraiment.",
    "fr-CA": "Ils ne partiront jamais vraiment.",
    "it": "Saranno sempre con noi.",
    "ja": "彼らが我らを見捨てることはない",
    "ko": "그들은 우리를 떠나지 않을 터.",
    "nl": "Ze zullen ons nooit verlaten.",
    "pt-BR": "Eles nunca nos deixarão.",
    "ru": "Да не оставят они нас.",
    "tr": "Bizi asla terk etmeyecekler.",
    "zh-CN": "愿那些人永不离开我们。",
    "zh-TW": "願那些人永不離開我們。"
  },
  "majorDlc": false,
  "name": {
    "ar": "بلسم المعتزِل <color=#03EAFD>المبارك</color>",
    "de": "<color=#03EAFD>Gesegneter</color> Balsam des Einsiedlers",
    "en": "<color=#03EAFD>Blessed</color> Balm of the Anchorite",
    "es": "Bálsamo <color=#03EAFD>bendecido</color> del ermitaño",
    "fr": "Baume de l'anachorète <color=#03EAFD>béni</color>",
    "fr-CA": "Baume <color=#03EAFD>béni</color> de l'anachorète",
    "it": "Balsamo dell'anacoreta <color=#03EAFD>benedetto</color>",
    "ja": "<color=#03EAFD>祝福された</color>隠者の香油",
    "ko": "<color=#03EAFD>축복받은</color> 은자의 연고",
    "nl": "<color=#03EAFD>Gezegende</color> balsem van de Anchoriet",
    "pt-BR": "Bálsamo do Anacoreta <color=#03EAFD>Abençoado</color>",
    "ru": "<color=#03EAFD>Священный</color> бальзам аскета",
    "tr": "<color=#03EAFD>Kutsanmış</color> Münzevinin Merhemi",
    "zh-CN": "<color=#03EAFD>受祝福的</color>隐修者香膏",
    "zh-TW": "<color=#03EAFD>受祝福的</color>隱修者香膏"
  },
  "namePlain": {
    "ar": "بلسم المعتزِل المبارك",
    "de": "Gesegneter Balsam des Einsiedlers",
    "en": "Blessed Balm of the Anchorite",
    "es": "Bálsamo bendecido del ermitaño",
    "fr": "Baume de l'anachorète béni",
    "fr-CA": "Baume béni de l'anachorète",
    "it": "Balsamo dell'anacoreta benedetto",
    "ja": "祝福された隠者の香油",
    "ko": "축복받은 은자의 연고",
    "nl": "Gezegende balsem van de Anchoriet",
    "pt-BR": "Bálsamo do Anacoreta Abençoado",
    "ru": "Священный бальзам аскета",
    "tr": "Kutsanmış Münzevinin Merhemi",
    "zh-CN": "受祝福的隐修者香膏",
    "zh-TW": "受祝福的隱修者香膏"
  },
  "requiresCult": true,
  "subType": "Any",
  "thumb": "icons/relics/64/HealPerFollower_Blessed.png",
  "unlockedBy": "Relics_Blessed_1",
  "weight": 1.0
}
