=== AuthFailed/cotl-api/schema/relic.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Relic",
  "type": "object",
  "required": [
    "id",
    "name",
    "description",
    "namePlain",
    "descriptionPlain",
    "icon",
    "thumb",
    "lore",
    "subType",
    "interactionType",
    "damageType",
    "chargeDamage",
    "chargeCategory",
    "weight",
    "requiresCult",
    "unlockedBy",
    "dlc",
    "coop",
    "majorDlc"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]+$"
    },
    "name": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      },
      "required": [
        "en"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "namePlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "name without the game's text markup"
    },
    "descriptionPlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "description without the game's text markup"
    },
    "icon": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/relics/[A-Za-z0-9_-]+\\.png$"
    },
    "thumb": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/relics/64/[A-Za-z0-9_-]+\\.png$"
    },
    "lore": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "subType": {
      "type": [
        "string",
        "null"
      ],
      "description": "None, Blessed, Damned, Corrupted, Coop ..."
    },
    "interactionType": {
      "type": [
        "string",
        "null"
      ],
      "description": "Instant, Fragile (single use) ..."
    },
    "damageType": {
      "type": [
        "string",
        "null"
      ],
      "description": "damage that charges it"
    },
    "chargeDamage": {
      "type": "number",
      "description": "damage needed to charge it"
    },
    "chargeCategory": {
      "type": [
        "string",
        "null"
      ],
      "description": "Fast, Average or Slow, as the game labels it"
    },
    "weight": {
      "type": "number",
      "description": "draw weight"
    },
    "requiresCult": {
      "type": "boolean",
      "description": "only appears once you have a cult"
    },
    "unlockedBy": {
      "type": [
        "string",
        "null"
      ],
      "description": "UpgradeSystem upgrade that unlocks it"
    },
    "dlc": {
      "type": "boolean",
      "description": ""
    },
    "coop": {
      "type": "boolean",
      "description": ""
    },
    "majorDlc": {
      "type": "boolean",
      "description": ""
    }
  }
}

=== AuthFailed/cotl-api/site/v1/relics/UnlimitedFervour.json
{
  "chargeCategory": "Slow",
  "chargeDamage": 120.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "يمكن اكتساب حماس غير محدود <sprite name=\"icon_blackSoul\"> لمدة 5 ثوانٍ.",
    "de": "Erhalte 5 Sekunden lang unendlich Eifer <sprite name=\"icon_blackSoul\">.",
    "en": "Gain unlimited Fervour <sprite name=\"icon_blackSoul\"> for 5 seconds.",
    "es": "Obtén fervor ilimitado <sprite name=\"icon_blackSoul\"> durante 5 segundos.",
    "fr": "Octroie ferveur <sprite name=\"icon_blackSoul\"> illimitée pendant 5 secondes.",
    "fr-CA": "Octroie ferveur <sprite name=\"icon_blackSoul\"> illimitée pendant 5 secondes.",
    "it": "Conferisce Fervore infinito <sprite name=\"icon_blackSoul\"> per 5 secondi.",
    "ja": "5秒間、信力 <sprite name=\"icon_blackSoul\"> が無限になる",
    "ko": "5초 동안 무제한 열정 <sprite name=\"icon_blackSoul\">을 얻습니다.",
    "nl": "Krijg 5 seconden lang onbeperkte furie <sprite name=\"icon_blackSoul\">.",
    "pt-BR": "Ganha Fervor <sprite name=\"icon_blackSoul\"> ilimitado por 5 segundos.",
    "ru": "Усердие <sprite name=\"icon_blackSoul\"> не истощается в течение 5 сек.",
    "tr": "5 saniyeliğine sınırsız Şevk <sprite name=\"icon_blackSoul\"> kazanırsın.",
    "zh-CN": "获得无限热诚 <sprite name=\"icon_blackSoul\">，持续 5 秒。",
    "zh-TW": "獲得無限熱誠 <sprite name=\"icon_blackSoul\">，持續 5 秒。"
  },
  "descriptionPlain": {
    "ar": "يمكن اكتساب حماس غير محدود لمدة 5 ثوانٍ.",
    "de": "Erhalte 5 Sekunden lang unendlich Eifer.",
    "en": "Gain unlimited Fervour for 5 seconds.",
    "es": "Obtén fervor ilimitado durante 5 segundos.",
    "fr": "Octroie ferveur illimitée pendant 5 secondes.",
    "fr-CA": "Octroie ferveur illimitée pendant 5 secondes.",
    "it": "Conferisce Fervore infinito per 5 secondi.",
    "ja": "5秒間、信力 が無限になる",
    "ko": "5초 동안 무제한 열정 을 얻습니다.",
    "nl": "Krijg 5 seconden lang onbeperkte furie.",
    "pt-BR": "Ganha Fervor ilimitado por 5 segundos.",
    "ru": "Усердие не истощается в течение 5 сек.",
    "tr": "5 saniyeliğine sınırsız Şevk kazanırsın.",
    "zh-CN": "获得无限热诚 ，持续 5 秒。",
    "zh-TW": "獲得無限熱誠 ，持續 5 秒。"
  },
  "dlc": false,
  "icon": "icons/relics/UnlimitedFervour.png",
  "id": "UnlimitedFervour",
  "interactionType": "Charging",
  "lore": {
    "ar": "ليس صلبًا ولا سائلًا ولا دخانًا...",
    "de": "Nicht fest, nicht flüssig, nicht gasförmig …",
    "en": "Not solid, nor liquid, nor smoke...",
    "es": "Ni sólido, ni líquido, ni humo...",
    "fr": "Ni solide, ni liquide, ni gazeux...",
    "fr-CA": "Ni solide, ni liquide, ni gazeux...",
    "it": "Né solido, né liquido, né gassoso...",
    "ja": "固体でも、液体でも、気体でもない…",
    "ko": "고체도 아니요, 액체도 아니요, 연기도 아닐지니...",
    "nl": "Niet vast, noch vloeibaar, noch rook...",
    "pt-BR": "Não é sólido, nem líquido, nem gasoso...",
    "ru": "Не твёрдый, не жидкий, не эфемерный.",
    "tr": "Ne katı ne sıvı ne de duman...",
    "zh-CN": "非固、非液、非气……",
    "zh-TW": "非固、非液、非氣……"
  },
  "majorDlc": false,
  "name": {
    "ar": "رحيق التيجان",
    "de": "Nektar der Kronen",
    "en": "Nectar of the Crowns",
    "es": "Néctar de las Coronas",
    "fr": "Nectar des Couronnes",
    "fr-CA": "Nectar des Couronnes",
    "it": "Nettare delle Corone",
    "ja": "王冠のネクター",
    "ko": "왕관의 넥타르",
    "nl": "Nectar van de kronen",
    "pt-BR": "Néctar das Coroas",
    "ru": "Нектар коронованных",
    "tr": "Taç Nektarı",
    "zh-CN": "圣冠琼浆",
    "zh-TW": "聖冠瓊漿"
  },
  "namePlain": {
    "ar": "رحيق التيجان",
    "de": "Nektar der Kronen",
    "en": "Nectar of the Crowns",
    "es": "Néctar de las Coronas",
    "fr": "Nectar des Couronnes",
    "fr-CA": "Nectar des Couronnes",
    "it": "Nettare delle Corone",
    "ja": "王冠のネクター",
    "ko": "왕관의 넥타르",
    "nl": "Nectar van de kronen",
    "pt-BR": "Néctar das Coroas",
    "ru": "Нектар коронованных",
    "tr": "Taç Nektarı",
    "zh-CN": "圣冠琼浆",
    "zh-TW": "聖冠瓊漿"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/UnlimitedFervour.png",
  "unlockedBy": "Building_LightningRod",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/IceyCoat.json
{
  "chargeCategory": "Slow",
  "chargeDamage": 80.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "حماية من القذائف لمدة 10 ثوانٍ.",
    "de": "10 Sekunden lang immun gegen Projektile.",
    "en": "Immune to projectiles for 10 seconds.",
    "es": "Inmune a los proyectiles durante 10 segundos.",
    "fr": "Immunise contre les projectiles pendant 10 secondes.",
    "fr-CA": "Immunise contre les projectiles pendant 10 secondes.",
    "it": "Immunità ai proiettili per 10 secondi.",
    "ja": "遠距離攻撃を10秒間無効化する",
    "ko": "10초 동안 탄환에 면역이 됩니다.",
    "nl": "Immuun voor projectielen gedurende 10 seconden.",
    "pt-BR": "Imune a projéteis por 10 segundos.",
    "ru": "Вы не получаете урона от снарядов в течение 10 сек.",
    "tr": "10 saniye boyunca menzilli saldırılardan hasar almazsın.",
    "zh-CN": "对投射物免疫 10 秒。",
    "zh-TW": "對投射物免疫 10 秒。"
  },
  "descriptionPlain": {
    "ar": "حماية من القذائف لمدة 10 ثوانٍ.",
    "de": "10 Sekunden lang immun gegen Projektile.",
    "en": "Immune to projectiles for 10 seconds.",
    "es": "Inmune a los proyectiles durante 10 segundos.",
    "fr": "Immunise contre les projectiles pendant 10 secondes.",
    "fr-CA": "Immunise contre les projectiles pendant 10 secondes.",
    "it": "Immunità ai proiettili per 10 secondi.",
    "ja": "遠距離攻撃を10秒間無効化する",
    "ko": "10초 동안 탄환에 면역이 됩니다.",
    "nl": "Immuun voor projectielen gedurende 10 seconden.",
    "pt-BR": "Imune a projéteis por 10 segundos.",
    "ru": "Вы не получаете урона от снарядов в течение 10 сек.",
    "tr": "10 saniye boyunca menzilli saldırılardan hasar almazsın.",
    "zh-CN": "对投射物免疫 10 秒。",
    "zh-TW": "對投射物免疫 10 秒。"
  },
  "dlc": true,
  "icon": "icons/relics/IceyCoat.png",
  "id": "IceyCoat",
  "interactionType": "Charging",
  "lore": {
    "ar": "سقطت من ظهر كائن زاحف عظيم.",
    "de": "Vom Rücken einer großen, kriechenden Kreatur abgestoßen.",
    "en": "Shed from the back of a great crawling creature.",
    "es": "Piel del lomo de una enorme criatura reptante.",
    "fr": "Tombée du dos d'une énorme créature rampante.",
    "fr-CA": "Tombée du dos d'une énorme créature rampante.",
    "it": "Staccatosi dal dorso di un'enorme creatura strisciante.",
    "ja": "地面を這う大いなる生物の背中から落ちたとされるもの",
    "ko": "기어다니는 거대 짐승에게서 떨어져 나온 것.",
    "nl": "Achtergebleven bij de vervelling van een monsterlijk wezen.",
    "pt-BR": "Tirado do corpo de uma grande criatura rastejante.",
    "ru": "Сброшена огромным ползучим существом.",
    "tr": "Yerde sürünen büyük bir yaratığın sırtından alınmış.",
    "zh-CN": "古代某种伟大爬行生物的空壳。",
    "zh-TW": "古代某種偉大爬行生物的空殼。"
  },
  "majorDlc": true,
  "name": {
    "ar": "قشرة التندرين",
    "de": "Hülle der Tundrane",
    "en": "Husk of the Tundrane",
    "es": "Muda de tundrane",
    "fr": "Enveloppe de la Toundrage",
    "fr-CA": "Enveloppe de la Toundrage",
    "it": "Guscio di Tundrane",
    "ja": "ツンドレインの抜け殻",
    "ko": "툰드레인의 저주",
    "nl": "Pantser van de vorstvlam",
    "pt-BR": "Casco de Tundrane",
    "ru": "Оболочка Тундрана",
    "tr": "Tundra Sineğinin Kabuğu",
    "zh-CN": "冻原之壳",
    "zh-TW": "凍原之殼"
  },
  "namePlain": {
    "ar": "قشرة التندرين",
    "de": "Hülle der Tundrane",
    "en": "Husk of the Tundrane",
    "es": "Muda de tundrane",
    "fr": "Enveloppe de la Toundrage",
    "fr-CA": "Enveloppe de la Toundrage",
    "it": "Guscio di Tundrane",
    "ja": "ツンドレインの抜け殻",
    "ko": "툰드레인의 저주",
    "nl": "Pantser van de vorstvlam",
    "pt-BR": "Casco de Tundrane",
    "ru": "Оболочка Тундрана",
    "tr": "Tundra Sineğinin Kabuğu",
    "zh-CN": "冻原之壳",
    "zh-TW": "凍原之殼"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/IceyCoat.png",
  "unlockedBy": "Relics_Ice",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/ProjectileRing.json
{
  "chargeCategory": "Average",
  "chargeDamage": 60.0,
  "coop": false,
  "damageType": "DealsDamage",
  "description": {
    "ar": "يمكن إطلاق ثلاث قذائف لكل حذاء مجهَّز ببطاقة تارو. إن لم يكن لديك بطاقات تارو يمكن إطلاق قذيفتين.",
    "de": "Feuere drei Projektile für jede ausgerüstete Tarotkarte ab. Wenn du keine Tarotkarten besitzt, feuerst du zwei Projektile ab.",
    "en": "Fire three projectiles for each equipped Tarot Card. If you have no Tarot Cards, fire two projectiles.",
    "es": "Dispara tres proyectiles por cada carta del tarot equipada. Si no tienes ninguna, dispara dos proyectiles.",
    "fr": "Tire trois projectiles pour chaque carte de tarot équipée. Si vous n'en portez aucune, tire deux projectiles.",
    "fr-CA": "Tire trois projectiles pour chaque carte de tarot équipée. Si vous n'en portez aucune, tire deux projectiles.",
    "it": "Lancia tre proiettili per ogni tarocco attivo. Se non ne hai, lancia due proiettili.",
    "ja": "装備中のタロットカードの枚数分、3つの弾を射出する。タロットがない場合、2つの弾を射出する",
    "ko": "장비한 타로 카드 한 장당 투사체를 3개 발사합니다. 타로 카드가 없을 경우, 2개를 발사합니다.",
    "nl": "Vuur drie projectielen af voor elke tarotkaart die je hebt. Als je geen tarotkaarten hebt, dan vuur je twee projectielen af.",
    "pt-BR": "Dispare três projéteis para cada Carta de Tarô equipada. Se não tiver nenhuma Carta de Tarô, dispare dois projéteis.",
    "ru": "Вы выпускаете по три снаряда за каждую имеющуюся карту Таро или два снаряда, если у вас нет карт Таро.",
    "tr": "Sahip olduğun her Tarot Kartı için üç menzilli saldırı yaparsın. Hiç Tarot Kartı'n yoksa iki menzilli saldırı yaparsın.",
    "zh-CN": "每装备一张塔罗牌，就射出三个投射物。没有塔罗牌时，射出二个投射物。",
    "zh-TW": "每裝備一張塔羅牌，就射出三個投射物。沒有塔羅牌時，射出二個投射物。"
  },
  "descriptionPlain": {
    "ar": "يمكن إطلاق ثلاث قذائف لكل حذاء مجهَّز ببطاقة تارو. إن لم يكن لديك بطاقات تارو يمكن إطلاق قذيفتين.",
    "de": "Feuere drei Projektile für jede ausgerüstete Tarotkarte ab. Wenn du keine Tarotkarten besitzt, feuerst du zwei Projektile ab.",
    "en": "Fire three projectiles for each equipped Tarot Card. If you have no Tarot Cards, fire two projectiles.",
    "es": "Dispara tres proyectiles por cada carta del tarot equipada. Si no tienes ninguna, dispara dos proyectiles.",
    "fr": "Tire trois projectiles pour chaque carte de tarot équipée. Si vous n'en portez aucune, tire deux projectiles.",
    "fr-CA": "Tire trois projectiles pour chaque carte de tarot équipée. Si vous n'en portez aucune, tire deux projectiles.",
    "it": "Lancia tre proiettili per ogni tarocco attivo. Se non ne hai, lancia due proiettili.",
    "ja": "装備中のタロットカードの枚数分、3つの弾を射出する。タロットがない場合、2つの弾を射出する",
    "ko": "장비한 타로 카드 한 장당 투사체를 3개 발사합니다. 타로 카드가 없을 경우, 2개를 발사합니다.",
    "nl": "Vuur drie projectielen af voor elke tarotkaart die je hebt. Als je geen tarotkaarten hebt, dan vuur je twee projectielen af.",
    "pt-BR": "Dispare três projéteis para cada Carta de Tarô equipada. Se não tiver nenhuma Carta de Tarô, dispare dois projéteis.",
    "ru": "Вы выпускаете по три снаряда за каждую имеющуюся карту Таро или два снаряда, если у вас нет карт Таро.",
    "tr": "Sahip olduğun her Tarot Kartı için üç menzilli saldırı yaparsın. Hiç Tarot Kartı'n yoksa iki menzilli saldırı yaparsın.",
    "zh-CN": "每装备一张塔罗牌，就射出三个投射物。没有塔罗牌时，射出二个投射物。",
    "zh-TW": "每裝備一張塔羅牌，就射出三個投射物。沒有塔羅牌時，射出二個投射物。"
  },
  "dlc": false,
  "icon": "icons/relics/ProjectileRing.png",
  "id": "ProjectileRing",
  "interactionType": "Charging",
  "lore": {
    "ar": "هل يعرف حتى أنه مفقود؟",
    "de": "Weiß er überhaupt, dass er weg ist?",
    "en": "Does he even know that it's missing?",
    "es": "¿Sabe siquiera que ha desaparecido?",
    "fr": "Est-ce qu'il a remarqué qu'il l'avait perdue ?",
    "fr-CA": "Est-ce qu'il a remarqué qu'il l'avait perdue?",
    "it": "Si è accorto che gli manca?",
    "ja": "靴がないことに、彼は気が付いているのだろうか？",
    "ko": "자기가 잃어버린 게 뭔지나 알까?",
    "nl": "Weet hij überhaupt dat hij die kwijt is?",
    "pt-BR": "Ele nem mesmo percebeu que está faltando um?",
    "ru": "Знает ли о потере он сам?",
    "tr": "Bunun kaybolduğunun farkında mı acaba?",
    "zh-CN": "他知道鞋子不见了吗？",
    "zh-TW": "他知道鞋子不見了嗎？"
  },
  "majorDlc": false,
  "name": {
    "ar": "حذاء كلاونيك",
    "de": "Claunecks Schuh",
    "en": "Clauneck's Shoe",
    "es": "Zapato de Clauneck",
    "fr": "Chaussure de Clauneck",
    "fr-CA": "Chaussure de Clauneck",
    "it": "Calzatura di Clauneck",
    "ja": "クラウネックの靴",
    "ko": "클라우넥의 신발",
    "nl": "Claunecks schoen",
    "pt-BR": "Sapato de Clauneck",
    "ru": "Тапочек Клонека",
    "tr": "Clauneck'in Ayakkabısı",
    "zh-CN": "克劳内克之鞋",
    "zh-TW": "克勞涅克之鞋"
  },
  "namePlain": {
    "ar": "حذاء كلاونيك",
    "de": "Claunecks Schuh",
    "en": "Clauneck's Shoe",
    "es": "Zapato de Clauneck",
    "fr": "Chaussure de Clauneck",
    "fr-CA": "Chaussure de Clauneck",
    "it": "Calzatura di Clauneck",
    "ja": "クラウネックの靴",
    "ko": "클라우넥의 신발",
    "nl": "Claunecks schoen",
    "pt-BR": "Sapato de Clauneck",
    "ru": "Тапочек Клонека",
    "tr": "Clauneck'in Ayakkabısı",
    "zh-CN": "克劳内克之鞋",
    "zh-TW": "克勞涅克之鞋"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/ProjectileRing.png",
  "unlockedBy": "Building_LightningRod",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/DestroyTarotDealDamge.json
{
  "chargeCategory": "Average",
  "chargeDamage": 60.0,
  "coop": false,
  "damageType": "DealsDamage",
  "description": {
    "ar": "يمكن إلحاق الضرر بجميع الأعداء وفقًا لعدد بطاقات التارو التي لديك.",
    "de": "Füge allen Gegnern Schaden entsprechend der Menge deiner Tarotkarten zu.",
    "en": "Deal damage to all enemies based on the amount of Tarot Cards you hold.",
    "es": "Inflige daño a todos los enemigos en función del número de cartas del tarot que tengas.",
    "fr": "Inflige des dégâts à tous les ennemis selon le nombre de cartes de tarot que vous avez.",
    "fr-CA": "Inflige des dégâts à tous les ennemis selon le nombre de cartes de tarot que vous avez.",
    "it": "Infligge danni a tutti i nemici in base al numero di tarocchi attivi.",
    "ja": "所持しているタロットカードの枚数に応じたダメージを敵全体に与える",
    "ko": "보유한 타로 카드의 수에 비례한 피해를 모든 적에게 가합니다.",
    "nl": "Breng schade toe aan alle vijanden op basis van het aantal tarotkaarten dat je bij je hebt.",
    "pt-BR": "Cause dano a todos os inimigos com base na quantidade de Cartas de Tarô que você carrega.",
    "ru": "Вы наносите врагам урон, зависящий от количества имеющихся карт Таро.",
    "tr": "Düşmanlara elindeki Tarot Kartı sayısına bağlı olarak hasar verir.",
    "zh-CN": "依照持有的塔罗牌数量，对所有敌人造成伤害。",
    "zh-TW": "依照持有的塔羅牌數量，對所有敵人造成傷害。"
  },
  "descriptionPlain": {
    "ar": "يمكن إلحاق الضرر بجميع الأعداء وفقًا لعدد بطاقات التارو التي لديك.",
    "de": "Füge allen Gegnern Schaden entsprechend der Menge deiner Tarotkarten zu.",
    "en": "Deal damage to all enemies based on the amount of Tarot Cards you hold.",
    "es": "Inflige daño a todos los enemigos en función del número de cartas del tarot que tengas.",
    "fr": "Inflige des dégâts à tous les ennemis selon le nombre de cartes de tarot que vous avez.",
    "fr-CA": "Inflige des dégâts à tous les ennemis selon le nombre de cartes de tarot que vous avez.",
    "it": "Infligge danni a tutti i nemici in base al numero di tarocchi attivi.",
    "ja": "所持しているタロットカードの枚数に応じたダメージを敵全体に与える",
    "ko": "보유한 타로 카드의 수에 비례한 피해를 모든 적에게 가합니다.",
    "nl": "Breng schade toe aan alle vijanden op basis van het aantal tarotkaarten dat je bij je hebt.",
    "pt-BR": "Cause dano a todos os inimigos com base na quantidade de Cartas de Tarô que você carrega.",
    "ru": "Вы наносите врагам урон, зависящий от количества имеющихся карт Таро.",
    "tr": "Düşmanlara elindeki Tarot Kartı sayısına bağlı olarak hasar verir.",
    "zh-CN": "依照持有的塔罗牌数量，对所有敌人造成伤害。",
    "zh-TW": "依照持有的塔羅牌數量，對所有敵人造成傷害。"
  },
  "dlc": false,
  "icon": "icons/relics/DestroyTarotDealDamge.png",
  "id": "DestroyTarotDealDamge",
  "interactionType": "Charging",
  "lore": {
    "ar": "ريش الوفرة والحظ.",
    "de": "Gefiedert und vom Zufall bestimmt.",
    "en": "Feathered and fortuitous.",
    "es": "Emplumado y fortuito.",
    "fr": "Porte-plume, et porte chance.",
    "fr-CA": "Porte-plume et porte-bonheur.",
    "it": "Piumati e fortunati.",
    "ja": "この羽毛は幸運をもたらす",
    "ko": "깃털 투성이의 행운이다.",
    "nl": "Gevederd en fortuinlijk.",
    "pt-BR": "Emplumado e fortuito.",
    "ru": "Удача в пучке волос.",
    "tr": "Tüylü ve tesadüfi.",
    "zh-CN": "带有羽毛及机运。",
    "zh-TW": "帶有羽毛及機運。"
  },
  "majorDlc": false,
  "name": {
    "ar": "خُصلة كلاونيك",
    "de": "Claunecks Haar",
    "en": "Clauneck's Hair",
    "es": "Pelo de Clauneck",
    "fr": "Cheveux de Clauneck",
    "fr-CA": "Cheveux de Clauneck",
    "it": "Capelli di Clauneck",
    "ja": "クラウネックの羽毛",
    "ko": "클라우넥의 머리카락",
    "nl": "Claunecks haar",
    "pt-BR": "Cabelo de Clauneck",
    "ru": "Прядь Клонека",
    "tr": "Clauneck'in Saçı",
    "zh-CN": "克劳内克之毛发",
    "zh-TW": "克勞涅克之毛髮"
  },
  "namePlain": {
    "ar": "خُصلة كلاونيك",
    "de": "Claunecks Haar",
    "en": "Clauneck's Hair",
    "es": "Pelo de Clauneck",
    "fr": "Cheveux de Clauneck",
    "fr-CA": "Cheveux de Clauneck",
    "it": "Capelli di Clauneck",
    "ja": "クラウネックの羽毛",
    "ko": "클라우넥의 머리카락",
    "nl": "Claunecks haar",
    "pt-BR": "Cabelo de Clauneck",
    "ru": "Прядь Клонека",
    "tr": "Clauneck'in Saçı",
    "zh-CN": "克劳内克之毛发",
    "zh-TW": "克勞涅克之毛髮"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/DestroyTarotDealDamge.png",
  "unlockedBy": "Relic_Pack_Default",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/Shrink.json
{
  "chargeCategory": "Fast",
  "chargeDamage": 30.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "يمكن تقليل حجم الحَمَل.",
    "de": "Werde kleiner.",
    "en": "Decrease in size.",
    "es": "Reduce el tamaño.",
    "fr": "Diminue votre taille.",
    "fr-CA": "Diminue votre taille.",
    "it": "Ti riduce di statura.",
    "ja": "体が小さくなる",
    "ko": "크기가 줄어듭니다.",
    "nl": "Word kleiner.",
    "pt-BR": "Diminua de tamanho.",
    "ru": "Вы уменьшаетесь в размерах.",
    "tr": "Boyutun küçülür.",
    "zh-CN": "体型变小。",
    "zh-TW": "體型變小。"
  },
  "descriptionPlain": {
    "ar": "يمكن تقليل حجم الحَمَل.",
    "de": "Werde kleiner.",
    "en": "Decrease in size.",
    "es": "Reduce el tamaño.",
    "fr": "Diminue votre taille.",
    "fr-CA": "Diminue votre taille.",
    "it": "Ti riduce di statura.",
    "ja": "体が小さくなる",
    "ko": "크기가 줄어듭니다.",
    "nl": "Word kleiner.",
    "pt-BR": "Diminua de tamanho.",
    "ru": "Вы уменьшаетесь в размерах.",
    "tr": "Boyutun küçülür.",
    "zh-CN": "体型变小。",
    "zh-TW": "體型變小。"
  },
  "dlc": false,
  "icon": "icons/relics/Shrink.png",
  "id": "Shrink",
  "interactionType": "Fragile",
  "lore": {
    "ar": "شونرو، عدو معروف.",
    "de": "Shunrue, berühmter Gegner.",
    "en": "Shunrue, famed foe.",
    "es": "Shunrue, rival legendario.",
    "fr": "Shunrue, mon ennemi juré.",
    "fr-CA": "Shunrue, mon ennemi juré.",
    "it": "Shunrue, famigerato nemico.",
    "ja": "名うての敵、その名もシュンルー",
    "ko": "슌뤼, 유명한 적이다.",
    "nl": "Shunrue, beroemde vijand.",
    "pt-BR": "Shunrue, antagonista notável.",
    "ru": "Шунру, заклятый враг.",
    "tr": "Meşhur düşman Shunrue.",
    "zh-CN": "襄茹，著名的强敌。",
    "zh-TW": "襄茹，著名的強敵。"
  },
  "majorDlc": false,
  "name": {
    "ar": "تميمة شونرو",
    "de": "Shunrues Talisman",
    "en": "Shunrue's Charm",
    "es": "Amuleto de Shunrue",
    "fr": "Charme de Shunrue",
    "fr-CA": "Charme de Shunrue",
    "it": "Portafortuna di Shunrue",
    "ja": "シュンルーの魔除け",
    "ko": "슌뤼의 부적",
    "nl": "Amulet van Shunrue",
    "pt-BR": "Amuleto de Shunrue",
    "ru": "Талисман Шунру",
    "tr": "Shunrue'nun Tılsımı",
    "zh-CN": "襄茹之护身符",
    "zh-TW": "襄茹之護身符"
  },
  "namePlain": {
    "ar": "تميمة شونرو",
    "de": "Shunrues Talisman",
    "en": "Shunrue's Charm",
    "es": "Amuleto de Shunrue",
    "fr": "Charme de Shunrue",
    "fr-CA": "Charme de Shunrue",
    "it": "Portafortuna di Shunrue",
    "ja": "シュンルーの魔除け",
    "ko": "슌뤼의 부적",
    "nl": "Amulet van Shunrue",
    "pt-BR": "Amuleto de Shunrue",
    "ru": "Талисман Шунру",
    "tr": "Shunrue'nun Tılsımı",
    "zh-CN": "襄茹之护身符",
    "zh-TW": "襄茹之護身符"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/Shrink.png",
  "unlockedBy": "Relic_Pack_Default",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/FieryBlood.json
{
  "chargeCategory": "Fast",
  "chargeDamage": 30.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "تبديل كل القلوب بقلوب مشتعلة.",
    "de": "Ersetze alle Herzen durch Geschmolzene Herzen.",
    "en": "Replace all hearts with Molten Hearts.",
    "es": "Reemplaza todos los corazones por corazones ígneos.",
    "fr": "Remplace tous les cœurs par des cœurs en fusion.",
    "fr-CA": "Remplace tous les cœurs par des cœurs en fusion.",
    "it": "Tutti i cuori vengono sostituiti da cuori ardenti.",
    "ja": "すべてのハートを炎の心臓に変換する",
    "ko": "모든 심장을 녹아내린 심장으로 교체합니다.",
    "nl": "Vervang alle harten door smeulende harten.",
    "pt-BR": "Substitui todos os corações por Corações Queimados.",
    "ru": "Все ваши сердца становятся раскалёнными.",
    "tr": "Tüm kalplerin Kor Kalp olur.",
    "zh-CN": "将所有心替换为熔心。",
    "zh-TW": "將所有心替換為熔心。"
  },
  "descriptionPlain": {
    "ar": "تبديل كل القلوب بقلوب مشتعلة.",
    "de": "Ersetze alle Herzen durch Geschmolzene Herzen.",
    "en": "Replace all hearts with Molten Hearts.",
    "es": "Reemplaza todos los corazones por corazones ígneos.",
    "fr": "Remplace tous les cœurs par des cœurs en fusion.",
    "fr-CA": "Remplace tous les cœurs par des cœurs en fusion.",
    "it": "Tutti i cuori vengono sostituiti da cuori ardenti.",
    "ja": "すべてのハートを炎の心臓に変換する",
    "ko": "모든 심장을 녹아내린 심장으로 교체합니다.",
    "nl": "Vervang alle harten door smeulende harten.",
    "pt-BR": "Substitui todos os corações por Corações Queimados.",
    "ru": "Все ваши сердца становятся раскалёнными.",
    "tr": "Tüm kalplerin Kor Kalp olur.",
    "zh-CN": "将所有心替换为熔心。",
    "zh-TW": "將所有心替換為熔心。"
  },
  "dlc": true,
  "icon": "icons/relics/FieryBlood.png",
  "id": "FieryBlood",
  "interactionType": "Fragile",
  "lore": {
    "ar": "يغطيه السناج لكنه لم يُحرق.",
    "de": "Mit Ruß bedeckt und doch unversengt.",
    "en": "Covered in soot and yet unburned.",
    "es": "Cubierto de hollín y, aun así, intacto.",
    "fr": "Outre la suie qui la recouvre, elle reste intacte.",
    "fr-CA": "Outre la suie qui la recouvre, elle demeure intacte.",
    "it": "Coperto di fuliggine, eppur intoccato dalle fiamme.",
    "ja": "煤に覆われているが、焼けてはいない",
    "ko": "그을음으로 덮였지만 아직 타지 않았다.",
    "nl": "Bedekt met roet maar niet verbrand.",
    "pt-BR": "A fuligem cobre seu corpo, mas não há queimaduras.",
    "ru": "Покрытый пеплом, но неопалённый.",
    "tr": "Kurumla kaplı olsa da yanmamış.",
    "zh-CN": "覆满煤灰，却还没燃烧起来。",
    "zh-TW": "覆滿煤灰，卻還沒燃燒起來。"
  },
  "majorDlc": true,
  "name": {
    "ar": "تمثال الموت حرقًا",
    "de": "Idol der Geopferten",
    "en": "Idol of the Immolated",
    "es": "Ídolo del sacrificado",
    "fr": "Idole des immolés",
    "fr-CA": "Idole des immolés",
    "it": "Idolo dell'immolato",
    "ja": "捧げられし者の偶像",
    "ko": "분신한 번제의 우상",
    "nl": "Afgod van de brandoffers",
    "pt-BR": "Ídolo dos Imolados",
    "ru": "Идол закланных",
    "tr": "Ateş Kurbanı Heykelciği",
    "zh-CN": "祭品神像",
    "zh-TW": "祭品神像"
  },
  "namePlain": {
    "ar": "تمثال الموت حرقًا",
    "de": "Idol der Geopferten",
    "en": "Idol of the Immolated",
    "es": "Ídolo del sacrificado",
    "fr": "Idole des immolés",
    "fr-CA": "Idole des immolés",
    "it": "Idolo dell'immolato",
    "ja": "捧げられし者の偶像",
    "ko": "분신한 번제의 우상",
    "nl": "Afgod van de brandoffers",
    "pt-BR": "Ídolo dos Imolados",
    "ru": "Идол закланных",
    "tr": "Ateş Kurbanı Heykelciği",
    "zh-CN": "祭品神像",
    "zh-TW": "祭品神像"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/FieryBlood.png",
  "unlockedBy": "Building_LightningRod",
  "weight": 1.0
}
