=== AuthFailed/cotl-api/schema/relic.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Relic",
  "type": "object",
  "required": [
    "id",
    "name",
    "description",
    "namePlain",
    "descriptionPlain",
    "icon",
    "thumb",
    "lore",
    "subType",
    "interactionType",
    "damageType",
    "chargeDamage",
    "chargeCategory",
    "weight",
    "requiresCult",
    "unlockedBy",
    "dlc",
    "coop",
    "majorDlc"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]+$"
    },
    "name": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      },
      "required": [
        "en"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "namePlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "name without the game's text markup"
    },
    "descriptionPlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "description without the game's text markup"
    },
    "icon": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/relics/[A-Za-z0-9_-]+\\.png$"
    },
    "thumb": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/relics/64/[A-Za-z0-9_-]+\\.png$"
    },
    "lore": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "subType": {
      "type": [
        "string",
        "null"
      ],
      "description": "None, Blessed, Damned, Corrupted, Coop ..."
    },
    "interactionType": {
      "type": [
        "string",
        "null"
      ],
      "description": "Instant, Fragile (single use) ..."
    },
    "damageType": {
      "type": [
        "string",
        "null"
      ],
      "description": "damage that charges it"
    },
    "chargeDamage": {
      "type": "number",
      "description": "damage needed to charge it"
    },
    "chargeCategory": {
      "type": [
        "string",
        "null"
      ],
      "description": "Fast, Average or Slow, as the game labels it"
    },
    "weight": {
      "type": "number",
      "description": "draw weight"
    },
    "requiresCult": {
      "type": "boolean",
      "description": "only appears once you have a cult"
    },
    "unlockedBy": {
      "type": [
        "string",
        "null"
      ],
      "description": "UpgradeSystem upgrade that unlocks it"
    },
    "dlc": {
      "type": "boolean",
      "description": ""
    },
    "coop": {
      "type": "boolean",
      "description": ""
    },
    "majorDlc": {
      "type": "boolean",
      "description": ""
    }
  }
}

=== AuthFailed/cotl-api/site/v1/relics/DealDamagePerFollower_Dammed.json
{
  "chargeCategory": "Average",
  "chargeDamage": 75.0,
  "coop": false,
  "damageType": "DealsDamage",
  "description": {
    "ar": "يمكن إلحاق الضرر بجميع الأعداء وفقًا لعدد أتباعك المعارضين.",
    "de": "Füge allen Gegnern entsprechend der Anzahl deiner abtrünnigen Anhänger Schaden zu.",
    "en": "Damage all enemies based on how many Dissenting Followers you have.",
    "es": "Inflige daño a todos los enemigos en función del número de adeptos desertores que tengas.",
    "fr": "Infligez des dégâts à tous les ennemis selon votre nombre d'adeptes rebelles.",
    "fr-CA": "Infligez des dégâts à tous les ennemis selon votre nombre d'adeptes rebelles.",
    "it": "Infligge danni a tutti i nemici in base al numero dei membri dissidenti del Culto.",
    "ja": "教団に所属している離反中の信者の人数に応じたダメージを敵全体に与える",
    "ko": "보유한 반목 중인 추종자들의 수에 비례해 모든 적에게 피해를 줍니다.",
    "nl": "Breng schade toe aan alle vijanden op basis van het aantal afvallige volgelingen dat je hebt.",
    "pt-BR": "Cause dano a todos os inimigos com base na sua quantidade de Seguidores Rebeldes.",
    "ru": "Вы наносите врагам урон, зависящий от количества инакомыслящих последователей.",
    "tr": "Sahip olduğun Başkaldıran Takipçi sayısına bağlı olarak tüm düşmanlara hasar verir.",
    "zh-CN": "根据你的反教者人数对所有敌人造成伤害。",
    "zh-TW": "根據你的反教者人數對所有敵人造成傷害。"
  },
  "descriptionPlain": {
    "ar": "يمكن إلحاق الضرر بجميع الأعداء وفقًا لعدد أتباعك المعارضين.",
    "de": "Füge allen Gegnern entsprechend der Anzahl deiner abtrünnigen Anhänger Schaden zu.",
    "en": "Damage all enemies based on how many Dissenting Followers you have.",
    "es": "Inflige daño a todos los enemigos en función del número de adeptos desertores que tengas.",
    "fr": "Infligez des dégâts à tous les ennemis selon votre nombre d'adeptes rebelles.",
    "fr-CA": "Infligez des dégâts à tous les ennemis selon votre nombre d'adeptes rebelles.",
    "it": "Infligge danni a tutti i nemici in base al numero dei membri dissidenti del Culto.",
    "ja": "教団に所属している離反中の信者の人数に応じたダメージを敵全体に与える",
    "ko": "보유한 반목 중인 추종자들의 수에 비례해 모든 적에게 피해를 줍니다.",
    "nl": "Breng schade toe aan alle vijanden op basis van het aantal afvallige volgelingen dat je hebt.",
    "pt-BR": "Cause dano a todos os inimigos com base na sua quantidade de Seguidores Rebeldes.",
    "ru": "Вы наносите врагам урон, зависящий от количества инакомыслящих последователей.",
    "tr": "Sahip olduğun Başkaldıran Takipçi sayısına bağlı olarak tüm düşmanlara hasar verir.",
    "zh-CN": "根据你的反教者人数对所有敌人造成伤害。",
    "zh-TW": "根據你的反教者人數對所有敵人造成傷害。"
  },
  "dlc": false,
  "icon": "icons/relics/DealDamagePerFollower_Dammed.png",
  "id": "DealDamagePerFollower_Dammed",
  "interactionType": "Charging",
  "lore": {
    "ar": "من يجرؤون على التشكيك، سيُعاقبون.",
    "de": "Die Skeptiker werden aufgereiht.",
    "en": "Those who would question, be strung.",
    "es": "A quienes cuestionen, ensartadlos.",
    "fr": "Contestation est synonyme de pendaison.",
    "fr-CA": "Contestation est synonyme de pendaison.",
    "it": "Chi osa protestare, che venga mandato alla forca.",
    "ja": "我らが教団に疑問を持つ者よ、数珠繋ぎとなれ",
    "ko": "의문을 품는 자, 꿰이리라.",
    "nl": "Zij die vragen stellen, worden opgeknoopt.",
    "pt-BR": "Aqueles que questionam, sejam amarrados.",
    "ru": "Объединитесь, вопрошающие.",
    "tr": "Sorgulamaya cüret edenlerin sonu halattır.",
    "zh-CN": "质疑者啊，串连成线吧。",
    "zh-TW": "質疑者啊，串連成線吧。"
  },
  "majorDlc": false,
  "name": {
    "ar": "خرزات المعتزِل <color=#FD1D03>الملعونة</color>",
    "de": "<color=#FD1D03>Verdammte</color> Perlen des Einsiedlers",
    "en": "<color=#FD1D03>Damned</color> Beads of the Anchorite",
    "es": "Abalorios <color=#FD1D03>malditos</color> del ermitaño",
    "fr": "Perles de l'anachorète <color=#FD1D03>maudites</color>",
    "fr-CA": "Perles <color=#FD1D03>maudites</color> de l'anachorète",
    "it": "Rosario dell'anacoreta <color=#FD1D03>dannato</color>",
    "ja": "<color=#FD1D03>呪われた</color>隠者の数珠",
    "ko": "<color=#FD1D03>저주받은</color> 은자의 염주",
    "nl": "<color=#FD1D03>Verdoemde</color> kralen van de Anchoriet",
    "pt-BR": "Terço do Anacoreta <color=#FD1D03>Maldito</color>",
    "ru": "<color=#FD1D03>Проклятые</color> бусы аскета",
    "tr": "<color=#FD1D03>Lanetli</color> Münzevinin Tespihi",
    "zh-CN": "<color=#FD1D03>受诅咒的</color>隐修者念珠",
    "zh-TW": "<color=#FD1D03>受詛咒的</color>隱修者念珠"
  },
  "namePlain": {
    "ar": "خرزات المعتزِل الملعونة",
    "de": "Verdammte Perlen des Einsiedlers",
    "en": "Damned Beads of the Anchorite",
    "es": "Abalorios malditos del ermitaño",
    "fr": "Perles de l'anachorète maudites",
    "fr-CA": "Perles maudites de l'anachorète",
    "it": "Rosario dell'anacoreta dannato",
    "ja": "呪われた隠者の数珠",
    "ko": "저주받은 은자의 염주",
    "nl": "Verdoemde kralen van de Anchoriet",
    "pt-BR": "Terço do Anacoreta Maldito",
    "ru": "Проклятые бусы аскета",
    "tr": "Lanetli Münzevinin Tespihi",
    "zh-CN": "受诅咒的隐修者念珠",
    "zh-TW": "受詛咒的隱修者念珠"
  },
  "requiresCult": true,
  "subType": "Any",
  "thumb": "icons/relics/64/DealDamagePerFollower_Dammed.png",
  "unlockedBy": "Relics_Dammed_1",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/FreezeOnTouch_Familiar.json
{
  "chargeCategory": "Slow",
  "chargeDamage": 110.0,
  "coop": false,
  "damageType": "DealsDamage",
  "description": {
    "ar": "عيون تسير في مدارات وتجمد الأعداء حالما تلمسهم.",
    "de": "Umkreisende Augen, die Gegner bei Kontakt einfrieren.",
    "en": "Orbiting eyes that freezes enemies on contact.",
    "es": "Ojos en órbita que congelan a los enemigos que tocan.",
    "fr": "Des yeux gravitent et gèlent les ennemis au contact.",
    "fr-CA": "Des yeux qui gravitent et gèlent les ennemis qu'ils touchent.",
    "it": "Occhi orbitanti che congelano i nemici al contatto.",
    "ja": "触れた敵を凍結させる眼を召喚する",
    "ko": "눈이 떠돌며 닿는 적을 얼립니다.",
    "nl": "Rondcirkelende ogen die vijanden bij aanraking bevriezen.",
    "pt-BR": "Olhos em órbita que congelam os inimigos ao fazer contato.",
    "ru": "Вы призываете глаза, которые вращаются вокруг вас и замораживают врагов при столкновении.",
    "tr": "Çevrende dönen ve bir düşmana dokunduğunda donduran gözler.",
    "zh-CN": "不断绕行的眼球，碰触到敌人时使其冻结。",
    "zh-TW": "不斷繞行的眼球，碰觸到敵人時使其凍結。"
  },
  "descriptionPlain": {
    "ar": "عيون تسير في مدارات وتجمد الأعداء حالما تلمسهم.",
    "de": "Umkreisende Augen, die Gegner bei Kontakt einfrieren.",
    "en": "Orbiting eyes that freezes enemies on contact.",
    "es": "Ojos en órbita que congelan a los enemigos que tocan.",
    "fr": "Des yeux gravitent et gèlent les ennemis au contact.",
    "fr-CA": "Des yeux qui gravitent et gèlent les ennemis qu'ils touchent.",
    "it": "Occhi orbitanti che congelano i nemici al contatto.",
    "ja": "触れた敵を凍結させる眼を召喚する",
    "ko": "눈이 떠돌며 닿는 적을 얼립니다.",
    "nl": "Rondcirkelende ogen die vijanden bij aanraking bevriezen.",
    "pt-BR": "Olhos em órbita que congelam os inimigos ao fazer contato.",
    "ru": "Вы призываете глаза, которые вращаются вокруг вас и замораживают врагов при столкновении.",
    "tr": "Çevrende dönen ve bir düşmana dokunduğunda donduran gözler.",
    "zh-CN": "不断绕行的眼球，碰触到敌人时使其冻结。",
    "zh-TW": "不斷繞行的眼球，碰觸到敵人時使其凍結。"
  },
  "dlc": false,
  "icon": "icons/relics/FreezeOnTouch_Familiar.png",
  "id": "FreezeOnTouch_Familiar",
  "interactionType": "Fragile",
  "lore": {
    "ar": "نظرة شاخصة جامدة.",
    "de": "Ein eisiges Starren.",
    "en": "An icy stare.",
    "es": "Una mirada helada.",
    "fr": "Un regard qui glace le sang.",
    "fr-CA": "Un regard qui glace le sang.",
    "it": "Uno sguardo glaciale.",
    "ja": "凍り付くような視線を感じる",
    "ko": "차가운 눈길이다.",
    "nl": "Een kille oogopslag.",
    "pt-BR": "Um olhar congelante.",
    "ru": "Холод во взгляде.",
    "tr": "Buz gibi soğuk bakışlar.",
    "zh-CN": "冷冰冰的怒瞪。",
    "zh-TW": "冷冰冰的怒瞪。"
  },
  "majorDlc": false,
  "name": {
    "ar": "عين آيسغور",
    "de": "Auge des Eisblutes",
    "en": "Eye of the Icegore",
    "es": "Ojo de ogrizo",
    "fr": "Œil de Glasang",
    "fr-CA": "Œil de Glasang",
    "it": "Occhio del Gelofuria",
    "ja": "アイスゴアの眼",
    "ko": "아이스고어의 눈",
    "nl": "Oog van de IJsgoor",
    "pt-BR": "Olho do Sangue Congelado",
    "ru": "Глаз Йетира",
    "tr": "Buzyaman'ın Gözü",
    "zh-CN": "冰牴之眼",
    "zh-TW": "冰牴之眼"
  },
  "namePlain": {
    "ar": "عين آيسغور",
    "de": "Auge des Eisblutes",
    "en": "Eye of the Icegore",
    "es": "Ojo de ogrizo",
    "fr": "Œil de Glasang",
    "fr-CA": "Œil de Glasang",
    "it": "Occhio del Gelofuria",
    "ja": "アイスゴアの眼",
    "ko": "아이스고어의 눈",
    "nl": "Oog van de IJsgoor",
    "pt-BR": "Olho do Sangue Congelado",
    "ru": "Глаз Йетира",
    "tr": "Buzyaman'ın Gözü",
    "zh-CN": "冰牴之眼",
    "zh-TW": "冰牴之眼"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/FreezeOnTouch_Familiar.png",
  "unlockedBy": "Relic_Pack1",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/HeartConversion_Blessed.json
{
  "chargeCategory": "Fast",
  "chargeDamage": 30.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "يمكن تحويل القلوب الزرقاء إلى قلوب أرواح.",
    "de": "Verwandle blaue Herzen in Geisterherzen.",
    "en": "Convert Blue Hearts to Spirit Hearts.",
    "es": "Convierte los corazones azules en corazones fantasmas.",
    "fr": "Convertissez vos cœurs bleus en cœurs spirituels.",
    "fr-CA": "Convertissez vos cœurs bleus en cœurs spirituels.",
    "it": "Converte i cuori blu in cuori spirituali.",
    "ja": "ブルーハートをスピリットハートに変換する",
    "ko": "파란 심장을 영혼 심장으로 변화시킵니다.",
    "nl": "Zet blauwe harten om in spirituele harten.",
    "pt-BR": "Converte Corações Azuis em Corações Espirituais.",
    "ru": "Вы превращаете голубые сердца в эфемерные сердца.",
    "tr": "Mavi Kalpleri Ruh Kalplerine dönüştürür.",
    "zh-CN": "将蓝心化为灵心。",
    "zh-TW": "將藍心化為靈心。"
  },
  "descriptionPlain": {
    "ar": "يمكن تحويل القلوب الزرقاء إلى قلوب أرواح.",
    "de": "Verwandle blaue Herzen in Geisterherzen.",
    "en": "Convert Blue Hearts to Spirit Hearts.",
    "es": "Convierte los corazones azules en corazones fantasmas.",
    "fr": "Convertissez vos cœurs bleus en cœurs spirituels.",
    "fr-CA": "Convertissez vos cœurs bleus en cœurs spirituels.",
    "it": "Converte i cuori blu in cuori spirituali.",
    "ja": "ブルーハートをスピリットハートに変換する",
    "ko": "파란 심장을 영혼 심장으로 변화시킵니다.",
    "nl": "Zet blauwe harten om in spirituele harten.",
    "pt-BR": "Converte Corações Azuis em Corações Espirituais.",
    "ru": "Вы превращаете голубые сердца в эфемерные сердца.",
    "tr": "Mavi Kalpleri Ruh Kalplerine dönüştürür.",
    "zh-CN": "将蓝心化为灵心。",
    "zh-TW": "將藍心化為靈心。"
  },
  "dlc": false,
  "icon": "icons/relics/HeartConversion_Blessed.png",
  "id": "HeartConversion_Blessed",
  "interactionType": "Charging",
  "lore": {
    "ar": "ما الذي يدفع الأب دون عشيرة؟",
    "de": "Was treibt den Patriarchen ohne Clan an?",
    "en": "What drives the patriach without clan?",
    "es": "¿Qué guía al patriarca sin clan?",
    "fr": "Qu'est-ce qu'un patriarche sans son clan ?",
    "fr-CA": "Qu'est-ce qu'un patriarche sans son clan?",
    "it": "Cosa stimola un patriarca senza clan?",
    "ja": "部族なき族長を駆り立てるものとは何ぞ",
    "ko": "가족이 아니라면 무엇이 가장을 움직이게 하리요?",
    "nl": "Wat drijft de patriarch zonder clan?",
    "pt-BR": "O que motiva o patriarca sem um clã?",
    "ru": "Ради чего живёт вождь, лишившийся племени?",
    "tr": "Klanı olmayan bir reise yaşama isteği veren nedir?",
    "zh-CN": "没了族人的一族之长为何行动？",
    "zh-TW": "沒了族人的一族之長為何行動？"
  },
  "majorDlc": false,
  "name": {
    "ar": "الدموع <color=#03EAFD>المباركة</color> للأب الحاقد",
    "de": "<color=#03EAFD>Gesegnete</color> Tränen des rachsüchtigen Vaters",
    "en": "<color=#03EAFD>Blessed</color> Tears of the Vengeful Father",
    "es": "Lágrimas <color=#03EAFD>bendecidas</color> de la madre misericordiosa",
    "fr": "Larmes du père vengeur <color=#03EAFD>bénies</color>",
    "fr-CA": "Larmes <color=#03EAFD>bénies</color> du père vengeur",
    "it": "Lacrime del padre vendicativo",
    "ja": "<color=#03EAFD>祝福された</color>執念深き父の涙",
    "ko": "<color=#03EAFD>축복받은</color> 복수심에 불타는 아비의 눈물",
    "nl": "<color=#03EAFD>Gezegende</color> tranen van de wraakzuchtige vader",
    "pt-BR": "Lágrimas <color=#03EAFD>Abençoadas</color> do Pai Vingativo",
    "ru": "<color=#03EAFD>Священные</color> слёзы мстительного отца",
    "tr": "<color=#03EAFD>Kutsanmış</color> İntikamcı Babanın Gözyaşları",
    "zh-CN": "<color=#03EAFD>受祝福的</color>复仇父亲之泪",
    "zh-TW": "<color=#03EAFD>受祝福的</color>復仇父親之淚"
  },
  "namePlain": {
    "ar": "الدموع المباركة للأب الحاقد",
    "de": "Gesegnete Tränen des rachsüchtigen Vaters",
    "en": "Blessed Tears of the Vengeful Father",
    "es": "Lágrimas bendecidas de la madre misericordiosa",
    "fr": "Larmes du père vengeur bénies",
    "fr-CA": "Larmes bénies du père vengeur",
    "it": "Lacrime del padre vendicativo",
    "ja": "祝福された執念深き父の涙",
    "ko": "축복받은 복수심에 불타는 아비의 눈물",
    "nl": "Gezegende tranen van de wraakzuchtige vader",
    "pt-BR": "Lágrimas Abençoadas do Pai Vingativo",
    "ru": "Священные слёзы мстительного отца",
    "tr": "Kutsanmış İntikamcı Babanın Gözyaşları",
    "zh-CN": "受祝福的复仇父亲之泪",
    "zh-TW": "受祝福的復仇父親之淚"
  },
  "requiresCult": false,
  "subType": "Blessed",
  "thumb": "icons/relics/64/HeartConversion_Blessed.png",
  "unlockedBy": "Building_LightningRod",
  "weight": 1.0
}

=== AuthFailed/cotl-api/site/v1/relics/DestroyTarotGainBuff_Dammed.json
{
  "chargeCategory": "Fast",
  "chargeDamage": 40.0,
  "coop": false,
  "damageType": "NoDamage",
  "description": {
    "ar": "يمكن تدمير جميع بطاقات التارو النشطة. ستعطي كل بطاقة مدمَّرة نصف قلب فاسد.",
    "de": "Zerstöre alle aktiven Tarotkarten. Jede zerstörte Karte gewährt dir ein halbes krankes Herz.",
    "en": "Destroy all active Tarot Cards. Each destroyed card will give half a Diseased Heart.",
    "es": "Destruye todas las cartas del tarot activas. Cada carta destruida otorga medio corazón enfermo.",
    "fr": "Détruisez toutes vos cartes de tarot actives. Chaque carte détruite vous octroie la moitié d'un cœur corrompu.",
    "fr-CA": "Détruisez toutes vos cartes de tarot actives. Chaque carte détruite vous octroie la moitié d'un cœur corrompu.",
    "it": "Distrugge tutti i tarocchi attivi. Ogni carta infranta fornisce mezzo cuore afflitto.",
    "ja": "タロットカードすべてを破壊する。破壊したタロット1枚につき半分の病みし心臓を獲得する",
    "ko": "모든 활성 중인 타로 카드를 파괴합니다. 파괴된 카드 한 장 당 병든 심장 반쪽을 얻습니다.",
    "nl": "Vernietig alle actieve tarotkaarten. Elke vernietigde kaart geeft je een half ziekelijk hart.",
    "pt-BR": "Destrói todas as Cartas de Tarô ativas. Cada carta destruída dará meio coração doente.",
    "ru": "Вы уничтожаете все полученные карты Таро и получаете по половине больного сердца за каждую.",
    "tr": "Tüm etkin Tarot Kartlarını yok eder. Yok edilen her kart yarım Çürümüş Kalp kazandırır.",
    "zh-CN": "摧毁所有生效的塔罗牌，每摧毁一张牌就获得半颗病缠黑心。",
    "zh-TW": "摧毀所有生效的塔羅牌，每摧毀一張牌就獲得半顆病纏黑心。"
  },
  "descriptionPlain": {
    "ar": "يمكن تدمير جميع بطاقات التارو النشطة. ستعطي كل بطاقة مدمَّرة نصف قلب فاسد.",
    "de": "Zerstöre alle aktiven Tarotkarten. Jede zerstörte Karte gewährt dir ein halbes krankes Herz.",
    "en": "Destroy all active Tarot Cards. Each destroyed card will give half a Diseased Heart.",
    "es": "Destruye todas las cartas del tarot activas. Cada carta destruida otorga medio corazón enfermo.",
    "fr": "Détruisez toutes vos cartes de tarot actives. Chaque carte détruite vous octroie la moitié d'un cœur corrompu.",
    "fr-CA": "Détruisez toutes vos cartes de tarot actives. Chaque carte détruite vous octroie la moitié d'un cœur corrompu.",
    "it": "Distrugge tutti i tarocchi attivi. Ogni carta infranta fornisce mezzo cuore afflitto.",
    "ja": "タロットカードすべてを破壊する。破壊したタロット1枚につき半分の病みし心臓を獲得する",
    "ko": "모든 활성 중인 타로 카드를 파괴합니다. 파괴된 카드 한 장 당 병든 심장 반쪽을 얻습니다.",
    "nl": "Vernietig alle actieve tarotkaarten. Elke vernietigde kaart geeft je een half ziekelijk hart.",
    "pt-BR": "Destrói todas as Cartas de Tarô ativas. Cada carta destruída dará meio coração doente.",
    "ru": "Вы уничтожаете все полученные карты Таро и получаете по половине больного сердца за каждую.",
    "tr": "Tüm etkin Tarot Kartlarını yok eder. Yok edilen her kart yarım Çürümüş Kalp kazandırır.",
    "zh-CN": "摧毁所有生效的塔罗牌，每摧毁一张牌就获得半颗病缠黑心。",
    "zh-TW": "摧毀所有生效的塔羅牌，每摧毀一張牌就獲得半顆病纏黑心。"
  },
  "dlc": false,
  "icon": "icons/relics/DestroyTarotGainBuff_Dammed.png",
  "id": "DestroyTarotGainBuff_Dammed",
  "interactionType": "Fragile",
  "lore": {
    "ar": "يا جروح الماضي، أعينيني في الحاضر.",
    "de": "Qual der Vergangenheit, diene mir in der Gegenwart.",
    "en": "Agony of the past, serve me in present.",
    "es": "Agonía pasada, sírveme en el presente.",
    "fr": "Agonie du passé, aide-moi aujourd'hui.",
    "fr-CA": "Agonie du passé, aide-moi aujourd'hui.",
    "it": "Agonia del passato, servimi nel presente.",
    "ja": "過去の苦痛よ、今の我に力を",
    "ko": "과거의 고통은, 현재의 나를 섬긴다.",
    "nl": "Kwelling van het verleden, dien me in het heden.",
    "pt-BR": "Agonia do passado, sirva-me no presente.",
    "ru": "Муки прошлого, станьте подспорьем в настоящем.",
    "tr": "Geçmişin ızdırabı, bana şimdi lazımsın.",
    "zh-CN": "过去的煎熬啊，现在服侍我吧。",
    "zh-TW": "過去的煎熬啊，現在服侍我吧。"
  },
  "majorDlc": false,
  "name": {
    "ar": "مرآة كلاونيك <color=#FD1D03>الملعونة</color>",
    "de": "Claunecks <color=#FD1D03>verdammter</color> Spiegel",
    "en": "<color=#FD1D03>Damned</color> Clauneck's Mirror",
    "es": "Espejo <color=#FD1D03>maldito</color> de Clauneck",
    "fr": "Miroir de Clauneck <color=#FD1D03>maudit</color>",
    "fr-CA": "Miroir <color=#FD1D03>maudit</color> de Clauneck",
    "it": "Specchio di Clauneck <color=#FD1D03>dannato</color>",
    "ja": "<color=#FD1D03>呪われた</color>クラウネックの鏡",
    "ko": "<color=#FD1D03>저주받은</color> 클라우넥의 거울",
    "nl": "<color=#FD1D03>Verdoemde</color> Claunecks spiegel",
    "pt-BR": "Espelho de Clauneck <color=#FD1D03>Maldito</color>",
    "ru": "<color=#FD1D03>Проклятое</color> зеркало Клонека",
    "tr": "<color=#FD1D03>Lanetli</color> Clauneck'in Aynası",
    "zh-CN": "<color=#FD1D03>受诅咒的</color>克劳内克之镜",
    "zh-TW": "<color=#FD1D03>受詛咒的</color>克勞涅克之鏡"
  },
  "namePlain": {
    "ar": "مرآة كلاونيك الملعونة",
    "de": "Claunecks verdammter Spiegel",
    "en": "Damned Clauneck's Mirror",
    "es": "Espejo maldito de Clauneck",
    "fr": "Miroir de Clauneck maudit",
    "fr-CA": "Miroir maudit de Clauneck",
    "it": "Specchio di Clauneck dannato",
    "ja": "呪われたクラウネックの鏡",
    "ko": "저주받은 클라우넥의 거울",
    "nl": "Verdoemde Claunecks spiegel",
    "pt-BR": "Espelho de Clauneck Maldito",
    "ru": "Проклятое зеркало Клонека",
    "tr": "Lanetli Clauneck'in Aynası",
    "zh-CN": "受诅咒的克劳内克之镜",
    "zh-TW": "受詛咒的克勞涅克之鏡"
  },
  "requiresCult": false,
  "subType": "Any",
  "thumb": "icons/relics/64/DestroyTarotGainBuff_Dammed.png",
  "unlockedBy": "Relics_Dammed_1",
  "weight": 1.0
}
