=== AuthFailed/cotl-api/site/v1/schema/curse.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Curse",
  "type": "object",
  "required": [
    "id",
    "name",
    "description",
    "namePlain",
    "descriptionPlain",
    "icon",
    "thumb",
    "lore",
    "family",
    "damage",
    "delay",
    "castingDuration",
    "chance",
    "canAim"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]+$"
    },
    "name": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      },
      "required": [
        "en"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "namePlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "name without the game's text markup"
    },
    "descriptionPlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "description without the game's text markup"
    },
    "icon": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/curses/[A-Za-z0-9_-]+\\.png$"
    },
    "thumb": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/curses/64/[A-Za-z0-9_-]+\\.png$"
    },
    "lore": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "family": {
      "type": [
        "string",
        "null"
      ],
      "description": "Tentacles, EnemyBlast, ProjectileAOE, Fireball, MegaSlash, Teleport, Barrier"
    },
    "damage": {
      "type": "number",
      "description": ""
    },
    "delay": {
      "type": "number",
      "description": ""
    },
    "castingDuration": {
      "type": "number",
      "description": ""
    },
    "chance": {
      "type": "number",
      "description": ""
    },
    "canAim": {
      "type": "boolean",
      "description": ""
    }
  }
}

=== AuthFailed/cotl-api/site/v1/curses/Tentacles_Flame.json
{
  "canAim": true,
  "castingDuration": 0.5,
  "chance": 1.0,
  "damage": 1.5,
  "delay": 0.5,
  "description": {
    "ar": "ثوران من أعمدة مشتعلة <color=#f79502>تحرق</color> الأعداء عند تلقي ضربة.",
    "de": "Hervorbrechende Flammensäulen, die getroffene Gegner <color=#f79502>verbrennen</color>.",
    "en": "An eruption of flaming pillars that <color=#f79502>burns</color> enemies on hit.",
    "es": "Una erupción de pilares de fuego que <color=#f79502>queman</color> a los enemigos que golpean.",
    "fr": "Des piliers de flammes qui <color=#f79502>brûlent</color> les ennemis.",
    "fr-CA": "Des piliers de flammes qui <color=#f79502>brûlent</color> les ennemis.",
    "it": "Un'eruzione di colonne infuocate che <color=#f79502>incendiano</color> i nemici al tocco.",
    "ja": "炎の柱を地面から召喚し、命中した敵を<color=#f79502>炎上</color>状態にする。",
    "ko": "적들을 맞출 시 <color=#f79502>불태워 버리는</color> 불기둥을 분출시킵니다.",
    "nl": "Een uitbarsting van brandende pilaren die vijanden <color=#f79502>verbrandt</color> wanneer je ze raakt.",
    "pt-BR": "Uma erupção de pilares de fogo que <color=#f79502>queima</color> os inimigos ao acertá-los.",
    "ru": "Вы поднимаете из земли столпы пламени, которые <color=#f79502>поджигают</color> задетых врагов.",
    "tr": "Düşmanları isabet hâlinde <color=#f79502>yakan</color> bir alev sütunu patlaması.",
    "zh-CN": "猛烈迸发出火柱，击中敌人时使敌人<color=#f79502>燃烧</color>。",
    "zh-TW": "猛烈迸發出火柱，擊中敵人時使敵人<color=#f79502>燃燒</color>。"
  },
  "descriptionPlain": {
    "ar": "ثوران من أعمدة مشتعلة تحرق الأعداء عند تلقي ضربة.",
    "de": "Hervorbrechende Flammensäulen, die getroffene Gegner verbrennen.",
    "en": "An eruption of flaming pillars that burns enemies on hit.",
    "es": "Una erupción de pilares de fuego que queman a los enemigos que golpean.",
    "fr": "Des piliers de flammes qui brûlent les ennemis.",
    "fr-CA": "Des piliers de flammes qui brûlent les ennemis.",
    "it": "Un'eruzione di colonne infuocate che incendiano i nemici al tocco.",
    "ja": "炎の柱を地面から召喚し、命中した敵を炎上状態にする。",
    "ko": "적들을 맞출 시 불태워 버리는 불기둥을 분출시킵니다.",
    "nl": "Een uitbarsting van brandende pilaren die vijanden verbrandt wanneer je ze raakt.",
    "pt-BR": "Uma erupção de pilares de fogo que queima os inimigos ao acertá-los.",
    "ru": "Вы поднимаете из земли столпы пламени, которые поджигают задетых врагов.",
    "tr": "Düşmanları isabet hâlinde yakan bir alev sütunu patlaması.",
    "zh-CN": "猛烈迸发出火柱，击中敌人时使敌人燃烧。",
    "zh-TW": "猛烈迸發出火柱，擊中敵人時使敵人燃燒。"
  },
  "family": "Tentacles",
  "icon": "icons/curses/Tentacles_Flame.png",
  "id": "Tentacles_Flame",
  "lore": {
    "ar": "سلف الجفاف العظيم.",
    "de": "Vorläufer der großen Dürre.",
    "en": "Predecessor to the Great Drought.",
    "es": "Predecesor de la Gran Sequía.",
    "fr": "Prédécesseur de la grande sécheresse.",
    "fr-CA": "Prédécesseur de la grande sécheresse.",
    "it": "Il precursore della Grande Siccità.",
    "ja": "大干ばつをもたらしたもの。",
    "ko": "대가뭄의 전조.",
    "nl": "Voorganger van de grote droogte.",
    "pt-BR": "Antecedente da Grande Seca.",
    "ru": "Грядёт великая засуха.",
    "tr": "Büyük Kuraklık'ın sebebi.",
    "zh-CN": "大旱灾的原身。",
    "zh-TW": "大旱災的原身。"
  },
  "name": {
    "ar": "لمسة ييغ",
    "de": "Yigs Berührung",
    "en": "Touch of Yig",
    "es": "Toque de Yig",
    "fr": "Souvenir de Yig",
    "fr-CA": "Souvenir de Yig",
    "it": "Tocco di Yig",
    "ja": "イグの御手",
    "ko": "이그의 손길",
    "nl": "Aanraking van Yig",
    "pt-BR": "Toque de Yig",
    "ru": "Касание Йига",
    "tr": "Yig'in Dokunuşu",
    "zh-CN": "伊格之触",
    "zh-TW": "伊格之觸"
  },
  "namePlain": {
    "ar": "لمسة ييغ",
    "de": "Yigs Berührung",
    "en": "Touch of Yig",
    "es": "Toque de Yig",
    "fr": "Souvenir de Yig",
    "fr-CA": "Souvenir de Yig",
    "it": "Tocco di Yig",
    "ja": "イグの御手",
    "ko": "이그의 손길",
    "nl": "Aanraking van Yig",
    "pt-BR": "Toque de Yig",
    "ru": "Касание Йига",
    "tr": "Yig'in Dokunuşu",
    "zh-CN": "伊格之触",
    "zh-TW": "伊格之觸"
  },
  "thumb": "icons/curses/64/Tentacles_Flame.png"
}

=== AuthFailed/cotl-api/site/v1/curses/Fireball_Swarm.json
{
  "canAim": true,
  "castingDuration": 0.5,
  "chance": 1.0,
  "damage": 1.0,
  "delay": 0.5,
  "description": {
    "ar": "تطلق عدة قذائف تستهدف الأعداء.",
    "de": "Verschießt mehrere Projektile, die Gegner verfolgen.",
    "en": "Shoots multiple projectiles that seek out enemies.",
    "es": "Dispara varios proyectiles que persiguen a los enemigos.",
    "fr": "Tire plusieurs projectiles qui pourchassent les ennemis.",
    "fr-CA": "Tire plusieurs projectiles qui pourchassent les ennemis.",
    "it": "Spara molteplici proiettili che cercano i nemici.",
    "ja": "敵を追跡する弾を複数射出する。",
    "ko": "적들을 찾아다니는 투사체를 다수 발사합니다.",
    "nl": "Schiet meerdere projectielen af die automatisch op vijanden afgaan.",
    "pt-BR": "Dispara diversos projéteis que procuram inimigos.",
    "ru": "Вы выпускаете множество снарядов, наводящихся на врагов.",
    "tr": "Düşmanları takip eden birden fazla menzilli saldırı yapar.",
    "zh-CN": "射出追踪敌人的数个投射物。",
    "zh-TW": "射出追蹤敵人的數個投射物。"
  },
  "descriptionPlain": {
    "ar": "تطلق عدة قذائف تستهدف الأعداء.",
    "de": "Verschießt mehrere Projektile, die Gegner verfolgen.",
    "en": "Shoots multiple projectiles that seek out enemies.",
    "es": "Dispara varios proyectiles que persiguen a los enemigos.",
    "fr": "Tire plusieurs projectiles qui pourchassent les ennemis.",
    "fr-CA": "Tire plusieurs projectiles qui pourchassent les ennemis.",
    "it": "Spara molteplici proiettili che cercano i nemici.",
    "ja": "敵を追跡する弾を複数射出する。",
    "ko": "적들을 찾아다니는 투사체를 다수 발사합니다.",
    "nl": "Schiet meerdere projectielen af die automatisch op vijanden afgaan.",
    "pt-BR": "Dispara diversos projéteis que procuram inimigos.",
    "ru": "Вы выпускаете множество снарядов, наводящихся на врагов.",
    "tr": "Düşmanları takip eden birden fazla menzilli saldırı yapar.",
    "zh-CN": "射出追踪敌人的数个投射物。",
    "zh-TW": "射出追蹤敵人的數個投射物。"
  },
  "family": "Fireball",
  "icon": "icons/curses/Fireball_Swarm.png",
  "id": "Fireball_Swarm",
  "lore": {
    "ar": "تبحث عمن يجرؤون على الشك وتضربهم.",
    "de": "Jage all jene, die es wagen, zu zweifeln.",
    "en": "Seek and strike those who dare doubt.",
    "es": "Busca y castiga a aquellos invadidos por la duda.",
    "fr": "Traquez et punissez les mécréants.",
    "fr-CA": "Traquez et punissez les mécréants.",
    "it": "Cerca e colpisci chiunque osi dubitare.",
    "ja": "愚かにも疑う者を見つけ出し、迫害せよ。",
    "ko": "감히 의심하는 자들을 찾아 공격한다.",
    "nl": "Zoek hen die twijfelen en sla ze neer.",
    "pt-BR": "Procuram e acertam aqueles que ousam duvidar.",
    "ru": "Ищите и карайте тех, кто смеет сомневаться.",
    "tr": "Hikmetinden sual edenleri cezalandır.",
    "zh-CN": "找出胆敢质疑者并加以打击。",
    "zh-TW": "找出膽敢質疑者並加以打擊。"
  },
  "name": {
    "ar": "ملاحقة القدر",
    "de": "Hunde des Schicksals",
    "en": "Hounds of Fate",
    "es": "Sabuesos del destino",
    "fr": "Traque mortelle",
    "fr-CA": "Traque mortelle",
    "it": "Segugi del fato",
    "ja": "運命の猟犬",
    "ko": "운명의 사냥개",
    "nl": "Helhonden van het lot",
    "pt-BR": "Caçadores do Destino",
    "ru": "Псы рока",
    "tr": "Kaderin Tazıları",
    "zh-CN": "命运猎犬",
    "zh-TW": "命運獵犬"
  },
  "namePlain": {
    "ar": "ملاحقة القدر",
    "de": "Hunde des Schicksals",
    "en": "Hounds of Fate",
    "es": "Sabuesos del destino",
    "fr": "Traque mortelle",
    "fr-CA": "Traque mortelle",
    "it": "Segugi del fato",
    "ja": "運命の猟犬",
    "ko": "운명의 사냥개",
    "nl": "Helhonden van het lot",
    "pt-BR": "Caçadores do Destino",
    "ru": "Псы рока",
    "tr": "Kaderin Tazıları",
    "zh-CN": "命运猎犬",
    "zh-TW": "命運獵犬"
  },
  "thumb": "icons/curses/64/Fireball_Swarm.png"
}

=== AuthFailed/cotl-api/site/v1/curses/Fireball.json
{
  "canAim": true,
  "castingDuration": 0.5,
  "chance": 1.0,
  "damage": 2.5,
  "delay": 0.5,
  "description": {
    "ar": "تطلق صاعقة نارية خارقة. عليك الضغط باستمرار والإفلات على العلامة لجعلها متفجرة.",
    "de": "Feuere einen durchdringenden Feuerbolzen ab. Halte die Taste gedrückt und lass sie beim Ziel los, um ihn explodieren zu lassen.",
    "en": "Shoot a piercing bolt of fire. Hold and release at the mark to make it explosive.",
    "es": "Dispara un rayo de fuego desgarrador. Mantén pulsado y suelta a la señal para convertirlo en explosivo.",
    "fr": "Tire un éclair de feu aveuglant. Maintenez et relâchez à la marque pour créer une explosion.",
    "fr-CA": "Tire un éclair de feu aveuglant. Maintenez et relâchez à la marque pour créer une explosion.",
    "it": "Lancia un dardo perforante di fuoco. Tieni premuto e rilascia sull'indicatore per farlo esplodere.",
    "ja": "炎の塊で敵を貫く。長押し後にタイミングよくボタンを離すと魔弾が爆発する。",
    "ko": "화염으로 된 꿰뚫는 화살을 하나 발사합니다. 표식에 대고 유지하다가 놓을 시 폭발시킬 수 있습니다.",
    "nl": "Deel een vurige klap uit. Houd vast om te richten en laat los op je doelwit om het te laten exploderen.",
    "pt-BR": "Dispare um raio de fogo perfurante. Segure e solte quando chegar na marca para torná-lo explosivo.",
    "ru": "Вы выпускаете огненный снаряд, проходящий сквозь врагов. Зажав кнопку и отпустив её на отметке, вы сделаете его взрывным.",
    "tr": "Deşip geçen bir ateş topu fırlatır. Ateş topunu patlatmak için hedefe göndermeden önce basılı tut.",
    "zh-CN": "射出一颗火球穿刺敌人。紧按后在标记处抓准时机放开，能让火球爆炸。",
    "zh-TW": "射出一顆火球穿刺敵人。在標記處投出，能讓火球爆炸。"
  },
  "descriptionPlain": {
    "ar": "تطلق صاعقة نارية خارقة. عليك الضغط باستمرار والإفلات على العلامة لجعلها متفجرة.",
    "de": "Feuere einen durchdringenden Feuerbolzen ab. Halte die Taste gedrückt und lass sie beim Ziel los, um ihn explodieren zu lassen.",
    "en": "Shoot a piercing bolt of fire. Hold and release at the mark to make it explosive.",
    "es": "Dispara un rayo de fuego desgarrador. Mantén pulsado y suelta a la señal para convertirlo en explosivo.",
    "fr": "Tire un éclair de feu aveuglant. Maintenez et relâchez à la marque pour créer une explosion.",
    "fr-CA": "Tire un éclair de feu aveuglant. Maintenez et relâchez à la marque pour créer une explosion.",
    "it": "Lancia un dardo perforante di fuoco. Tieni premuto e rilascia sull'indicatore per farlo esplodere.",
    "ja": "炎の塊で敵を貫く。長押し後にタイミングよくボタンを離すと魔弾が爆発する。",
    "ko": "화염으로 된 꿰뚫는 화살을 하나 발사합니다. 표식에 대고 유지하다가 놓을 시 폭발시킬 수 있습니다.",
    "nl": "Deel een vurige klap uit. Houd vast om te richten en laat los op je doelwit om het te laten exploderen.",
    "pt-BR": "Dispare um raio de fogo perfurante. Segure e solte quando chegar na marca para torná-lo explosivo.",
    "ru": "Вы выпускаете огненный снаряд, проходящий сквозь врагов. Зажав кнопку и отпустив её на отметке, вы сделаете его взрывным.",
    "tr": "Deşip geçen bir ateş topu fırlatır. Ateş topunu patlatmak için hedefe göndermeden önce basılı tut.",
    "zh-CN": "射出一颗火球穿刺敌人。紧按后在标记处抓准时机放开，能让火球爆炸。",
    "zh-TW": "射出一顆火球穿刺敵人。在標記處投出，能讓火球爆炸。"
  },
  "family": "Fireball",
  "icon": "icons/curses/Fireball.png",
  "id": "Fireball",
  "lore": {
    "ar": "تطلق ألسنة لهب العالم السفلي.",
    "de": "Entfessele die Flammen der Unterwelt.",
    "en": "Send forth the flames of the Underworld.",
    "es": "Lanza hacia delante las llamas del Inframundo.",
    "fr": "Invoque les flammes des enfers.",
    "fr-CA": "Invoque les flammes des enfers.",
    "it": "Fai divampare le fiamme degli Inferi.",
    "ja": "冥界の炎を射出せよ。",
    "ko": "저승의 화염을 앞으로 발사한다.",
    "nl": "Wakker de vlammen van de onderwereld aan.",
    "pt-BR": "Invoque as chamas do Submundo.",
    "ru": "Пламя мира мёртвых очистит мир смертных.",
    "tr": "Cehennem ateşlerine hükmet.",
    "zh-CN": "放射出冥界的火焰。",
    "zh-TW": "放射出冥界的火焰。"
  },
  "name": {
    "ar": "الطلقة المشتعلة",
    "de": "Flammenschuss",
    "en": "Flaming Shot",
    "es": "Disparo flameante",
    "fr": "Tir de feu",
    "fr-CA": "Tir de feu",
    "it": "Colpo infuocato",
    "ja": "炎の魔弾",
    "ko": "불타는 사격",
    "nl": "Vlammend schot",
    "pt-BR": "Tiro Flamejante",
    "ru": "Пылающий выстрел",
    "tr": "Ateş Topu",
    "zh-CN": "烈焰弹",
    "zh-TW": "烈焰彈"
  },
  "namePlain": {
    "ar": "الطلقة المشتعلة",
    "de": "Flammenschuss",
    "en": "Flaming Shot",
    "es": "Disparo flameante",
    "fr": "Tir de feu",
    "fr-CA": "Tir de feu",
    "it": "Colpo infuocato",
    "ja": "炎の魔弾",
    "ko": "불타는 사격",
    "nl": "Vlammend schot",
    "pt-BR": "Tiro Flamejante",
    "ru": "Пылающий выстрел",
    "tr": "Ateş Topu",
    "zh-CN": "烈焰弹",
    "zh-TW": "烈焰彈"
  },
  "thumb": "icons/curses/64/Fireball.png"
}

=== AuthFailed/cotl-api/site/v1/curses/Tentacles_Ice.json
{
  "canAim": true,
  "castingDuration": 0.5,
  "chance": 1.0,
  "damage": 1.5,
  "delay": 0.5,
  "description": {
    "ar": "ثوران من أعمدة ثلجية <color=#70F7FF>تجمد</color> الأعداء عند تلقي ضربة.",
    "de": "Hervorbrechende Eissäulen, die getroffene Gegner <color=#70F7FF>einfrieren</color>.",
    "en": "An eruption of ice pillars that <color=#70F7FF>freezes</color> enemies on hit.",
    "es": "Una erupción de pilares de hielo que <color=#70F7FF>congelan</color> a los enemigos que golpeen.",
    "fr": "Des piliers de glace qui <color=#70F7FF>gèlent</color> les ennemis.",
    "fr-CA": "Des piliers de glace qui <color=#70F7FF>gèlent</color> les ennemis.",
    "it": "Un'eruzione di stalattiti che <color=#70F7FF>congelano</color> i nemici al tocco.",
    "ja": "氷の柱を地面から召喚し、命中した敵を<color=#70F7FF>凍結</color>させる。",
    "ko": "적들을 맞출 시 <color=#70F7FF>얼려버리는</color> 얼음 기둥을 분출시킵니다.",
    "nl": "Een uitbarsting van ijspilaren die vijanden <color=#70F7FF>bevriest</color> wanneer je ze raakt.",
    "pt-BR": "Uma erupção de pilares de gelo que <color=#70F7FF>congela</color> os inimigos ao acertá-los.",
    "ru": "Вы поднимаете из земли ледяные глыбы, которые <color=#70F7FF>замораживают</color> задетых врагов.",
    "tr": "Düşmanları isabet hâlinde <color=#70F7FF>donduran</color> bir buz sütunu patlaması.",
    "zh-CN": "猛烈迸发出冰柱，击中敌人时<color=#70F7FF>冻结</color>敌人",
    "zh-TW": "猛烈迸發出冰柱，擊中敵人時<color=#70F7FF>凍結</color>敵人"
  },
  "descriptionPlain": {
    "ar": "ثوران من أعمدة ثلجية تجمد الأعداء عند تلقي ضربة.",
    "de": "Hervorbrechende Eissäulen, die getroffene Gegner einfrieren.",
    "en": "An eruption of ice pillars that freezes enemies on hit.",
    "es": "Una erupción de pilares de hielo que congelan a los enemigos que golpeen.",
    "fr": "Des piliers de glace qui gèlent les ennemis.",
    "fr-CA": "Des piliers de glace qui gèlent les ennemis.",
    "it": "Un'eruzione di stalattiti che congelano i nemici al tocco.",
    "ja": "氷の柱を地面から召喚し、命中した敵を凍結させる。",
    "ko": "적들을 맞출 시 얼려버리는 얼음 기둥을 분출시킵니다.",
    "nl": "Een uitbarsting van ijspilaren die vijanden bevriest wanneer je ze raakt.",
    "pt-BR": "Uma erupção de pilares de gelo que congela os inimigos ao acertá-los.",
    "ru": "Вы поднимаете из земли ледяные глыбы, которые замораживают задетых врагов.",
    "tr": "Düşmanları isabet hâlinde donduran bir buz sütunu patlaması.",
    "zh-CN": "猛烈迸发出冰柱，击中敌人时冻结敌人",
    "zh-TW": "猛烈迸發出冰柱，擊中敵人時凍結敵人"
  },
  "family": "Tentacles",
  "icon": "icons/curses/Tentacles_Ice.png",
  "id": "Tentacles_Ice",
  "lore": {
    "ar": "نداء من العالم السفلي ببدء العام الشتوي.",
    "de": "Ein Ruf aus der Tiefe, mit dem das Winterjahr begann.",
    "en": "A call from below that began the Winter Year.",
    "es": "Una llamada de las profundidades que da comienzo al año invernal.",
    "fr": "Un appel des enfers qui créa l'année hivernale.",
    "fr-CA": "Un appel des enfers qui amorça l'année hivernale.",
    "it": "Un appello dalle profondità che diede inizio all'Anno glaciale.",
    "ja": "地中からのその呼び声は、氷河期の幕開けをもたらした。",
    "ko": "겨울을 시작하게 한 아래에서의 부름이다.",
    "nl": "Een kreet van onder de aarde waarmee het winterjaar begon.",
    "pt-BR": "Um chamado lá de baixo que dá início ao Ano de Inverno.",
    "ru": "Зов из глубин дал начало году снегов.",
    "tr": "Yer altından gelen, Kış Yılı'nı başlatan çağrı.",
    "zh-CN": "开启严冬之年的下界呼唤。",
    "zh-TW": "開啟嚴冬之年的下界呼喚。"
  },
  "name": {
    "ar": "لمسة وحش الجليد",
    "de": "Ithaquas Berührung",
    "en": "Touch of Ithaqua",
    "es": "Toque de Ithaqua",
    "fr": "Souvenir d'Itaqua",
    "fr-CA": "Souvenir d'Itaqua",
    "it": "Tocco di Ithaqua",
    "ja": "イタクァの御手",
    "ko": "이타콰의 손길",
    "nl": "Aanraking van Ithaqua",
    "pt-BR": "Toque de Ithaqua",
    "ru": "Касание Итакуа",
    "tr": "Ithaqua'nın Dokunuşu",
    "zh-CN": "伊塔库亚之触",
    "zh-TW": "伊塔庫亞之觸"
  },
  "namePlain": {
    "ar": "لمسة وحش الجليد",
    "de": "Ithaquas Berührung",
    "en": "Touch of Ithaqua",
    "es": "Toque de Ithaqua",
    "fr": "Souvenir d'Itaqua",
    "fr-CA": "Souvenir d'Itaqua",
    "it": "Tocco di Ithaqua",
    "ja": "イタクァの御手",
    "ko": "이타콰의 손길",
    "nl": "Aanraking van Ithaqua",
    "pt-BR": "Toque de Ithaqua",
    "ru": "Касание Итакуа",
    "tr": "Ithaqua'nın Dokunuşu",
    "zh-CN": "伊塔库亚之触",
    "zh-TW": "伊塔庫亞之觸"
  },
  "thumb": "icons/curses/64/Tentacles_Ice.png"
}

=== AuthFailed/cotl-api/site/v1/curses/Fireball_Triple.json
{
  "canAim": true,
  "castingDuration": 0.5,
  "chance": 1.0,
  "damage": 2.0,
  "delay": 0.5,
  "description": {
    "ar": "تطلق ثلاث قذائف دفعة واحدة.",
    "de": "Verschießt drei Projektile gleichzeitig.",
    "en": "Shoots three projectiles at once.",
    "es": "Dispara tres proyectiles a la vez.",
    "fr": "Tire trois projectiles à la fois.",
    "fr-CA": "Tire trois projectiles à la fois.",
    "it": "Spara tre proiettili contemporaneamente.",
    "ja": "1度に3つの弾を射出する。",
    "ko": "한 번에 세 개의 투사체를 발사합니다.",
    "nl": "Schiet tegelijk drie projectielen af.",
    "pt-BR": "Dispara três projéteis de uma vez só.",
    "ru": "Вы выпускаете три снаряда за раз.",
    "tr": "Aynı anda üç menzilli saldırı yapar.",
    "zh-CN": "一次射出三个投射物。",
    "zh-TW": "一次射出三個投射物。"
  },
  "descriptionPlain": {
    "ar": "تطلق ثلاث قذائف دفعة واحدة.",
    "de": "Verschießt drei Projektile gleichzeitig.",
    "en": "Shoots three projectiles at once.",
    "es": "Dispara tres proyectiles a la vez.",
    "fr": "Tire trois projectiles à la fois.",
    "fr-CA": "Tire trois projectiles à la fois.",
    "it": "Spara tre proiettili contemporaneamente.",
    "ja": "1度に3つの弾を射出する。",
    "ko": "한 번에 세 개의 투사체를 발사합니다.",
    "nl": "Schiet tegelijk drie projectielen af.",
    "pt-BR": "Dispara três projéteis de uma vez só.",
    "ru": "Вы выпускаете три снаряда за раз.",
    "tr": "Aynı anda üç menzilli saldırı yapar.",
    "zh-CN": "一次射出三个投射物。",
    "zh-TW": "一次射出三個投射物。"
  },
  "family": "Fireball",
  "icon": "icons/curses/Fireball_Triple.png",
  "id": "Fireball_Triple",
  "lore": {
    "ar": "ألسنة لهب مطهرة تشتعل بقوة حارقة ثلاثية.",
    "de": "Die Flammen der Reinigung brennen dreimal so hell.",
    "en": "Flames of cleansing burn thrice as bright.",
    "es": "Las llamas del fuego purificador brillan tres veces más.",
    "fr": "Les flammes de la purification brûlent trois fois plus fort.",
    "fr-CA": "Les flammes de la purification brûlent trois fois plus fort.",
    "it": "Le fiamme della purificazione bruciano tre volte più intensamente.",
    "ja": "清め浄化する炎、その輝きの強さは3倍だという。",
    "ko": "정화의 불길이 세 번 밝게 불탄다.",
    "nl": "Louterende vlammen branden drie keer zo fel.",
    "pt-BR": "Chamas purificadoras são três vezes mais brilhantes.",
    "ru": "Очищающее пламя полыхает ярче.",
    "tr": "Arındıran alevlerin kör edici parlaklığına şahit ol.",
    "zh-CN": "净化烈火的火光亮上三倍。",
    "zh-TW": "淨化烈焰燃燒的火光亮上三倍。"
  },
  "name": {
    "ar": "نار التطهير",
    "de": "Reinigendes Feuer",
    "en": "Cleansing Fire",
    "es": "Fuego purificador",
    "fr": "Feu purificateur",
    "fr-CA": "Feu purificateur",
    "it": "Fuoco purificatore",
    "ja": "浄化の炎",
    "ko": "정화의 불길",
    "nl": "Louterend vuur",
    "pt-BR": "Fogo Purificador",
    "ru": "Очищающий огонь",
    "tr": "Arındıran Ateş",
    "zh-CN": "净化烈火",
    "zh-TW": "淨化烈火"
  },
  "namePlain": {
    "ar": "نار التطهير",
    "de": "Reinigendes Feuer",
    "en": "Cleansing Fire",
    "es": "Fuego purificador",
    "fr": "Feu purificateur",
    "fr-CA": "Feu purificateur",
    "it": "Fuoco purificatore",
    "ja": "浄化の炎",
    "ko": "정화의 불길",
    "nl": "Louterend vuur",
    "pt-BR": "Fogo Purificador",
    "ru": "Очищающий огонь",
    "tr": "Arındıran Ateş",
    "zh-CN": "净化烈火",
    "zh-TW": "淨化烈火"
  },
  "thumb": "icons/curses/64/Fireball_Triple.png"
}

=== AuthFailed/cotl-api/site/v1/curses/EnemyBlast.json
{
  "canAim": false,
  "castingDuration": 0.5,
  "chance": 1.0,
  "damage": 1.5,
  "delay": 0.5,
  "description": {
    "ar": "تطيح بالأعداء داخل نطاقك ويلحق بهم الضرر أيضًا.",
    "de": "Wirft Gegner in deiner Reichweite zurück und fügt ihnen gleichzeitig Schaden zu.",
    "en": "Knocks back enemies within your range while also damaging them.",
    "es": "Daña a los enemigos dentro de su alcance y los hace retroceder.",
    "fr": "Repousse et blesse les ennemis à portée.",
    "fr-CA": "Repousse et blesse les ennemis à portée.",
    "it": "Respinge e danneggia i nemici nel raggio d'azione.",
    "ja": "範囲内の敵をノックバックしダメージを与える。",
    "ko": "범위 내에 있는 적들을 밀쳐냄과 동시에 피해를 줍니다.",
    "nl": "Slaat vijanden binnen je bereik terug en verwondt ze.",
    "pt-BR": "Empurra os inimigos ao seu alcance para trás e causa dano a eles.",
    "ru": "Вы отбрасываете врагов, нанося урон.",
    "tr": "Menzilindeki düşmanları geri savurur ve onlara hasar verir.",
    "zh-CN": "击退范围内的敌人，同时造成伤害。",
    "zh-TW": "擊退範圍內的敵人，同時造成傷害。"
  },
  "descriptionPlain": {
    "ar": "تطيح بالأعداء داخل نطاقك ويلحق بهم الضرر أيضًا.",
    "de": "Wirft Gegner in deiner Reichweite zurück und fügt ihnen gleichzeitig Schaden zu.",
    "en": "Knocks back enemies within your range while also damaging them.",
    "es": "Daña a los enemigos dentro de su alcance y los hace retroceder.",
    "fr": "Repousse et blesse les ennemis à portée.",
    "fr-CA": "Repousse et blesse les ennemis à portée.",
    "it": "Respinge e danneggia i nemici nel raggio d'azione.",
    "ja": "範囲内の敵をノックバックしダメージを与える。",
    "ko": "범위 내에 있는 적들을 밀쳐냄과 동시에 피해를 줍니다.",
    "nl": "Slaat vijanden binnen je bereik terug en verwondt ze.",
    "pt-BR": "Empurra os inimigos ao seu alcance para trás e causa dano a eles.",
    "ru": "Вы отбрасываете врагов, нанося урон.",
    "tr": "Menzilindeki düşmanları geri savurur ve onlara hasar verir.",
    "zh-CN": "击退范围内的敌人，同时造成伤害。",
    "zh-TW": "擊退範圍內的敵人，同時造成傷害。"
  },
  "family": "EnemyBlast",
  "icon": "icons/curses/EnemyBlast.png",
  "id": "EnemyBlast",
  "lore": {
    "ar": "لعنة ضد غير الجديرين بوجودك.",
    "de": "Verflucht alle, die deiner Gegenwart unwürdig sind.",
    "en": "A curse against those unworthy of your presence.",
    "es": "Una maldición contra los indignos de tu presencia.",
    "fr": "Maléfice pour les êtres indignes de votre présence.",
    "fr-CA": "Maléfice pour les êtres indignes de votre présence.",
    "it": "Sia maledetto chi non è degno della tua presenza.",
    "ja": "敵とみなした者どもに対抗するための呪い。",
    "ko": "당신의 존재에 걸맞지 않은 자들에게 내리는 저주이다.",
    "nl": "Een vloek tegen hen die je niet waardig zijn.",
    "pt-BR": "Uma maldição para aqueles indignos de sua presença.",
    "ru": "Проклятие для тех, кто недостоин быть рядом с вами.",
    "tr": "Senin huzuruna çıkmaya layık olmayanlara karşı bir lanet.",
    "zh-CN": "咒术之一，攻击不配出现在你眼前的敌人。",
    "zh-TW": "咒術之一，攻擊不配出現在你眼前的敵人。"
  },
  "name": {
    "ar": "الانفجار المقدر",
    "de": "Göttliche Explosion",
    "en": "Divine Blast",
    "es": "Explosión divina",
    "fr": "Rafale divine",
    "fr-CA": "Rafale divine",
    "it": "Esplosione divina",
    "ja": "神聖なる波動",
    "ko": "신성한 일격",
    "nl": "Goddelijke klap",
    "pt-BR": "Explosão Divina",
    "ru": "Божественный взрыв",
    "tr": "İlahi İnfilak",
    "zh-CN": "神圣爆炸",
    "zh-TW": "神聖爆炸"
  },
  "namePlain": {
    "ar": "الانفجار المقدر",
    "de": "Göttliche Explosion",
    "en": "Divine Blast",
    "es": "Explosión divina",
    "fr": "Rafale divine",
    "fr-CA": "Rafale divine",
    "it": "Esplosione divina",
    "ja": "神聖なる波動",
    "ko": "신성한 일격",
    "nl": "Goddelijke klap",
    "pt-BR": "Explosão Divina",
    "ru": "Божественный взрыв",
    "tr": "İlahi İnfilak",
    "zh-CN": "神圣爆炸",
    "zh-TW": "神聖爆炸"
  },
  "thumb": "icons/curses/64/EnemyBlast.png"
}

=== AuthFailed/cotl-api/site/v1/curses/EnemyBlast_Poison.json
{
  "canAim": false,
  "castingDuration": 0.5,
  "chance": 1.0,
  "damage": 1.5,
  "delay": 0.5,
  "description": {
    "ar": "تطيح بالأعداء وتسممهم.",
    "de": "Wirft Gegner zurück und vergiftet sie.",
    "en": "Knocks back and poisons enemies.",
    "es": "Empuja y envenena a los enemigos.",
    "fr": "Repousse et empoisonne les ennemis.",
    "fr-CA": "Repousse et empoisonne les ennemis.",
    "it": "Respinge e avvelena i nemici.",
    "ja": "敵をノックバックし、毒を付与する。",
    "ko": "적들을 밀치고 중독시킵니다.",
    "nl": "Slaat vijanden terug en vergiftigt ze.",
    "pt-BR": "Empurra e envenena os inimigos.",
    "ru": "Вы отбрасываете врагов, отравляя их.",
    "tr": "Düşmanları geri savurur ve zehirler.",
    "zh-CN": "击退敌人并使其中毒。",
    "zh-TW": "擊退敵人並使其中毒。"
  },
  "descriptionPlain": {
    "ar": "تطيح بالأعداء وتسممهم.",
    "de": "Wirft Gegner zurück und vergiftet sie.",
    "en": "Knocks back and poisons enemies.",
    "es": "Empuja y envenena a los enemigos.",
    "fr": "Repousse et empoisonne les ennemis.",
    "fr-CA": "Repousse et empoisonne les ennemis.",
    "it": "Respinge e avvelena i nemici.",
    "ja": "敵をノックバックし、毒を付与する。",
    "ko": "적들을 밀치고 중독시킵니다.",
    "nl": "Slaat vijanden terug en vergiftigt ze.",
    "pt-BR": "Empurra e envenena os inimigos.",
    "ru": "Вы отбрасываете врагов, отравляя их.",
    "tr": "Düşmanları geri savurur ve zehirler.",
    "zh-CN": "击退敌人并使其中毒。",
    "zh-TW": "擊退敵人並使其中毒。"
  },
  "family": "EnemyBlast",
  "icon": "icons/curses/EnemyBlast_Poison.png",
  "id": "EnemyBlast_Poison",
  "lore": {
    "ar": "تنذر بسوء الطالع.",
    "de": "Das Omen eines großen Unglücks.",
    "en": "Omen of great ill fortune.",
    "es": "Un mal augurio.",
    "fr": "Présage d'un grand malheur.",
    "fr-CA": "Présage d'un grand malheur.",
    "it": "Presagio di grande sfortuna.",
    "ja": "大いなる不運の前触れ。",
    "ko": "커다란 불행의 징조다.",
    "nl": "Voorbode van grote rampspoed.",
    "pt-BR": "Um presságio de grande infortúnio.",
    "ru": "Предвестие ещё большей беды.",
    "tr": "Makus kaderin alameti.",
    "zh-CN": "恐怖厄运的预兆。",
    "zh-TW": "恐怖厄運的預兆。"
  },
  "name": {
    "ar": "البلاء المقدر",
    "de": "Göttliche Pest",
    "en": "Divine Blight",
    "es": "Plaga divina",
    "fr": "Châtiment sacré",
    "fr-CA": "Châtiment sacré",
    "it": "Flagello divino",
    "ja": "神聖なる毒風",
    "ko": "신성한 역병",
    "nl": "Goddelijk verderf",
    "pt-BR": "Flagelo Divino",
    "ru": "Божественный мор",
    "tr": "İlahi Mahvoluş",
    "zh-CN": "神圣毒祸",
    "zh-TW": "神聖毒禍"
  },
  "namePlain": {
    "ar": "البلاء المقدر",
    "de": "Göttliche Pest",
    "en": "Divine Blight",
    "es": "Plaga divina",
    "fr": "Châtiment sacré",
    "fr-CA": "Châtiment sacré",
    "it": "Flagello divino",
    "ja": "神聖なる毒風",
    "ko": "신성한 역병",
    "nl": "Goddelijk verderf",
    "pt-BR": "Flagelo Divino",
    "ru": "Божественный мор",
    "tr": "İlahi Mahvoluş",
    "zh-CN": "神圣毒祸",
    "zh-TW": "神聖毒禍"
  },
  "thumb": "icons/curses/64/EnemyBlast_Poison.png"
}
