=== AuthFailed/cotl-api/site/v1/schema/fleece.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Fleece",
  "type": "object",
  "required": [
    "id",
    "name",
    "description",
    "namePlain",
    "descriptionPlain",
    "icon",
    "thumb",
    "fleece",
    "cost",
    "pack"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]+$"
    },
    "name": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      },
      "required": [
        "en"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "namePlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "name without the game's text markup"
    },
    "descriptionPlain": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "description without the game's text markup"
    },
    "icon": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/fleeces/[A-Za-z0-9_-]+\\.png$"
    },
    "thumb": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^icons/fleeces/64/[A-Za-z0-9_-]+\\.png$"
    },
    "fleece": {
      "type": "integer",
      "description": "the game's fleece number"
    },
    "cost": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "item",
          "quantity"
        ],
        "properties": {
          "item": {
            "type": "string"
          },
          "quantity": {
            "type": "integer",
            "minimum": 0
          }
        }
      }
    },
    "pack": {
      "type": [
        "string",
        "null"
      ],
      "description": "DLC pack it comes with, or null"
    }
  }
}

=== AuthFailed/cotl-api/site/v1/fleeces/White.json
{
  "cost": [
    {
      "item": "TALISMAN",
      "quantity": 1
    }
  ],
  "description": {
    "ar": "يسحب 4 بطاقات تارو في بداية الحملة، لكن لا يمكن سحب أي منها بعد ذلك.",
    "de": "Ziehe 4 Tarotkarten zu Beginn jedes Durchlaufs, aber keine kann im Nachhinein gezogen werden.",
    "en": "Draw 4 Tarot Cards at the start of a run, but none can be drawn after.",
    "es": "Levantas 4 cartas del tarot al comienzo de una partida, pero ya no podrás levantar más.",
    "fr": "Tire quatre cartes de tarot au début du donjon, mais aucune carte ne pourra plus être tirée ensuite.",
    "fr-CA": "Tire 4 cartes de tarot au début d'une croisade, mais aucune carte ne pourra plus être tirée ensuite.",
    "it": "Peschi 4 tarocchi all'inizio di una crociata, ma non ne otterrai oltre.",
    "ja": "ダンジョン開始時にタロットカードを4枚引く。その後タロットカードを引けなくなる。",
    "ko": "게임 시작 시 타로 카드 4장을 뽑지만, 이후로 타로 카드를 뽑을 수 없습니다.",
    "nl": "Trek 4 tarotkaarten aan het begin van een run, maar daarna kun je er geen meer trekken.",
    "pt-BR": "Saca 4 cartas de tarô no início de uma partida, mas nenhuma pode ser sacada depois.",
    "ru": "Вы получаете 4 карты Таро перед началом похода, но не можете брать их позже.",
    "tr": "Bir denemenin başında 4 Tarot Kartı çekersin fakat deneme sırasında hiç kart çekemezsin.",
    "zh-CN": "每轮开始时抽 4 张塔罗牌，之后无法再抽塔罗牌。",
    "zh-TW": "每輪開始時抽 4 張塔羅牌，之後無法再抽塔羅牌。"
  },
  "descriptionPlain": {
    "ar": "يسحب 4 بطاقات تارو في بداية الحملة، لكن لا يمكن سحب أي منها بعد ذلك.",
    "de": "Ziehe 4 Tarotkarten zu Beginn jedes Durchlaufs, aber keine kann im Nachhinein gezogen werden.",
    "en": "Draw 4 Tarot Cards at the start of a run, but none can be drawn after.",
    "es": "Levantas 4 cartas del tarot al comienzo de una partida, pero ya no podrás levantar más.",
    "fr": "Tire quatre cartes de tarot au début du donjon, mais aucune carte ne pourra plus être tirée ensuite.",
    "fr-CA": "Tire 4 cartes de tarot au début d'une croisade, mais aucune carte ne pourra plus être tirée ensuite.",
    "it": "Peschi 4 tarocchi all'inizio di una crociata, ma non ne otterrai oltre.",
    "ja": "ダンジョン開始時にタロットカードを4枚引く。その後タロットカードを引けなくなる。",
    "ko": "게임 시작 시 타로 카드 4장을 뽑지만, 이후로 타로 카드를 뽑을 수 없습니다.",
    "nl": "Trek 4 tarotkaarten aan het begin van een run, maar daarna kun je er geen meer trekken.",
    "pt-BR": "Saca 4 cartas de tarô no início de uma partida, mas nenhuma pode ser sacada depois.",
    "ru": "Вы получаете 4 карты Таро перед началом похода, но не можете брать их позже.",
    "tr": "Bir denemenin başında 4 Tarot Kartı çekersin fakat deneme sırasında hiç kart çekemezsin.",
    "zh-CN": "每轮开始时抽 4 张塔罗牌，之后无法再抽塔罗牌。",
    "zh-TW": "每輪開始時抽 4 張塔羅牌，之後無法再抽塔羅牌。"
  },
  "fleece": 4,
  "icon": "icons/fleeces/White.png",
  "id": "White",
  "name": {
    "ar": "رداء الأقدار",
    "de": "Vlies der Schicksale",
    "en": "Fleece of the Fates",
    "es": "Vellocino del destino",
    "fr": "Pelisse du destin",
    "fr-CA": "Toison du destin",
    "it": "Vello del destino",
    "ja": "運命の羊毛",
    "ko": "운명의 양털",
    "nl": "Vacht van het lot",
    "pt-BR": "Lã dos Destinos",
    "ru": "Руно судьбы",
    "tr": "Yazgı Postu",
    "zh-CN": "命运毛纺",
    "zh-TW": "命運毛紡"
  },
  "namePlain": {
    "ar": "رداء الأقدار",
    "de": "Vlies der Schicksale",
    "en": "Fleece of the Fates",
    "es": "Vellocino del destino",
    "fr": "Pelisse du destin",
    "fr-CA": "Toison du destin",
    "it": "Vello del destino",
    "ja": "運命の羊毛",
    "ko": "운명의 양털",
    "nl": "Vacht van het lot",
    "pt-BR": "Lã dos Destinos",
    "ru": "Руно судьбы",
    "tr": "Yazgı Postu",
    "zh-CN": "命运毛纺",
    "zh-TW": "命運毛紡"
  },
  "pack": null,
  "thumb": "icons/fleeces/64/White.png"
}

=== AuthFailed/cotl-api/site/v1/fleeces/Fleece667.json
{
  "cost": [
    {
      "item": "TALISMAN",
      "quantity": 1
    }
  ],
  "description": {
    "ar": "ذو قلنسوة حمراء صغيرة. <color=\"grey\"> <br> لا يمنح مزايا.",
    "de": "Eine kleine rote Kapuze. <color=\"grey\"> <br> Gewährt keine Boni.",
    "en": "A little red hood. <color=\"grey\"> <br> Provides no bonuses.",
    "es": "Una capa roja con capucha. <color=\"grey\"> <br> No otorga nada especial.",
    "fr": "Un chaperon rouge. <color=\"grey\"> <br> N'octroie aucun bonus.",
    "fr-CA": "Un chaperon rouge. <color=\"grey\"> <br> N'octroie aucun bonus.",
    "it": "Un piccolo cappuccio rosso. <color=\"grey\"> <br> Non fornisce bonus.",
    "ja": "小さな赤ずきん。<color=\"grey\"> <br> ボーナスなし。",
    "ko": "작은 빨간 두건입니다. <color=\"grey\"> <br> 특별한 효과는 없습니다.",
    "nl": "Een kleine rode kap. <color=\"grey\"> <br> Geeft geen bonussen.",
    "pt-BR": "Um pequeno capuz vermelho. <color=\"grey\"> <br> Não fornece nenhum bônus.",
    "ru": "Красная накидка.<color=\"grey\"><br>Не даёт преимуществ.",
    "tr": "Kırmızı başlıklı koyun. <color=\"grey\"> <br> İlave özellik sağlamaz.",
    "zh-CN": "红色小兜帽。<color=\"grey\"><br>没有特殊效果。",
    "zh-TW": "小紅帽。<color=\"grey\"><br>沒有特殊效果。"
  },
  "descriptionPlain": {
    "ar": "ذو قلنسوة حمراء صغيرة.\nلا يمنح مزايا.",
    "de": "Eine kleine rote Kapuze.\nGewährt keine Boni.",
    "en": "A little red hood.\nProvides no bonuses.",
    "es": "Una capa roja con capucha.\nNo otorga nada especial.",
    "fr": "Un chaperon rouge.\nN'octroie aucun bonus.",
    "fr-CA": "Un chaperon rouge.\nN'octroie aucun bonus.",
    "it": "Un piccolo cappuccio rosso.\nNon fornisce bonus.",
    "ja": "小さな赤ずきん。\nボーナスなし。",
    "ko": "작은 빨간 두건입니다.\n특별한 효과는 없습니다.",
    "nl": "Een kleine rode kap.\nGeeft geen bonussen.",
    "pt-BR": "Um pequeno capuz vermelho.\nNão fornece nenhum bônus.",
    "ru": "Красная накидка.\nНе даёт преимуществ.",
    "tr": "Kırmızı başlıklı koyun.\nİlave özellik sağlamaz.",
    "zh-CN": "红色小兜帽。\n没有特殊效果。",
    "zh-TW": "小紅帽。\n沒有特殊效果。"
  },
  "fleece": 667,
  "icon": "icons/fleeces/Fleece667.png",
  "id": "Fleece667",
  "name": {
    "ar": "رداء البريئة",
    "de": "Vlies der Unschuldigen",
    "en": "Fleece of the Innocent",
    "es": "Vellocino de la Inocente",
    "fr": "Pelisse de l'innocente",
    "fr-CA": "Toison de l'innocente",
    "it": "Vello dell'innocente",
    "ja": "純真無垢の羊毛",
    "ko": "순수한 자의 양털",
    "nl": "Vacht van de onschuldige",
    "pt-BR": "Lã da Inocência",
    "ru": "Руно невинности",
    "tr": "Masumun Postu",
    "zh-CN": "无辜者毛纺",
    "zh-TW": "無辜者毛紡"
  },
  "namePlain": {
    "ar": "رداء البريئة",
    "de": "Vlies der Unschuldigen",
    "en": "Fleece of the Innocent",
    "es": "Vellocino de la Inocente",
    "fr": "Pelisse de l'innocente",
    "fr-CA": "Toison de l'innocente",
    "it": "Vello dell'innocente",
    "ja": "純真無垢の羊毛",
    "ko": "순수한 자의 양털",
    "nl": "Vacht van de onschuldige",
    "pt-BR": "Lã da Inocência",
    "ru": "Руно невинности",
    "tr": "Masumun Postu",
    "zh-CN": "无辜者毛纺",
    "zh-TW": "無辜者毛紡"
  },
  "pack": "woolhaven",
  "thumb": "icons/fleeces/64/Fleece667.png"
}

=== AuthFailed/cotl-api/site/v1/fleeces/OneHitKills.json
{
  "cost": [
    {
      "item": "TALISMAN",
      "quantity": 1
    }
  ],
  "description": {
    "ar": "ضربة واحدة. لا يمكن العودة إلى الحياة. يلحق 10x من ضرر السلاح.",
    "de": "Ein Treffer. Keine Wiedererweckungen. Teile den zehnfachen Schaden aus.",
    "en": "One hit. No resurrections. Deal 10x weapon damage.",
    "es": "Un golpe. Sin resurrecciones. Las armas infligen x10 de daño.",
    "fr": "Un coup. Pas de résurrection. Dégâts des armes multipliés par 10.",
    "fr-CA": "Un coup. Pas de résurrection. Dégâts des armes multipliés par 10.",
    "it": "Puoi ricevere un colpo solo, senza poter risorgere, ma l'arma infligge dieci volte il danno base.",
    "ja": "ハートは1つのみ、復活はできない。与えるダメージが10倍になる。",
    "ko": "1대 맞을 시 사망. 부활 없음. 무기 피해를 10배로 가합니다.",
    "nl": "Eén treffer. Geen wederopstandingen. Breng 10x wapenschade toe.",
    "pt-BR": "Um acerto. Sem ressurreições. Causa 10x de dano.",
    "ru": "Вы остаётесь с одним сердцем и не можете возвращаться к жизни, но наносите в 10 раз больше урона оружием.",
    "tr": "Tek vurulma şansı. Dirilme yok. 10 kat fazla silah hasarı verirsin.",
    "zh-CN": "一击必杀。无法复活。武器伤害为10倍。",
    "zh-TW": "一擊死亡，無法復活。武器傷害為 10 倍。"
  },
  "descriptionPlain": {
    "ar": "ضربة واحدة. لا يمكن العودة إلى الحياة. يلحق 10x من ضرر السلاح.",
    "de": "Ein Treffer. Keine Wiedererweckungen. Teile den zehnfachen Schaden aus.",
    "en": "One hit. No resurrections. Deal 10x weapon damage.",
    "es": "Un golpe. Sin resurrecciones. Las armas infligen x10 de daño.",
    "fr": "Un coup. Pas de résurrection. Dégâts des armes multipliés par 10.",
    "fr-CA": "Un coup. Pas de résurrection. Dégâts des armes multipliés par 10.",
    "it": "Puoi ricevere un colpo solo, senza poter risorgere, ma l'arma infligge dieci volte il danno base.",
    "ja": "ハートは1つのみ、復活はできない。与えるダメージが10倍になる。",
    "ko": "1대 맞을 시 사망. 부활 없음. 무기 피해를 10배로 가합니다.",
    "nl": "Eén treffer. Geen wederopstandingen. Breng 10x wapenschade toe.",
    "pt-BR": "Um acerto. Sem ressurreições. Causa 10x de dano.",
    "ru": "Вы остаётесь с одним сердцем и не можете возвращаться к жизни, но наносите в 10 раз больше урона оружием.",
    "tr": "Tek vurulma şansı. Dirilme yok. 10 kat fazla silah hasarı verirsin.",
    "zh-CN": "一击必杀。无法复活。武器伤害为10倍。",
    "zh-TW": "一擊死亡，無法復活。武器傷害為 10 倍。"
  },
  "fleece": 7,
  "icon": "icons/fleeces/OneHitKills.png",
  "id": "OneHitKills",
  "name": {
    "ar": "رداء الشرس",
    "de": "Vlies des Berserkers",
    "en": "Fleece of the Berserker",
    "es": "Vellocino del berserker",
    "fr": "Pelisse du berserker",
    "fr-CA": "Toison du berserker",
    "it": "Vello del guerriero furioso",
    "ja": "狂戦士の羊毛",
    "ko": "광전사의 양털",
    "nl": "Vacht van de berserker",
    "pt-BR": "Lã do Guerreiro Furioso",
    "ru": "Руно берсерка",
    "tr": "Barbar Postu",
    "zh-CN": "狂战士毛纺",
    "zh-TW": "狂戰士毛紡"
  },
  "namePlain": {
    "ar": "رداء الشرس",
    "de": "Vlies des Berserkers",
    "en": "Fleece of the Berserker",
    "es": "Vellocino del berserker",
    "fr": "Pelisse du berserker",
    "fr-CA": "Toison du berserker",
    "it": "Vello del guerriero furioso",
    "ja": "狂戦士の羊毛",
    "ko": "광전사의 양털",
    "nl": "Vacht van de berserker",
    "pt-BR": "Lã do Guerreiro Furioso",
    "ru": "Руно берсерка",
    "tr": "Barbar Postu",
    "zh-CN": "狂战士毛纺",
    "zh-TW": "狂戰士毛紡"
  },
  "pack": null,
  "thumb": "icons/fleeces/64/OneHitKills.png"
}

=== AuthFailed/cotl-api/site/v1/fleeces/Gold.json
{
  "cost": [
    {
      "item": "TALISMAN",
      "quantity": 1
    }
  ],
  "description": {
    "ar": "يزيد الضرر المُلحق بعد كل عملية قتل، لكن يُعاد التعيين عند تلقي ضربة. يُضاعف الضرر الوارد.",
    "de": "Der verursachte Schaden erhöht sich mit jedem Kill, wird aber zurückgesetzt, wenn du getroffen wirst. Du erleidest doppelten Schaden.",
    "en": "Damage dealt increases after each kill, but resets when hit. Take double damage.",
    "es": "El daño que infliges va aumentando con cada muerte, pero se restablece cuando encajas un golpe y recibes el doble de daño.",
    "fr": "Vous infligez plus de dégâts pour chaque ennemi tué. Effet réinitialisé lorsqu'un ennemi vous attaque. Vous subissez 2x plus de dégâts.",
    "fr-CA": "Vous infligez plus de dégâts pour chaque ennemi tué. Effet réinitialisé lorsqu'un ennemi vous attaque. Vous subissez 2x plus de dégâts.",
    "it": "I danni inflitti aumentano dopo ogni uccisione, ma si azzerano quando subisci un colpo. Ricevi il doppio dei danni.",
    "ja": "敵を倒すたびに与えるダメージが上昇するが、攻撃を受けるとそれをリセットする。受けるダメージが2倍になる。",
    "ko": "적을 죽일 때마다 가하는 피해량이 증가하지만, 피격당할 시 초기화됩니다. 두 배의 피해를 입습니다.",
    "nl": "Na elke gedode vijand breng je meer schade toe. Dit effect wordt gereset nadat je zelf wordt geraakt. Je krijgt twee keer zoveel schade.",
    "pt-BR": "O dano causado aumenta após cada abate, mas é zerado ao sofrer dano. Recebe o dobro de dano.",
    "ru": "Наносимый урон увеличивается после каждого убийства, но возвращается к исходному значению при получении урона. Получаемый урон удваивается.",
    "tr": "Verilen hasar öldürdüğün düşman başına artar ancak bir saldırıdan isabet aldığında sıfırlanır. İki kat fazla hasar alırsın.",
    "zh-CN": "每次击杀敌人后增加对敌方造成的伤害值，受到攻击时重置。受到的伤害加倍。",
    "zh-TW": "每次擊殺敵人後增加對敵方造成的傷害值，受到攻擊時重置。受到的傷害加倍。"
  },
  "descriptionPlain": {
    "ar": "يزيد الضرر المُلحق بعد كل عملية قتل، لكن يُعاد التعيين عند تلقي ضربة. يُضاعف الضرر الوارد.",
    "de": "Der verursachte Schaden erhöht sich mit jedem Kill, wird aber zurückgesetzt, wenn du getroffen wirst. Du erleidest doppelten Schaden.",
    "en": "Damage dealt increases after each kill, but resets when hit. Take double damage.",
    "es": "El daño que infliges va aumentando con cada muerte, pero se restablece cuando encajas un golpe y recibes el doble de daño.",
    "fr": "Vous infligez plus de dégâts pour chaque ennemi tué. Effet réinitialisé lorsqu'un ennemi vous attaque. Vous subissez 2x plus de dégâts.",
    "fr-CA": "Vous infligez plus de dégâts pour chaque ennemi tué. Effet réinitialisé lorsqu'un ennemi vous attaque. Vous subissez 2x plus de dégâts.",
    "it": "I danni inflitti aumentano dopo ogni uccisione, ma si azzerano quando subisci un colpo. Ricevi il doppio dei danni.",
    "ja": "敵を倒すたびに与えるダメージが上昇するが、攻撃を受けるとそれをリセットする。受けるダメージが2倍になる。",
    "ko": "적을 죽일 때마다 가하는 피해량이 증가하지만, 피격당할 시 초기화됩니다. 두 배의 피해를 입습니다.",
    "nl": "Na elke gedode vijand breng je meer schade toe. Dit effect wordt gereset nadat je zelf wordt geraakt. Je krijgt twee keer zoveel schade.",
    "pt-BR": "O dano causado aumenta após cada abate, mas é zerado ao sofrer dano. Recebe o dobro de dano.",
    "ru": "Наносимый урон увеличивается после каждого убийства, но возвращается к исходному значению при получении урона. Получаемый урон удваивается.",
    "tr": "Verilen hasar öldürdüğün düşman başına artar ancak bir saldırıdan isabet aldığında sıfırlanır. İki kat fazla hasar alırsın.",
    "zh-CN": "每次击杀敌人后增加对敌方造成的伤害值，受到攻击时重置。受到的伤害加倍。",
    "zh-TW": "每次擊殺敵人後增加對敵方造成的傷害值，受到攻擊時重置。受到的傷害加倍。"
  },
  "fleece": 1,
  "icon": "icons/fleeces/Gold.png",
  "id": "Gold",
  "name": {
    "ar": "الرداء الذهبي",
    "de": "Goldenes Vlies",
    "en": "Golden Fleece",
    "es": "Vellocino de oro",
    "fr": "Pelisse dorée",
    "fr-CA": "Toison dorée",
    "it": "Vello aureo",
    "ja": "黄金の羊毛",
    "ko": "황금 양털",
    "nl": "Gulden vlies",
    "pt-BR": "Lã Dourada",
    "ru": "Золотое руно",
    "tr": "Altın Post",
    "zh-CN": "金毛纺",
    "zh-TW": "金毛紡"
  },
  "namePlain": {
    "ar": "الرداء الذهبي",
    "de": "Goldenes Vlies",
    "en": "Golden Fleece",
    "es": "Vellocino de oro",
    "fr": "Pelisse dorée",
    "fr-CA": "Toison dorée",
    "it": "Vello aureo",
    "ja": "黄金の羊毛",
    "ko": "황금 양털",
    "nl": "Gulden vlies",
    "pt-BR": "Lã Dourada",
    "ru": "Золотое руно",
    "tr": "Altın Post",
    "zh-CN": "金毛纺",
    "zh-TW": "金毛紡"
  },
  "pack": null,
  "thumb": "icons/fleeces/64/Gold.png"
}

=== AuthFailed/cotl-api/site/v1/fleeces/GodOfDeath.json
{
  "cost": [
    {
      "item": "TALISMAN",
      "quantity": 1
    }
  ],
  "description": {
    "ar": "عند العودة إلى الحياة، يمكنك الحصول على قلبين فاسدين.",
    "de": "Erhalte bei der Wiedererweckung 2 kranke Herzen.",
    "en": "When Resurrecting gain 2 Diseased Hearts.",
    "es": "Ganas 2 corazones enfermos al resucitar.",
    "fr": "Donne 2 cœurs corrompus lorsque vous ressuscitez.",
    "fr-CA": "Donne 2 cœurs corrompus lorsque vous ressuscitez.",
    "it": "Quando risorgi, ottieni 2 cuori afflitti.",
    "ja": "復活時に病みし心臓を2個得る。",
    "ko": "부활할 때 병든 심장을 2개 얻습니다.",
    "nl": "Krijg 2 ziekelijke harten bij wederopstanding.",
    "pt-BR": "Ganha 2 Corações Doentes ao Ressuscitar.",
    "ru": "Вы получаете два больных сердца после оживления.",
    "tr": "Dirildiğinde 2 Çürümüş Kalp kazanırsın.",
    "zh-CN": "复活时获得 2 颗病缠黑心。",
    "zh-TW": "復活時獲得 2 顆病纏黑心。"
  },
  "descriptionPlain": {
    "ar": "عند العودة إلى الحياة، يمكنك الحصول على قلبين فاسدين.",
    "de": "Erhalte bei der Wiedererweckung 2 kranke Herzen.",
    "en": "When Resurrecting gain 2 Diseased Hearts.",
    "es": "Ganas 2 corazones enfermos al resucitar.",
    "fr": "Donne 2 cœurs corrompus lorsque vous ressuscitez.",
    "fr-CA": "Donne 2 cœurs corrompus lorsque vous ressuscitez.",
    "it": "Quando risorgi, ottieni 2 cuori afflitti.",
    "ja": "復活時に病みし心臓を2個得る。",
    "ko": "부활할 때 병든 심장을 2개 얻습니다.",
    "nl": "Krijg 2 ziekelijke harten bij wederopstanding.",
    "pt-BR": "Ganha 2 Corações Doentes ao Ressuscitar.",
    "ru": "Вы получаете два больных сердца после оживления.",
    "tr": "Dirildiğinde 2 Çürümüş Kalp kazanırsın.",
    "zh-CN": "复活时获得 2 颗病缠黑心。",
    "zh-TW": "復活時獲得 2 顆病纏黑心。"
  },
  "fleece": 1000,
  "icon": "icons/fleeces/GodOfDeath.png",
  "id": "GodOfDeath",
  "name": {
    "ar": "رداء سيد الموت",
    "de": "Gott des Todes-Vlieses",
    "en": "God of Death Fleece",
    "es": "Vellocino dios de la muerte",
    "fr": "Pelisse du Dieu de la mort",
    "fr-CA": "Toison du Dieu de la mort",
    "it": "Vello del Dio della Morte",
    "ja": "死の神の羊毛",
    "ko": "죽음의 신 양털",
    "nl": "Vacht van de god der doden",
    "pt-BR": "Lã do Deus da Morte",
    "ru": "Руно владыки смерти",
    "tr": "Ölüm Tanrısı Postu",
    "zh-CN": "死亡之神毛纺",
    "zh-TW": "死亡之神毛紡"
  },
  "namePlain": {
    "ar": "رداء سيد الموت",
    "de": "Gott des Todes-Vlieses",
    "en": "God of Death Fleece",
    "es": "Vellocino dios de la muerte",
    "fr": "Pelisse du Dieu de la mort",
    "fr-CA": "Toison du Dieu de la mort",
    "it": "Vello del Dio della Morte",
    "ja": "死の神の羊毛",
    "ko": "죽음의 신 양털",
    "nl": "Vacht van de god der doden",
    "pt-BR": "Lã do Deus da Morte",
    "ru": "Руно владыки смерти",
    "tr": "Ölüm Tanrısı Postu",
    "zh-CN": "死亡之神毛纺",
    "zh-TW": "死亡之神毛紡"
  },
  "pack": null,
  "thumb": "icons/fleeces/64/GodOfDeath.png"
}

=== AuthFailed/cotl-api/site/v1/fleeces/Outfit_1002.json
{
  "cost": [
    {
      "item": "TALISMAN",
      "quantity": 1
    }
  ],
  "description": {
    "ar": "ثوب طويل أنيق ناعم الملمس. <color=\"grey\"> <br> لا يمنح مزايا.",
    "de": "Eine elegante Robe, die sich sehr weich anfühlt. <color=\"grey\"> <br> Gewährt keine Boni.",
    "en": "An elegant robe, soft to the touch. <color=\"grey\"> <br> Provides no bonuses.",
    "es": "Una túnica elegante y suave al tacto. <color=\"grey\"> <br> No otorga nada especial.",
    "fr": "Une tenue élégante, agréable au toucher. <color=\"grey\"> <br> N'octroie aucun bonus.",
    "fr-CA": "Une tenue élégante, agréable au toucher. <color=\"grey\"> <br> N'octroie aucun bonus.",
    "it": "Una veste elegante, soffice al tatto.<color=\"grey\"><br>Non fornisce bonus.",
    "ja": "すごく柔らかい、上品なローブ。<color=\"grey\"> <br> ボーナスなし。",
    "ko": "부드러운 촉감의 우아한 로브입니다. <color=\"grey\"> <br> 특별한 효과는 없습니다.",
    "nl": "Een elegant gewaad voor een zijdezacht gevoel. <color=\"grey\"> <br> Geeft geen bonussen.",
    "pt-BR": "Um traje elegante, suave ao toque. <color=\"grey\"> <br> Não fornece nenhum bônus.",
    "ru": "Изящное одеяние, мягкое на ощупь.<color=\"grey\"><br>Не даёт преимуществ.",
    "tr": "Şık ve epey yumuşak bir cübbe. <color=\"grey\"> <br> İlave özellik sağlamaz.",
    "zh-CN": "优雅的教服，触感柔软。<color=\"grey\"><br>没有特殊效果。",
    "zh-TW": "優雅的教服，觸感柔軟。<color=\"grey\"><br>沒有特殊效果。"
  },
  "descriptionPlain": {
    "ar": "ثوب طويل أنيق ناعم الملمس.\nلا يمنح مزايا.",
    "de": "Eine elegante Robe, die sich sehr weich anfühlt.\nGewährt keine Boni.",
    "en": "An elegant robe, soft to the touch.\nProvides no bonuses.",
    "es": "Una túnica elegante y suave al tacto.\nNo otorga nada especial.",
    "fr": "Une tenue élégante, agréable au toucher.\nN'octroie aucun bonus.",
    "fr-CA": "Une tenue élégante, agréable au toucher.\nN'octroie aucun bonus.",
    "it": "Una veste elegante, soffice al tatto.\nNon fornisce bonus.",
    "ja": "すごく柔らかい、上品なローブ。\nボーナスなし。",
    "ko": "부드러운 촉감의 우아한 로브입니다.\n특별한 효과는 없습니다.",
    "nl": "Een elegant gewaad voor een zijdezacht gevoel.\nGeeft geen bonussen.",
    "pt-BR": "Um traje elegante, suave ao toque.\nNão fornece nenhum bônus.",
    "ru": "Изящное одеяние, мягкое на ощупь.\nНе даёт преимуществ.",
    "tr": "Şık ve epey yumuşak bir cübbe.\nİlave özellik sağlamaz.",
    "zh-CN": "优雅的教服，触感柔软。\n没有特殊效果。",
    "zh-TW": "優雅的教服，觸感柔軟。\n沒有特殊效果。"
  },
  "fleece": 1002,
  "icon": "icons/fleeces/Outfit_1002.png",
  "id": "Outfit_1002",
  "name": {
    "ar": "رداء بلمسة حريرية",
    "de": "Vlies der sanften Seide",
    "en": "Fleece of the Silken Touch",
    "es": "Vellocino del tacto sedoso",
    "fr": "Pelisse du toucher soyeux",
    "fr-CA": "Toison du toucher soyeux",
    "it": "Vello setoso",
    "ja": "上質な絹の羊毛",
    "ko": "비단결 같은 손길의 양털",
    "nl": "Vacht van zijde",
    "pt-BR": "Lã do Toque Sedoso",
    "ru": "Руно шёлковой глади",
    "tr": "İpeksi Dokunuş Postu",
    "zh-CN": "丝质触感毛纺",
    "zh-TW": "絲質觸感毛紡"
  },
  "namePlain": {
    "ar": "رداء بلمسة حريرية",
    "de": "Vlies der sanften Seide",
    "en": "Fleece of the Silken Touch",
    "es": "Vellocino del tacto sedoso",
    "fr": "Pelisse du toucher soyeux",
    "fr-CA": "Toison du toucher soyeux",
    "it": "Vello setoso",
    "ja": "上質な絹の羊毛",
    "ko": "비단결 같은 손길의 양털",
    "nl": "Vacht van zijde",
    "pt-BR": "Lã do Toque Sedoso",
    "ru": "Руно шёлковой глади",
    "tr": "İpeksi Dokunuş Postu",
    "zh-CN": "丝质触感毛纺",
    "zh-TW": "絲質觸感毛紡"
  },
  "pack": "pilgrim",
  "thumb": "icons/fleeces/64/Outfit_1002.png"
}

=== AuthFailed/cotl-api/site/v1/fleeces/Fleece674.json
{
  "cost": [
    {
      "item": "TALISMAN",
      "quantity": 1
    }
  ],
  "description": {
    "ar": "تقديرًا لمَن يسجلون التاريخ. <color=\"grey\"> <br> لا يمنح مزايا.",
    "de": "Eine Hommage an diejenigen, die Geschichte aufzeichnen. <color=\"grey\"> <br> Gewährt keine Boni.",
    "en": "An homage to those who record history. <color=\"grey\"> <br> Provides no bonuses.",
    "es": "Un homenaje a los cronistas de la historia. <color=\"grey\"> <br> No otorga nada especial.",
    "fr": "Un hommage à tous les historiens. <color=\"grey\"> <br> N'octroie aucun bonus.",
    "fr-CA": "Un hommage à tous les gardiens de la mémoire. <color=\"grey\"> <br> N'octroie aucun bonus.",
    "it": "Un omaggio a chi preserva la storia. <color=\"grey\"> <br> Non fornisce bonus.",
    "ja": "歴史を記録し、後世に残した者への敬意の象徴。<color=\"grey\"> <br> ボーナスなし。",
    "ko": "역사를 기록하는 자들에게 바치는 헌정입니다. <color=\"grey\"> <br> 특별한 효과는 없습니다.",
    "nl": "Een ode aan hen die de geschiedenis vastleggen. <color=\"grey\"> <br> Geeft geen bonussen.",
    "pt-BR": "Uma homenagem para aqueles que registram a história. <color=\"grey\"> <br> Não fornece nenhum bônus.",
    "ru": "Дань уважения летописцам.<color=\"grey\"><br>Не даёт преимуществ.",
    "tr": "Tarih yazanlara bir ağıt... <color=\"grey\"> <br> İlave özellik sağlamaz.",
    "zh-CN": "致敬历史的记录者。<color=\"grey\"><br>没有特殊效果。",
    "zh-TW": "象徵對記錄歷史之人的崇敬。<color=\"grey\"><br>沒有特殊效果。"
  },
  "descriptionPlain": {
    "ar": "تقديرًا لمَن يسجلون التاريخ.\nلا يمنح مزايا.",
    "de": "Eine Hommage an diejenigen, die Geschichte aufzeichnen.\nGewährt keine Boni.",
    "en": "An homage to those who record history.\nProvides no bonuses.",
    "es": "Un homenaje a los cronistas de la historia.\nNo otorga nada especial.",
    "fr": "Un hommage à tous les historiens.\nN'octroie aucun bonus.",
    "fr-CA": "Un hommage à tous les gardiens de la mémoire.\nN'octroie aucun bonus.",
    "it": "Un omaggio a chi preserva la storia.\nNon fornisce bonus.",
    "ja": "歴史を記録し、後世に残した者への敬意の象徴。\nボーナスなし。",
    "ko": "역사를 기록하는 자들에게 바치는 헌정입니다.\n특별한 효과는 없습니다.",
    "nl": "Een ode aan hen die de geschiedenis vastleggen.\nGeeft geen bonussen.",
    "pt-BR": "Uma homenagem para aqueles que registram a história.\nNão fornece nenhum bônus.",
    "ru": "Дань уважения летописцам.\nНе даёт преимуществ.",
    "tr": "Tarih yazanlara bir ağıt...\nİlave özellik sağlamaz.",
    "zh-CN": "致敬历史的记录者。\n没有特殊效果。",
    "zh-TW": "象徵對記錄歷史之人的崇敬。\n沒有特殊效果。"
  },
  "fleece": 674,
  "icon": "icons/fleeces/Fleece674.png",
  "id": "Fleece674",
  "name": {
    "ar": "رداء العالمة",
    "de": "Vlies der Gelehrten",
    "en": "Fleece of the Scholar",
    "es": "Vellocino de la Escriba",
    "fr": "Pelisse de l'érudite",
    "fr-CA": "Toison de l'érudite",
    "it": "Vello dell'erudita",
    "ja": "学者の羊毛",
    "ko": "학자의 양털",
    "nl": "Vacht van de geleerde",
    "pt-BR": "Lã da Erudição",
    "ru": "Руно учёности",
    "tr": "Âlimin Postu",
    "zh-CN": "学者毛纺",
    "zh-TW": "學者毛紡"
  },
  "namePlain": {
    "ar": "رداء العالمة",
    "de": "Vlies der Gelehrten",
    "en": "Fleece of the Scholar",
    "es": "Vellocino de la Escriba",
    "fr": "Pelisse de l'érudite",
    "fr-CA": "Toison de l'érudite",
    "it": "Vello dell'erudita",
    "ja": "学者の羊毛",
    "ko": "학자의 양털",
    "nl": "Vacht van de geleerde",
    "pt-BR": "Lã da Erudição",
    "ru": "Руно учёности",
    "tr": "Âlimin Postu",
    "zh-CN": "学者毛纺",
    "zh-TW": "學者毛紡"
  },
  "pack": "woolhaven",
  "thumb": "icons/fleeces/64/Fleece674.png"
}
